.\" $Id$
.TH CAPINFO 1
.SH NAME
capinfo \- print statistics about packet capture files
.SH SYNOPSIS
.na
.B capinfo
.I file ...
.SH DESCRIPTION
.LP
.I capinfo 
is a tool for displaying statistics about network traffic from files saved with 
\fItcpdump(8)\fP
or
\fIsnoop(1M)\fP.
.LP
For pcap files, capinfo will display the following information:
.PP
.PD 0
	byte order of the capture file
.LP
	libpcap version used for packet capture
.LP
	capture timezone (usually empty)
.LP
	significant figures of timestamps (usually empty)
.LP
	snap length: maximum packet size captured
.LP
	data link type
.LP
	number of packets and bytes
.LP
	number of snaplen truncated packets
.LP
	timestamp of the first and last packets
.PD
.LP
For snoop files, capinfo will display the following information:
.PP
.PD 0
.LP
	snoop version used for packet capture
.LP
	data link type
.LP
	number of packets and bytes
.LP
	number of snaplen truncated packets
.LP
	timestamp of the first and last packets
.PD
.LP
.SH "SEE ALSO"
tcpreplay(8), tcpdump(8), snoop(1M), editcap(1)
.SH AUTHORS
Matt Bing <mbing@nfr.net>
Aaron Turner <aturner@pobox.com>
.SH AVAILABILITY
The current version is available with the tcpreplay package at:
.LP
.RS
.I http://www.sourceforge.net/projects/tcpreplay/
.RE
.SH BUGS
None known. 
.LP
Please send bug reports to tcpreplay-users@lists.sourceforge.net.


