#ifndef __xX_H__
#define __xX_H__

/*
 * Functions for processing args/data generated by -x and -X
 */

/*
 * requires globals:
 * int include_exclude_mode;
 * CIDR *xX_cidr = NULL;
 * LIST *xX_list = NULL;
 */
 

void *parse_xX_str(char, char *);
int process_xX_by_cidr(int, CIDR *, ip_hdr_t *);


/*
 * Include/Exclude (xXmode) values
 */
#define xXSource 1
#define xXDest 2
#define xXBoth 3
#define xXEither 4
#define xXPacket 5
#define xXExclude 128 /* if exclude mode, add 128 to above value */


#endif
