/*  -*- buffer-read-only: t -*- vi: set ro:
 * 
 * DO NOT EDIT THIS FILE   (ao-strs.h)
 * 
 * It has been AutoGen-ed  August 11, 2012 at 09:41:13 AM by AutoGen 5.16.2pre7
 * From the definitions    ao-strs.def
 * and the template file   strings
 *
 *  Copyright (C) 2011-2012 Bruce Korb, all rights reserved.
 *  This is free software. It is licensed for use, modification and
 *  redistribution under the terms of the
 *  Modified (3 clause) Berkeley Software Distribution License
 *    <http://www.xfree86.org/3.3.6/COPYRIGHT2.html>
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *  1. Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *  2. Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *  3. Neither the name ``Bruce Korb'' nor the name of any other
 *     contributor may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *  
 *  strings IS PROVIDED BY Bruce Korb ``AS IS'' AND ANY EXPRESS
 *  OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 *  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 *  ARE DISCLAIMED.  IN NO EVENT SHALL Bruce Korb OR ANY OTHER CONTRIBUTORS
 *  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 *  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 *  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 *  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 *  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef STRINGS_AO_STRS_H_GUARD
#define STRINGS_AO_STRS_H_GUARD 1
/*
 * 102 strings in ao_strs_strtable string table
 */
#define ARG_BREAK_STR               (ao_strs_strtable+0)
#define ARG_BREAK_STR_LEN           5
#define ARG_BY_NUM_FMT              (ao_strs_strtable+180)
#define ARG_BY_NUM_FMT_LEN          9
#define BOOL_ATR_FMT                (ao_strs_strtable+6198)
#define BOOL_ATR_FMT_LEN            31
#define BULLET_STR                  (ao_strs_strtable+401)
#define BULLET_STR_LEN              6
#define DEEP_INDENT_STR             (ao_strs_strtable+408)
#define DEEP_INDENT_STR_LEN         6
#define EMPTY_ARG                   (ao_strs_strtable+169)
#define EMPTY_ARG_LEN               2
#define END_MARK                    (ao_strs_strtable+1620)
#define END_MARK_LEN                115
#define END_OPT_SEL_STR             (ao_strs_strtable+98)
#define END_OPT_SEL_STR_LEN         12
#define END_PRE_FMT                 (ao_strs_strtable+718)
#define END_PRE_FMT_LEN             36
#define END_SET_TEXT                (ao_strs_strtable+360)
#define END_SET_TEXT_LEN            3
#define END_XML_FMT                 (ao_strs_strtable+6152)
#define END_XML_FMT_LEN             6
#define ENUM_ERR_SEP_LINE_FMT       (ao_strs_strtable+474)
#define ENUM_ERR_SEP_LINE_FMT_LEN   5
#define ENUM_ERR_STR_WIDTH_FMT      (ao_strs_strtable+480)
#define ENUM_ERR_STR_WIDTH_FMT_LEN  6
#define EXPORT_ARG_FMT              (ao_strs_strtable+190)
#define EXPORT_ARG_FMT_LEN          17
#define FALSE_STR                   (ao_strs_strtable+263)
#define FALSE_STR_LEN               5
#define FLAG_OPT_MARK               (ao_strs_strtable+88)
#define FLAG_OPT_MARK_LEN           9
#define FLAG_STR                    (ao_strs_strtable+342)
#define FLAG_STR_LEN                4
#define INIT_LOPT_STR               (ao_strs_strtable+3387)
#define INIT_LOPT_STR_LEN           250
#define INIT_OPT_STR                (ao_strs_strtable+4417)
#define INIT_OPT_STR_LEN            116
#define INVALID_FMT                 (ao_strs_strtable+6)
#define INVALID_FMT_LEN             10
#define INVALID_STR                 (ao_strs_strtable+17)
#define INVALID_STR_LEN             9
#define LONG_OPT_MARK               (ao_strs_strtable+68)
#define LONG_OPT_MARKER             (ao_strs_strtable+398)
#define LONG_OPT_MARKER_LEN         2
#define LONG_OPT_MARK_LEN           10
#define LONG_USE_STR                (ao_strs_strtable+332)
#define LONG_USE_STR_LEN            9
#define LOOP_STR                    (ao_strs_strtable+1006)
#define LOOP_STR_LEN                193
#define LOPT_ARG_FMT                (ao_strs_strtable+3638)
#define LOPT_ARG_FMT_LEN            778
#define MORE_STR                    (ao_strs_strtable+63)
#define MORE_STR_LEN                4
#define MULTI_ARG_FMT               (ao_strs_strtable+2296)
#define MULTI_ARG_FMT_LEN           123
#define MULTI_DEF_FMT               (ao_strs_strtable+755)
#define MULTI_DEF_FMT_LEN           120
#define NESTED_OPT_FMT              (ao_strs_strtable+6172)
#define NESTED_OPT_FMT_LEN          17
#define NLSTR_FMT                   (ao_strs_strtable+40)
#define NLSTR_FMT_LEN               3
#define NLSTR_SPACE_FMT             (ao_strs_strtable+79)
#define NLSTR_SPACE_FMT_LEN         5
#define NONE_STR                    (ao_strs_strtable+27)
#define NONE_STR_LEN                4
#define NOT_FOUND_STR               (ao_strs_strtable+417)
#define NOT_FOUND_STR_LEN           56
#define NO_ARG_NEEDED               (ao_strs_strtable+295)
#define NO_ARG_NEEDED_LEN           17
#define NO_LOAD_WARN                (ao_strs_strtable+5913)
#define NO_LOAD_WARN_LEN            46
#define NO_MULTI_ARG_FMT            (ao_strs_strtable+2667)
#define NO_MULTI_ARG_FMT_LEN        140
#define NO_SAVE_OPTS                (ao_strs_strtable+5960)
#define NO_SAVE_OPTS_LEN            46
#define NO_SGL_ARG_FMT              (ao_strs_strtable+2808)
#define NO_SGL_ARG_FMT_LEN          306
#define NO_SUPPRESS_LOAD            (ao_strs_strtable+6007)
#define NO_SUPPRESS_LOAD_LEN        65
#define NULL_ATR_FMT                (ao_strs_strtable+6140)
#define NULL_ATR_FMT_LEN            6
#define NUMB_ATR_FMT                (ao_strs_strtable+6230)
#define NUMB_ATR_FMT_LEN            34
#define OK_NEED_OPT_ARG             (ao_strs_strtable+277)
#define OK_NEED_OPT_ARG_LEN         17
#define ONE_TAB_STR                 (ao_strs_strtable+415)
#define ONE_TAB_STR_LEN             1
#define ONLY_OPTS_LOOP              (ao_strs_strtable+1200)
#define ONLY_OPTS_LOOP_LEN          89
#define OPEN_CLOSE_FMT              (ao_strs_strtable+6140)
#define OPEN_CLOSE_FMT_LEN          6
#define OPEN_XML_FMT                (ao_strs_strtable+6147)
#define OPEN_XML_FMT_LEN            4
#define OPTION_STR                  (ao_strs_strtable+364)
#define OPTION_STR_LEN              6
#define OPT_ARG_FMT                 (ao_strs_strtable+4534)
#define OPT_ARG_FMT_LEN             1153
#define OPT_END_FMT                 (ao_strs_strtable+154)
#define OPT_END_FMT_LEN             14
#define OPT_VAL_FMT                 (ao_strs_strtable+147)
#define OPT_VAL_FMT_LEN             6
#define OR_STR                      (ao_strs_strtable+36)
#define OR_STR_LEN                  3
#define PAGER_NAME                  (ao_strs_strtable+44)
#define PAGER_NAME_LEN              5
#define PAGE_USAGE_FMT              (ao_strs_strtable+487)
#define PAGE_USAGE_FMT_LEN          42
#define PLUS_STR                    (ao_strs_strtable+32)
#define PLUS_STR_LEN                3
#define PREAMBLE_FMT                (ao_strs_strtable+612)
#define PREAMBLE_FMT_LEN            105
#define QUOT_APOS                   (ao_strs_strtable+172)
#define QUOT_APOS_LEN               2
#define QUOT_ARG_FMT                (ao_strs_strtable+175)
#define QUOT_ARG_FMT_LEN            4
#define SAVE_WARN                   (ao_strs_strtable+6104)
#define SAVE_WARN_LEN               35
#define SET_NO_TEXT_FMT             (ao_strs_strtable+6073)
#define SET_NO_TEXT_FMT_LEN         30
#define SET_OFF_FMT                 (ao_strs_strtable+391)
#define SET_OFF_FMT_LEN             6
#define SET_TEXT_FMT                (ao_strs_strtable+347)
#define SET_TEXT_FMT_LEN            12
#define SGL_ARG_FMT                 (ao_strs_strtable+2420)
#define SGL_ARG_FMT_LEN             246
#define SGL_DEF_FMT                 (ao_strs_strtable+876)
#define SGL_DEF_FMT_LEN             67
#define SGL_NO_DEF_FMT              (ao_strs_strtable+944)
#define SGL_NO_DEF_FMT_LEN          61
#define SHELL_MAGIC                 (ao_strs_strtable+140)
#define SHELL_MAGIC_LEN             6
#define SHOW_PROG_ENV               (ao_strs_strtable+371)
#define SHOW_PROG_ENV_LEN           19
#define SHOW_VAL_FMT                (ao_strs_strtable+240)
#define SHOW_VAL_FMT_LEN            17
#define START_MARK                  (ao_strs_strtable+530)
#define START_MARK_LEN              81
#define STDOUT                      (ao_strs_strtable+111)
#define STDOUT_LEN                  6
#define TIME_FMT                    (ao_strs_strtable+118)
#define TIME_FMT_LEN                21
#define TMP_USAGE_FMT               (ao_strs_strtable+50)
#define TMP_USAGE_FMT_LEN           12
#define TRUE_STR                    (ao_strs_strtable+258)
#define TRUE_STR_LEN                4
#define TWO_SPACES_STR              (ao_strs_strtable+85)
#define TWO_SPACES_STR_LEN          2
#define TYPE_ATR_FMT                (ao_strs_strtable+6159)
#define TYPE_ATR_FMT_LEN            12
#define UNK_OPT_FMT                 (ao_strs_strtable+1834)
#define UNK_OPT_FMT_LEN             141
#define VER_STR                     (ao_strs_strtable+269)
#define VER_STR_LEN                 7
#define XML_HEX_BYTE_FMT            (ao_strs_strtable+6190)
#define XML_HEX_BYTE_FMT_LEN        7
#define YES_NEED_OPT_ARG            (ao_strs_strtable+313)
#define YES_NEED_OPT_ARG_LEN        18
#define apostrophy                  (ao_strs_strtable+221)
#define apostrophy_LEN              4
#define arg_fmt                     (ao_strs_strtable+215)
#define arg_fmt_LEN                 5
#define init_optct                  (ao_strs_strtable+226)
#define init_optct_LEN              13
#define set_dash                    (ao_strs_strtable+208)
#define set_dash_LEN                6
#define zCantArg                    (ao_strs_strtable+3267)
#define zCantArg_LEN                119
#define zCmdFmt                     (ao_strs_strtable+2101)
#define zCmdFmt_LEN                 15
#define zCountTest                  (ao_strs_strtable+2117)
#define zCountTest_LEN              178
#define zEquivMode                  (ao_strs_strtable+5868)
#define zEquivMode_LEN              44
#define zFullOptFmt                 (ao_strs_strtable+5833)
#define zFullOptFmt_LEN             34
#define zLoopEnd                    (ao_strs_strtable+1290)
#define zLoopEnd_LEN                329
#define zMayArg                     (ao_strs_strtable+3115)
#define zMayArg_LEN                 119
#define zMustArg                    (ao_strs_strtable+3235)
#define zMustArg_LEN                31
#define zOptCookieCt                (ao_strs_strtable+5730)
#define zOptCookieCt_LEN            38
#define zOptCtFmt                   (ao_strs_strtable+5769)
#define zOptCtFmt_LEN               30
#define zOptDisabl                  (ao_strs_strtable+5800)
#define zOptDisabl_LEN              32
#define zOptNumFmt                  (ao_strs_strtable+5688)
#define zOptNumFmt_LEN              41
#define zOptionCase                 (ao_strs_strtable+1736)
#define zOptionCase_LEN             30
#define zOptionEndSelect            (ao_strs_strtable+1817)
#define zOptionEndSelect_LEN        16
#define zOptionFlag                 (ao_strs_strtable+1801)
#define zOptionFlag_LEN             15
#define zOptionFullName             (ao_strs_strtable+1785)
#define zOptionFullName_LEN         15
#define zOptionPartName             (ao_strs_strtable+1767)
#define zOptionPartName_LEN         17
#define zPagedUsageExit             (ao_strs_strtable+2027)
#define zPagedUsageExit_LEN         73
#define zTextExit                   (ao_strs_strtable+1976)
#define zTextExit_LEN               50
extern char const ao_strs_strtable[6265];

#endif /* STRINGS_AO_STRS_H_GUARD */
