= tcpreplay(1)
:doctype: manpage
:manmanual: Tcpreplay Suite
:mansource: Tcpreplay Suite
:man-linkstyle: pass:[blue R < >]

== NAME

tcpreplay - Replay network traffic stored in pcap files

== SYNOPSIS

*tcpreplay* *-i* _interface_ [_OPTION_]... _<pcap_file(s)>_ | _<pcap_dir(s)>_

== DESCRIPTION

*tcpreplay* is a tool for replaying network traffic from files saved with
tcpdump or other tools which write pcap(3) files.

The basic operation of tcpreplay is to resend all packets from the input
file(s) at the speed at which they were recorded, or a specified data rate, up
to as fast as the hardware is capable. Optionally, the traffic can be split
between two interfaces, written to files, filtered and edited in various ways,
providing the means to test firewalls, NIDS and other network devices.

For more details, please see the Tcpreplay Manual at: http://tcpreplay.appneta.com

== OPTIONS

// Shared tcpreplay options.
include::tcpreplay_options.adoc[]

*-V, --version*::
  Print version information and exit.

*-h, --less-help*::
  Display abbreviated usage information and exit.

*-H, --help*::
  Display extended usage information (including per-option constraints) and
  exit.

== SIGNALS

tcpreplay understands the following signals:

*SIGUSR1*::
  Suspend tcpreplay.

*SIGCONT*::
  Restart tcpreplay.

== EXIT STATUS

One of the following exit values will be returned:

*0* (EXIT_SUCCESS)::
  Successful program execution.

*1* (EXIT_FAILURE)::
  The operation failed or the command syntax was not valid.

== SEE ALSO

tcpdump(1), tcpbridge(1), tcprewrite(1), tcpprep(1), tcpcapinfo(1)

== BUGS

tcpreplay can only send packets as fast as your computer's interface,
processor, disk and system bus will allow.

Packet timing at high speeds is a black art and very OS/CPU dependent.

Replaying captured traffic may simulate odd or broken conditions on your
network and cause all sorts of problems.

In most cases, you can not replay traffic back to/at a server.

Some operating systems by default do not allow forging source MAC addresses.
Please consult your operating system's documentation and the tcpreplay FAQ if
you experience this issue.

== AUTHORS

Copyright 2026 Gabriel Ganne

Copyright 2013-2025 Fred Klassen - AppNeta

Copyright 2000-2012 Aaron Turner

For support please use the tcpreplay-users@lists.sourceforge.net mailing list.

The latest version of this software is always available from:
http://tcpreplay.appneta.com/

== COPYRIGHT

The entire Tcpreplay Suite is licensed under the GPLv3.
