= tcpreplay-edit(1)
:doctype: manpage
:manmanual: Tcpreplay Suite
:mansource: Tcpreplay Suite
:man-linkstyle: pass:[blue R < >]

== NAME

tcpreplay-edit - Replay network traffic stored in pcap files, editing the
packets on the fly

== SYNOPSIS

*tcpreplay-edit* *-i* _interface_ [_OPTION_]... _<pcap_file(s)>_ | _<pcap_dir(s)>_

== DESCRIPTION

*tcpreplay-edit* is the packet-editing variant of tcpreplay(1). In addition to
replaying network traffic from pcap(3) files, it can rewrite and edit the
packets as they are sent, using the same tcpedit engine as tcprewrite(1).

The basic operation is to resend all packets from the input file(s) at the
speed at which they were recorded, or a specified data rate, while optionally
splitting the traffic between two interfaces and applying edits such as MAC/IP
rewriting, VLAN tagging and DLT conversion.

For more details, please see the Tcpreplay Manual at: http://tcpreplay.appneta.com

== OPTIONS

// Shared tcpreplay options.
include::tcpreplay_options.adoc[]

*-e, --endpoints*=_string_::
  Rewrite all traffic to appear to be between two endpoints. Takes a pair of
  colon delimited IPv4/v6 addresses. Requires *--cachefile*.
+
....
--endpoints=172.16.0.1:172.16.0.2
--endpoints=[2001:db8::dead:beef]:[::ffff:0:0:ac:f:0:2]
....

// Shared tcpedit / DLT-plugin editing options.
include::tcpedit_options.adoc[]

*-V, --version*::
  Print version information and exit.

*-h, --less-help*::
  Display abbreviated usage information and exit.

*-H, --help*::
  Display extended usage information (including per-option constraints) and
  exit.

== SIGNALS

tcpreplay-edit understands the following signals:

*SIGUSR1*::
  Suspend tcpreplay-edit.

*SIGCONT*::
  Restart tcpreplay-edit.

== EXIT STATUS

One of the following exit values will be returned:

*0* (EXIT_SUCCESS)::
  Successful program execution.

*1* (EXIT_FAILURE)::
  The operation failed or the command syntax was not valid.

== SEE ALSO

tcpdump(1), tcpbridge(1), tcprewrite(1), tcpprep(1), tcpcapinfo(1)

== BUGS

tcpreplay-edit can only send packets as fast as your computer's interface,
processor, disk and system bus will allow.

Packet timing at high speeds is a black art and very OS/CPU dependent.

Replaying captured traffic may simulate odd or broken conditions on your
network and cause all sorts of problems.

Some operating systems by default do not allow forging source MAC addresses.
Please consult your operating system's documentation and the tcpreplay FAQ if
you experience this issue.

== AUTHORS

Copyright 2026 Gabriel Ganne

Copyright 2013-2025 Fred Klassen - AppNeta

Copyright 2000-2012 Aaron Turner

For support please use the tcpreplay-users@lists.sourceforge.net mailing list.

The latest version of this software is always available from:
http://tcpreplay.appneta.com/

== COPYRIGHT

The entire Tcpreplay Suite is licensed under the GPLv3.
