= tcprewrite(1)
:doctype: manpage
:manmanual: Tcpreplay Suite
:mansource: Tcpreplay Suite
:man-linkstyle: pass:[blue R < >]

== NAME

tcprewrite - Rewrite the packets in a pcap file

== SYNOPSIS

*tcprewrite* *-i* _infile.pcap_ *-o* _outfile.pcap_ [_OPTION_]...

== DESCRIPTION

*tcprewrite* is a tool to rewrite packets stored in pcap(3) file format, such as
created by tcpdump(1) and wireshark(1). Once a pcap file has had its packets
rewritten, they can be replayed back out on the network using tcpreplay(1).

tcprewrite currently supports reading the following DLT types: DLT_C_HDLC
(Cisco HDLC), DLT_EN10MB (Ethernet), DLT_LINUX_SLL / DLT_LINUX_SLL2 (Linux
Cooked Socket), DLT_RAW (RAW IP), DLT_NULL (BSD Loopback), DLT_LOOP (OpenBSD
Loopback), DLT_IEEE802_11 (802.11a/b/g), DLT_IEEE802_11_RADIO (with Radiotap
headers), DLT_JUNIPER_ETHER (Juniper Encapsulated Ethernet) and DLT_PPP_SERIAL
(PPP over Serial). Please see the *--dlt* option for supported output DLT types.

The packet editing features which distinguish between "client" and "server"
traffic require a tcpprep(1) cache file.

For more details, please see the Tcpreplay Manual at: http://tcpreplay.appneta.com

== OPTIONS

*-d, --dbug*=_number_::
  Enable debugging output. Takes an integer in the range 0 through 5 (default
  0). Only available if the program was configured with *--enable-debug*;
  higher numbers increase verbosity.

*-i, --infile*=_string_::
  Input pcap file to be processed. Required.

*-o, --outfile*=_string_::
  Output pcap file. Required.

*-c, --cachefile*=_string_::
  Split traffic based upon client/server relationships using a tcpprep(1) cache
  file.

*-e, --endpoints*=_string_::
  Rewrite all traffic to appear to be between two endpoints. Takes a pair of
  colon delimited IPv4/v6 addresses. Requires *--cachefile*.
+
....
--endpoints=172.16.0.1:172.16.0.2
--endpoints=[2001:db8::dead:beef]:[::ffff:0:0:ac:f:0:2]
....

// Shared tcpedit / DLT-plugin options.
include::tcpedit_options.adoc[]

*-v, --verbose*::
  Print decoded packets via tcpdump to STDOUT. Only available if the program
  was configured with *--enable-verbose*.

*-A, --decode*=_string_::
  Arguments passed to the tcpdump decoder when *--verbose* is used. By default
  -n and -l are used. Be sure to quote the arguments so they are not interpreted
  by tcprewrite. Requires *--verbose*.

*--fragroute*=_string_::
  Enable advanced evasion techniques using the built-in fragroute(8) engine.
  See the fragroute(8) man page for details. The delay, echo and print commands
  are not supported. Only available if configured with *--enable-fragroute*.

*--fragdir*=_string_::
  Apply the fragroute engine to packets going _c2s_, _s2c_ or _both_ (when using
  a cache file). Requires *--cachefile*. Only available with *--enable-fragroute*.

*--skip-soft-errors*::
  Skip writing packets that cannot be decoded or edited (soft errors). By
  default such packets are written unedited so that tcpprep cache files can
  still be used.

*-w, --suppress-warnings*::
  Suppress printing warning messages.

*-V, --version*::
  Print version information and exit.

*-h, --less-help*::
  Display abbreviated usage information and exit.

*-H, --help*::
  Display extended usage information (including per-option constraints) and
  exit.

== EXIT STATUS

One of the following exit values will be returned:

*0* (EXIT_SUCCESS)::
  Successful program execution.

*1* (EXIT_FAILURE)::
  The operation failed or the command syntax was not valid.

== SEE ALSO

tcpdump(1), tcpbridge(1), tcpreplay(1), tcpprep(1), tcpcapinfo(1)

== AUTHORS

Copyright 2026 Gabriel Ganne

Copyright 2013-2025 Fred Klassen - AppNeta

Copyright 2000-2012 Aaron Turner

For support please use the tcpreplay-users@lists.sourceforge.net mailing list.

The latest version of this software is always available from:
http://tcpreplay.appneta.com/

== COPYRIGHT

The entire Tcpreplay Suite is licensed under the GPLv3.
