'\" t
.\"     Title: tcpbridge
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2026-07-19
.\"    Manual: Tcpreplay Suite
.\"    Source: Tcpreplay Suite
.\"  Language: English
.\"
.TH "TCPBRIDGE" "1" "2026-07-19" "Tcpreplay Suite" "Tcpreplay Suite"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
tcpbridge \- Bridge network traffic across two interfaces
.SH "SYNOPSIS"
.sp
\fBtcpbridge\fP [\fIOPTION\fP]...
.SH "DESCRIPTION"
.sp
tcpbridge is a tool for selectively bridging network traffic across two interfaces and optionally modifying the packets in between
.sp
The basic operation of tcpbridge is to be a network bridge between two subnets.  All packets received on one interface are sent via the other.
.sp
+
Optionally, packets can be edited in a variety of ways according to your needs.
.sp
+
For more details, please see the Tcpreplay Manual at: \c
.URL "http://tcpreplay.appneta.com" "" ""
.SH "OPTIONS"
.sp
\fB\-r\fP, \fB\-\-portmap\fP=\fIstring\fP
.RS 4
Rewrite TCP/UDP ports. May appear up to 9999 times.
.sp
Specify a list of comma delimited port mappings consisting of colon delimited port number pairs.  Each colon delimited port pair consists of the port to match followed by the port number to rewrite.
.sp
Examples:
.sp
.if n .RS 4
.nf
.fam C
\-\-portmap=80:8000 \-\-portmap=8080:80\&    # 80\->8000 and 8080\->80
\-\-portmap=8000,8080,88888:80\&           # 3 different ports become 80
\-\-portmap=8000\-8999:80\&                 # ports 8000 to 8999 become 80
.fam
.fi
.if n .RE
.RE
.sp
\fB\-s\fP, \fB\-\-seed\fP=\fInumber\fP
.RS 4
Randomize src/dst IPv4/v6 addresses w/ given seed. Cannot be combined with: \fB\-\-fuzz\-seed\fP.
.sp
Causes the source and destination IPv4/v6 addresses to be pseudo randomized but still maintain client/server relationships. Since the randomization is deterministic based on the seed, you can reuse the same seed value to recreate the traffic.
.RE
.sp
\fB\-N\fP, \fB\-\-pnat\fP=\fIstring\fP
.RS 4
Rewrite IPv4/v6 addresses using pseudo\-NAT. May appear up to 2 times. Cannot be combined with: \fB\-\-srcipmap\fP.
.sp
Takes a comma delimited series of colon delimited CIDR netblock pairs.  Each netblock pair is evaluated in order against the IP addresses.  If the IP address in the packet matches the first netblock, it is rewritten using the second netblock as a mask against the high order bits.
.sp
IPv4 Example:
.sp
.if n .RS 4
.nf
.fam C
\-\-pnat=192.168.0.0/16:10.77.0.0/16,172.16.0.0/12:10.1.0.0/24
.fam
.fi
.if n .RE
.sp
IPv6 Example:
.sp
.if n .RS 4
.nf
.fam C
\-\-pnat=[2001:db8::/32]:[dead::/16],[2001:db8::/32]:[::ffff:0:0/96]
.fam
.fi
.if n .RE
.RE
.sp
\fB\-S\fP, \fB\-\-srcipmap\fP=\fIstring\fP
.RS 4
Rewrite source IPv4/v6 addresses using pseudo\-NAT. Cannot be combined with: \fB\-\-pnat\fP.
.sp
Works just like the \-\-pnat option, but only affects the source IP addresses in the IPv4/v6 header.
.RE
.sp
\fB\-D\fP, \fB\-\-dstipmap\fP=\fIstring\fP
.RS 4
Rewrite destination IPv4/v6 addresses using pseudo\-NAT. Cannot be combined with: \fB\-\-pnat\fP.
.sp
Works just like the \-\-pnat option, but only affects the destination IP addresses in the IPv4/v6 header.
.RE
.sp
\fB\-e\fP, \fB\-\-endpoints\fP=\fIstring\fP
.RS 4
Rewrite IP addresses to be between two endpoints. Requires: \fB\-\-cachefile\fP.
.sp
Takes a pair of colon delimited IPv4/v6 addresses which will be used to rewrite all traffic to appear to be between the two IP addresses.
.sp
IPv4 Example:
.sp
.if n .RS 4
.nf
.fam C
\-\-endpoints=172.16.0.1:172.16.0.2
.fam
.fi
.if n .RE
.sp
IPv6 Example:
.sp
.if n .RS 4
.nf
.fam C
\-\-endpoints=[2001:db8::dead:beef]:[::ffff:0:0:ac:f:0:2]
.fam
.fi
.if n .RE
.RE
.sp
\fB\-\-tcp\-sequence\fP=\fInumber\fP
.RS 4
Change TCP Sequence (and ACK) numbers /w given seed. Range: 1 to any. Default: \f(CR0\fP.
.sp
Change all TCP sequence numbers, and related sequence\-acknowledgement numbers. They will be shifted by a random amount based on the provided seed.
.RE
.sp
\fB\-b\fP, \fB\-\-skipbroadcast\fP
.RS 4
Skip rewriting broadcast/multicast IPv4/v6 addresses.
.sp
By default \-\-seed, \-\-pnat and \-\-endpoints will rewrite broadcast and multicast IPv4/v6 and MAC addresses.	Setting this flag will keep broadcast/multicast IPv4/v6 and MAC addresses from being rewritten.
.RE
.sp
\fB\-C\fP, \fB\-\-fixcsum\fP
.RS 4
Force recalculation of IPv4/TCP/UDP header checksums.
.sp
Causes each IPv4/v6 packet to have their checksums recalculated and fixed.  Automatically enabled for packets modified with \f(CR\-\-seed\fP, \f(CR\-\-pnat\fP, \f(CR\-\-endpoints\fP or \f(CR\-\-fixlen\fP.
.RE
.sp
\fB\-\-fixhdrlen\fP
.RS 4
Alter IP/TCP header len to match packet length.
.sp
By default, tcpreplay will send packets with the original packet length, However, you may want the packet length revised to minimum packet size. Using this option, tcpreplay will rewrite (fix) the packet length, and recalculate checksums when packet length changes. Caution: undesired packet changes may occur when this option is specified.
.RE
.sp
\fB\-m\fP, \fB\-\-mtu\fP=\fInumber\fP
.RS 4
Override default MTU length (1500 bytes). Range: 1 to MAX_SNAPLEN.
.sp
Override the default 1500 byte MTU size for determining the maximum padding length (\-\-fixlen=pad) or when truncating (\-\-mtu\-trunc).
.RE
.sp
\fB\-\-mtu\-trunc\fP
.RS 4
Truncate packets larger then specified MTU.
.sp
Similar to \-\-fixlen, this option will truncate data in packets from Layer 3 and above to be no larger then the MTU.
.RE
.sp
\fB\-E\fP, \fB\-\-efcs\fP
.RS 4
Remove Ethernet checksums (FCS) from end of frames.
.sp
Note, this option is pretty dangerous!  We do not actually check to see if a FCS actually exists in the frame, we just blindly delete the last 4 bytes.  Hence, you should only use this if you know know that your OS provides the FCS when reading raw packets.
.RE
.sp
\fB\-\-ttl\fP=\fIstring\fP
.RS 4
Modify the IPv4/v6 TTL/Hop Limit.
.sp
Allows you to modify the TTL/Hop Limit of all the IPv4/v6 packets.  Specify a number to hard\-code the value or +/\-value to increase or decrease by the value provided (limited to 1\-255).
.sp
Examples:
.sp
.if n .RS 4
.nf
.fam C
\-\-ttl=10
\-\-ttl=+7
\-\-ttl=\-64
.fam
.fi
.if n .RE
.RE
.sp
\fB\-\-tos\fP=\fInumber\fP
.RS 4
Set the IPv4 TOS/DiffServ/ECN byte. Range: 0 to 255.
.sp
Allows you to override the TOS (also known as DiffServ/ECN) value in IPv4.
.RE
.sp
\fB\-\-tclass\fP=\fInumber\fP
.RS 4
Set the IPv6 Traffic Class byte. Range: 0 to 255.
.sp
Allows you to override the IPv6 Traffic Class field.
.RE
.sp
\fB\-\-flowlabel\fP=\fInumber\fP
.RS 4
Set the IPv6 Flow Label. Range: 0 to 1048575.
.sp
Allows you to override the 20bit IPv6 Flow Label field.  Has no effect on IPv4 packets.
.RE
.sp
\fB\-F\fP, \fB\-\-fixlen\fP=\fIstring\fP
.RS 4
Pad or truncate packet data to match header length.
.sp
Packets may be truncated during capture if the snaplen is smaller then the packet.  This option allows you to modify the packet to pad the packet back out to the size stored in the IPv4/v6 header or rewrite the IP header total length to reflect the stored packet length. @table @bullet @item \fIpad\fP Truncated packets will be padded out so that the packet length matches the IPv4 total length @item \fItrunc\fP Truncated packets will have their IPv4 total length field rewritten to match the actual packet length @item \fIdel\fP Delete the packet
.RE
.sp
\fB\-\-fuzz\-seed\fP=\fInumber\fP
.RS 4
Fuzz 1 in X packets. Edit bytes, length, or emulate packet drop. Range: 0 to any. Default: \f(CR0\fP.
.sp
This fuzzing was designed as to test layer 7 protocols such as voip protocols. It modifies randomly 1 out of X packets (where X = \fI\-\-fuzz\-factor\fP) in order for stateful protocols to cover more of their code.  The random fuzzing actions focus on data start and end because it often is the part of the data application protocols base their decisions on.
.sp
Possible fuzzing actions list: * drop packet * reduce packet size * edit packet Bytes:
.sp
.if n .RS 4
.nf
.fam C
   * Not all Bytes have the same probability of appearance in real life.
     Replace with 0x00, 0xFF, or a random byte with equal likelihood.
   * Not all Bytes have the same significance in a packet.
     Replace the start, the end, or the middle of the packet with equal likelihood.
.fam
.fi
.if n .RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
do nothing (7 out of 8 packets)
.RE
.RE
.sp
\fB\-\-fuzz\-factor\fP=\fInumber\fP
.RS 4
Set the Fuzz 1 in X packet ratio (default 1 in 8 packets). Range: 1 to any. Default: \f(CR8\fP. Requires: \fB\-\-fuzz\-seed\fP.
.sp
Sets the ratio of for \fI\-\-fuzz\-seed\fP option. By default this value is 8, which means 1 in 8 packets are modified by fuzzing. Note that this ratio is based on the random number generated by the supplied fuzz seed. Therefore by default you cannot expect that exactly every eighth packet will be modified.
.RE
.sp
\fB\-\-skipl2broadcast\fP
.RS 4
Skip rewriting broadcast/multicast Layer 2 addresses.
.sp
By default, editing Layer 2 addresses will rewrite broadcast and multicast MAC addresses.	Setting this flag will keep broadcast/multicast MAC addresses from being rewritten.
.RE
.sp
\fB\-\-dlt\fP=\fIstring\fP
.RS 4
Override output DLT encapsulation.
.sp
By default, no DLT (data link type) conversion will be made. To change the DLT type of the output pcap, select one of the following values:
.sp
\fBenet\fP
.RS 4
Ethernet aka DLT_EN10MB
.RE
.sp
\fBhdlc\fP
.RS 4
Cisco HDLC aka DLT_C_HDLC
.RE
.sp
\fBjnpr_eth\fP
.RS 4
Juniper Ethernet DLT_C_JNPR_ETHER
.RE
.sp
\fBpppserial\fP
.RS 4
PPP Serial aka DLT_PPP_SERIAL
.RE
.sp
\fBuser\fP
.RS 4
User specified Layer 2 header and DLT type
.RE
.RE
.sp
\fB\-\-enet\-dmac\fP=\fIstring\fP
.RS 4
Override destination ethernet MAC addresses.
.sp
Takes a pair of comma deliminated ethernet MAC addresses which will replace the destination MAC address of outbound packets. The first MAC address will be used for the server to client traffic and the optional second MAC address will be used for the client to server traffic.
.sp
Example:
.sp
.if n .RS 4
.nf
.fam C
\-\-enet\-dmac=00:12:13:14:15:16,00:22:33:44:55:66
.fam
.fi
.if n .RE
.RE
.sp
\fB\-\-enet\-smac\fP=\fIstring\fP
.RS 4
Override source ethernet MAC addresses.
.sp
Takes a pair of comma deliminated ethernet MAC addresses which will replace the source MAC address of outbound packets. The first MAC address will be used for the server to client traffic and the optional second MAC address will be used for the client to server traffic.
.sp
Example:
.sp
.if n .RS 4
.nf
.fam C
\-\-enet\-smac=00:12:13:14:15:16,00:22:33:44:55:66
.fam
.fi
.if n .RE
.RE
.sp
\fB\-\-enet\-subsmac\fP=\fIstring\fP
.RS 4
Substitute MAC addresses. May appear up to 9999 times.
.sp
Allows you to rewrite ethernet MAC addresses of packets. It takes comma delimited pair or MACs address and rewrites all occurrences of the first MAC with the value of the second MAC. Example:
.sp
.if n .RS 4
.nf
.fam C
\-\-enet\-subsmac=00:12:13:14:15:16,00:22:33:44:55:66
.fam
.fi
.if n .RE
.RE
.sp
\fB\-\-enet\-mac\-seed\fP=\fInumber\fP
.RS 4
Randomize MAC addresses. Cannot be combined with: \fB\-\-enet\-smac\fP, \fB\-\-enet\-dmac\fP, \fB\-\-enet\-subsmac\fP.
.sp
Allows you to randomize ethernet MAC addresses of packets, mostly like what \fI\-\-seed\fP option does for IPv4/IPv6 addresses.
.RE
.sp
\fB\-\-enet\-mac\-seed\-keep\-bytes\fP=\fInumber\fP
.RS 4
Randomize MAC addresses. Range: 1 to 6. Requires: \fB\-\-enet\-mac\-seed\fP.
.sp
Keep some bytes untouched when usinging \fI\-\-enet\-mac\-seed\fP option.
.RE
.sp
\fB\-\-enet\-vlan\fP=\fIstring\fP
.RS 4
Specify ethernet 802.1q VLAN tag mode.
.sp
Allows you to rewrite ethernet frames to add a 802.1q header to standard 802.3 ethernet headers or remove the 802.1q VLAN tag information. @table @bullet @item \fIadd\fP Adds an 802.1q VLAN header to the existing 802.3 ethernet header. If a VLAN header already exists, a new VLAN header is added outside of the existing header.
.sp
Note that you will be allowed to run this option multiple times to create more than 2 VLAN headers, however those packets will be valid. At most you should have 2 X 802.1q VLAN tags, or outer an 802.1ad and an inner 802.1q VLAN tag. @item \fIdel\fP Rewrites the existing 802.1q VLAN header as an 802.3 ethernet header
.RE
.sp
\fB\-\-enet\-vlan\-tag\fP=\fInumber\fP
.RS 4
Specify the new ethernet 802.1q VLAN tag value. Range: 0 to 4095. Requires: \fB\-\-enet\-vlan\fP.
.sp
Mandatory when \fI\-\-enet\-vlan=add\fP is used on packets that are not already VLAN tagged.
.RE
.sp
\fB\-\-enet\-vlan\-cfi\fP=\fInumber\fP
.RS 4
Specify the ethernet 802.1q VLAN CFI value. Range: 0 to 1. Requires: \fB\-\-enet\-vlan\fP.
.sp
When omitted, the CFI bit of an existing VLAN header is preserved; a newly added tag on a previously untagged packet defaults to 0 (a one\-time notice is printed).
.RE
.sp
\fB\-\-enet\-vlan\-pri\fP=\fInumber\fP
.RS 4
Specify the ethernet 802.1q VLAN priority. Range: 0 to 7. Requires: \fB\-\-enet\-vlan\fP.
.sp
When omitted, the priority of an existing VLAN header is preserved; a newly added tag on a previously untagged packet defaults to 0 (a one\-time notice is printed).
.RE
.sp
\fB\-\-enet\-vlan\-proto\fP=\fIstring\fP
.RS 4
Specify VLAN tag protocol 802.1q or 802.1ad.
.sp
Allows you to specify the protocol of the added VLAN tags. @table @bullet @item \fI802.1q\fP Specifies that 802.1q VLAN headers are to be added. This is the default. @item \fI802.1ad\fP Specifies that 802.1ad Q\-in\-Q VLAN headers are to be added. To make valid packets, input packets must already have 802.1q VLAN headers.
.RE
.sp
\fB\-\-hdlc\-control\fP=\fInumber\fP
.RS 4
Specify HDLC control value.
.sp
The Cisco HDLC header has a 1 byte "control" field.  Apparently this should always be 0, but if you can use any 1 byte value.
.RE
.sp
\fB\-\-hdlc\-address\fP=\fInumber\fP
.RS 4
Specify HDLC address.
.sp
The Cisco HDLC header has a 1 byte "address" field which has two valid values:
.sp
\fB0x0F\fP
.RS 4
Unicast
.RE
.sp
\fB0xBF\fP
.RS 4
Broadcast
.RE
.RE
.sp
You can however specify any single byte value.
.sp
\fB\-\-user\-dlt\fP=\fInumber\fP
.RS 4
Set output file DLT type.
.sp
Set the DLT value of the output pcap file.
.RE
.sp
\fB\-\-user\-dlink\fP=\fIstring\fP
.RS 4
Rewrite Data\-Link layer with user specified data. May appear up to 2 times.
.sp
Provide a series of comma deliminated hex values which will be used to rewrite or create the Layer 2 header of the packets. The first instance of this argument will rewrite both server and client traffic, but if this argument is specified a second time, it will be used for the client traffic.
.sp
Example:
.sp
.if n .RS 4
.nf
.fam C
\-\-user\-dlink=01,02,03,04,05,06,00,1A,2B,3C,4D,5E,6F,08,00
.fam
.fi
.if n .RE
.RE
.sp
\fB\-d\fP, \fB\-\-dbug\fP=\fInumber\fP
.RS 4
Enable debugging output. Range: 0 to 5. Default: \f(CR0\fP.
.sp
If configured with \-\-enable\-debug, then you can specify a verbosity level for debugging output.  Higher numbers increase verbosity.
.RE
.sp
\fB\-i\fP, \fB\-\-intf1\fP=\fIstring\fP
.RS 4
Primary interface (listen in uni\-directional mode). This option is required.
.RE
.sp
\fB\-I\fP, \fB\-\-intf2\fP=\fIstring\fP
.RS 4
Secondary interface (send in uni\-directional mode).
.RE
.sp
\fB\-u\fP, \fB\-\-unidir\fP
.RS 4
Send and receive in only one direction.
.sp
Normally, tcpbridge will send and receive traffic in both directions (bi\-directionally).  However, if you choose this option, traffic will be sent uni\-directionally.
.RE
.sp
\fB\-\-listnics\fP
.RS 4
List available network interfaces and exit.
.RE
.sp
\fB\-L\fP, \fB\-\-limit\fP=\fInumber\fP
.RS 4
Limit the number of packets to send. Range: 1 to any. Default: \f(CR\-1\fP.
.sp
By default, tcpbridge will send packets forever or until Ctrl\-C.  Alternatively, you can specify a maximum number of packets to send.
.RE
.sp
\fB\-M\fP, \fB\-\-mac\fP=\fIstring\fP
.RS 4
MAC addresses of local NIC\(cqs. May appear up to 2 times.
.sp
tcpbridge does not support detecting the MAC addresses of the local network interfaces under Windows.  Please specify both MAC addresses of the interfaces used in the bridge: \-M <intf1 mac> \-M <intf2 mac>
.RE
.sp
\fB\-x\fP, \fB\-\-include\fP=\fIstring\fP
.RS 4
Include only packets matching rule. Cannot be combined with: \fB\-\-exclude\fP.
.sp
Override default of sending all packets stored in the capture file and only send packets which match the provided rule.  Rules can be one of:
.sp
\fBS:<CIDR1>,...\fP
.RS 4
Source IP must match specified CIDR(s)
.RE
.sp
\fBD:<CIDR1>,...\fP
.RS 4
Destination IP must match specified CIDR(s)
.RE
.sp
\fBB:<CIDR1>,...\fP
.RS 4
Both source and destination IP must match specified CIDR(s)
.RE
.sp
\fBE:<CIDR1>,...\fP
.RS 4
Either IP must match specified CIDR(s)
.RE
.sp
\fBP:<LIST>\fP
.RS 4
Must be one of the listed packets where the list corresponds to the packet number in the capture file.
.sp
.if n .RS 4
.nf
.fam C
\-\-include=P:1\-5,9,15,72\-
.fam
.fi
.if n .RE
.sp
would send packets 1 through 5, the 9th and 15th packet, and packets 72 until the end of the file
.RE
.sp
\fBF:\*(Aq<bpf>\*(Aq\fP
.RS 4
BPF filter.  See the \fItcpdump(8)\fP man page for syntax.
.RE
.RE
.sp
\fB\-X\fP, \fB\-\-exclude\fP=\fIstring\fP
.RS 4
Exclude any packet matching this rule. Cannot be combined with: \fB\-\-include\fP.
.sp
Override default of sending all packets stored in the capture file and only send packets which do not match the provided rule.  Rules can be one of:
.sp
\fBS:<CIDR1>,...\fP
.RS 4
Source IP must not match specified CIDR(s)
.RE
.sp
\fBD:<CIDR1>,...\fP
.RS 4
Destination IP must not match specified CIDR(s)
.RE
.sp
\fBB:<CIDR1>,...\fP
.RS 4
Both source and destination IP must not match specified CIDR(s)
.RE
.sp
\fBE:<CIDR1>,...\fP
.RS 4
Either IP must not match specified CIDR(s)
.RE
.sp
\fBP:<LIST>\fP
.RS 4
Must not be one of the listed packets where the list corresponds to the packet number in the capture file.
.sp
.if n .RS 4
.nf
.fam C
\-\-exclude=P:1\-5,9,15,72\-
.fam
.fi
.if n .RE
.sp
would drop packets 1 through 5, the 9th and 15th packet, and packets 72 until the end of the file
.RE
.RE
.sp
\fB\-P\fP, \fB\-\-pid\fP
.RS 4
Print the PID of tcpbridge at startup.
.RE
.sp
\fB\-v\fP, \fB\-\-verbose\fP
.RS 4
Print decoded packets via tcpdump to STDOUT.
.RE
.sp
\fB\-A\fP, \fB\-\-decode\fP=\fIstring\fP
.RS 4
Arguments passed to tcpdump decoder. Requires: \fB\-\-verbose\fP.
.sp
When enabling verbose mode (\fI\-v\fP) you may also specify one or more additional  arguments to pass to \f(CRtcpdump\fP to modify the way packets are decoded.  By default, \-n and \-l are used.   Be  sure  to quote the arguments like: \-\-verbose="\-axxx" so that they are not interpreted by tcpbridge.  The following arguments are valid:
.sp
.if n .RS 4
.nf
.fam C
    [ \-aAeNqRStuvxX ]
    [ \-E spi@ipaddr algo:secret,... ]
    [ \-s snaplen ]
.fam
.fi
.if n .RE
.RE
.sp
\fB\-V\fP, \fB\-\-version\fP
.RS 4
Print version information.
.RE
.sp
\fB\-h\fP, \fB\-\-less\-help\fP
.RS 4
Display less usage information and exit.
.RE
.sp
\fB\-w\fP, \fB\-\-suppress\-warnings\fP
.RS 4
suppress printing warning messages.
.RE
.sp
\fB\-H\fP, \fB\-\-help\fP
.RS 4
Display usage information and exit.
.RE
.sp
\fB\-\-more\-help\fP
.RS 4
Pass the extended usage information through a pager.
.RE
.sp
\fB\-\-save\-opts\fP[=\fIstring\fP]
.RS 4
Save the current option state to a config file.
.RE
.sp
\fB\-\-load\-opts\fP=\fIstring\fP, \fB\-\-no\-load\-opts\fP
.RS 4
Load options from a config file; \fB\-\-no\-load\-opts\fP disables this.
.RE
.SH "OPTION PRESETS"
.sp
Any option that is not marked as \fInot presettable\fP may be preset by loading values from configuration ("RC" or ".INI") file(s).
The homerc file is \fI$$/\fP, unless that is a directory; in that case \fI.tcpbridgerc\fP is searched for within it.
.SH "FILES"
.sp
See \fBOPTION PRESETS\fP for configuration files.
.SH "EXIT STATUS"
.sp
One of the following exit values will be returned:
.sp
\fB0\fP (EXIT_SUCCESS)
.RS 4
Successful program execution.
.RE
.sp
\fB1\fP (EXIT_FAILURE)
.RS 4
The operation failed or the command syntax was not valid.
.RE
.sp
\fB66\fP (EX_NOINPUT)
.RS 4
A specified configuration file could not be loaded.
.RE
.sp
\fB70\fP (EX_SOFTWARE)
.RS 4
libopts had an internal operational error. Please report it to \c
.MTO "autogen\-users\(atlists.sourceforge.net" "" "."
Thank you.
.RE
.SH "AUTHORS"
.sp
Copyright 2013\-2026 Fred Klassen \- AppNeta
.sp
Copyright 2000\-2012 Aaron Turner
.sp
For support please use the \c
.MTO "tcpreplay\-users\(atlists.sourceforge.net" "" ""
mailing list.
.sp
The latest version of this software is always available from: \c
.URL "http://tcpreplay.appneta.com/" "" ""
.SH "COPYRIGHT"
.sp
Copyright \(co 2000\-2026 Aaron Turner and Fred Klassen, all rights reserved.
This program is released under the terms of the GNU General Public License, version 3 or later.
.SH "BUGS"
.sp
Please send bug reports to: \c
.MTO "tcpreplay\-users\(atlists.sourceforge.net" "" ""
.SH "NOTES"
.sp
This manual page was generated from the tcpbridge option definitions.