'\" t
.\"     Title: tcpcapinfo
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2026-07-19
.\"    Manual: Tcpreplay Suite
.\"    Source: Tcpreplay Suite
.\"  Language: English
.\"
.TH "TCPCAPINFO" "1" "2026-07-19" "Tcpreplay Suite" "Tcpreplay Suite"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
tcpcapinfo \- Pcap file dissector for debugging broken pcap files
.SH "SYNOPSIS"
.sp
\fBtcpcapinfo\fP [\fIOPTION\fP]... <pcap_file(s)>
.SH "DESCRIPTION"
.sp
tcpcapinfo is a tool for decoding the structure of a pcap(3) file with a focus on finding broken pcap files and determining how two related pcap files might differ.
.sp
tcpcapinfo will first print out the pcap_file_header_t in human readable form followed by a per\-packet summary including the pcap_pkthdr_t and simple checksum value of the packet.
.SH "OPTIONS"
.sp
\fB\-d\fP, \fB\-\-dbug\fP=\fInumber\fP
.RS 4
Enable debugging output. Range: 0 to 5. Default: \f(CR0\fP.
.sp
If configured with \-\-enable\-debug, then you can specify a verbosity level for debugging output.  Higher numbers increase verbosity.
.RE
.sp
\fB\-V\fP, \fB\-\-version\fP
.RS 4
Print version information.
.RE
.sp
\fB\-H\fP, \fB\-\-help\fP
.RS 4
Display usage information and exit.
.RE
.sp
\fB\-\-more\-help\fP
.RS 4
Pass the extended usage information through a pager.
.RE
.SH "EXIT STATUS"
.sp
One of the following exit values will be returned:
.sp
\fB0\fP (EXIT_SUCCESS)
.RS 4
Successful program execution.
.RE
.sp
\fB1\fP (EXIT_FAILURE)
.RS 4
The operation failed or the command syntax was not valid.
.RE
.sp
\fB70\fP (EX_SOFTWARE)
.RS 4
libopts had an internal operational error. Please report it to \c
.MTO "autogen\-users\(atlists.sourceforge.net" "" "."
Thank you.
.RE
.SH "AUTHORS"
.sp
Copyright 2000\-2012 Aaron Turner
.sp
Copyright 2013 Fred Klassen \- AppNeta
.sp
For support please use the \c
.MTO "tcpreplay\-users\(atlists.sourceforge.net" "" ""
mailing list.
.sp
The latest version of this software is always available from: \c
.URL "http://tcpreplay.appneta.com/" "" ""
.SH "COPYRIGHT"
.sp
Copyright \(co 2000\-2012 Aaron Turner and Fred Klassen, all rights reserved.
This program is released under the terms of the GNU General Public License, version 3 or later.
.SH "BUGS"
.sp
Please send bug reports to: \c
.MTO "tcpreplay\-users\(atlists.sourceforge.net" "" ""
.SH "NOTES"
.sp
This manual page was generated from the tcpcapinfo option definitions.