'\" t
.\"     Title: tcpliveplay
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2026-07-19
.\"    Manual: Tcpreplay Suite
.\"    Source: Tcpreplay Suite
.\"  Language: English
.\"
.TH "TCPLIVEPLAY" "1" "2026-07-19" "Tcpreplay Suite" "Tcpreplay Suite"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
tcpliveplay \- Replays network traffic stored in a pcap file on live networks using new TCP connections
.SH "SYNOPSIS"
.sp
\fBtcpliveplay\fP [\fIOPTION\fP]... <eth0/eth1> <file.pcap> <Destination IP [1.2.3.4]> <Destination mac [0a:1b:2c:3d:4e:5f]> <\*(Aqrandom\*(Aq dst port OR specify dport #>
.SH "DESCRIPTION"
.sp
This program, \*(Aqtcpliveplay\*(Aq replays a captured set of packets using new TCP connections with the captured TCP payloads against a remote host in order to do comprehensive vulnerability testing.
.sp
The basic operation of tcpliveplay is it rewrites the given pcap file in a scheduled event format and responds with the appropriate packet if the remote host meets tcp protocal\(cqs SEQ/ACK expectation. Once expectations are met, then the local packets are sent with the same payload except with new tcp SEQ & ACK numbers meeting the response from the remote hose.
.sp
+
The input pcap file are rewritten to start at the first encounter of the SYN packet for correct operation making this packet be the first action in the event schedule of local host doing the replay.
.sp
+
For more details, please see the Tcpreplay Manual at: \c
.URL "http://tcpreplay.appneta.com" "" ""
.SH "OPTIONS"
.sp
\fB\-d\fP, \fB\-\-dbug\fP=\fInumber\fP
.RS 4
Enable debugging output. Range: 0 to 5. Default: \f(CR0\fP.
.sp
If configured with \-\-enable\-debug, then you can specify a verbosity level for debugging output.  Higher numbers increase verbosity.
.RE
.sp
\fB\-V\fP, \fB\-\-version\fP
.RS 4
Print version information.
.RE
.sp
\fB\-h\fP, \fB\-\-less\-help\fP
.RS 4
Display less usage information and exit.
.RE
.sp
\fB\-H\fP, \fB\-\-help\fP
.RS 4
Display usage information and exit.
.RE
.sp
\fB\-\-more\-help\fP
.RS 4
Pass the extended usage information through a pager.
.RE
.sp
\fB\-\-save\-opts\fP[=\fIstring\fP]
.RS 4
Save the current option state to a config file.
.RE
.sp
\fB\-\-load\-opts\fP=\fIstring\fP, \fB\-\-no\-load\-opts\fP
.RS 4
Load options from a config file; \fB\-\-no\-load\-opts\fP disables this.
.RE
.SH "OPTION PRESETS"
.sp
Any option that is not marked as \fInot presettable\fP may be preset by loading values from configuration ("RC" or ".INI") file(s).
The homerc file is \fI$$/\fP, unless that is a directory; in that case \fI.tcpliveplayrc\fP is searched for within it.
.SH "FILES"
.sp
See \fBOPTION PRESETS\fP for configuration files.
.SH "EXIT STATUS"
.sp
One of the following exit values will be returned:
.sp
\fB0\fP (EXIT_SUCCESS)
.RS 4
Successful program execution.
.RE
.sp
\fB1\fP (EXIT_FAILURE)
.RS 4
The operation failed or the command syntax was not valid.
.RE
.sp
\fB66\fP (EX_NOINPUT)
.RS 4
A specified configuration file could not be loaded.
.RE
.sp
\fB70\fP (EX_SOFTWARE)
.RS 4
libopts had an internal operational error. Please report it to \c
.MTO "autogen\-users\(atlists.sourceforge.net" "" "."
Thank you.
.RE
.SH "AUTHORS"
.sp
Copyright 2012 Yazan Siam
.sp
For support please use the \c
.MTO "tcpreplay\-users\(atlists.sourceforge.net" "" ""
mailing list.
.sp
The latest version of this software is always available from: \c
.URL "http://tcpreplay.appneta.com" "" ""
.SH "COPYRIGHT"
.sp
This program is released under the Modified (3 clause) Berkeley Software Distribution License.
.SH "BUGS"
.sp
Please send bug reports through the project\(cqs issue tracker.
.SH "NOTES"
.sp
This manual page was generated from the tcpliveplay option definitions.