'\" t
.\"     Title: tcpprep
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2026-07-19
.\"    Manual: Tcpreplay Suite
.\"    Source: Tcpreplay Suite
.\"  Language: English
.\"
.TH "TCPPREP" "1" "2026-07-19" "Tcpreplay Suite" "Tcpreplay Suite"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
tcpprep \- Create a tcpreplay cache cache file from a pcap file.
.SH "SYNOPSIS"
.sp
\fBtcpprep\fP [\fIOPTION\fP]...
.SH "DESCRIPTION"
.sp
tcpprep is a \fIpcap(3)\fP file pre\-processor which creates a cache file which provides "rules" for \fItcprewrite(1)\fP and \fItcpreplay(1)\fP on how to process and send packets.
.sp
The basic operation of tcpreplay is to resend all packets from the input file(s) out a single file.  Tcpprep processes a pcap file and applies a set of user\-specified rules to create a cache file which tells tcpreplay whether or not to send each packet and which interface the packet should be sent out of.
.sp
+
For more details, please see the Tcpreplay Manual at: \c
.URL "http://tcpreplay.appneta.com" "" ""
.SH "OPTIONS"
.sp
\fB\-d\fP, \fB\-\-dbug\fP=\fInumber\fP
.RS 4
Enable debugging output. Range: 0 to 5. Default: \f(CR0\fP.
.sp
If configured with \-\-enable\-debug, then you can specify a verbosity level for debugging output.  Higher numbers increase verbosity.
.RE
.sp
\fB\-a\fP, \fB\-\-auto\fP=\fIstring\fP
.RS 4
Auto\-split mode. Cannot be combined with: \fB\-\-cidr\fP, \fB\-\-port\fP, \fB\-\-regex\fP, \fB\-\-mac\fP.
.sp
Tcpprep will try to automatically determine the primary function of hosts based on the traffic captured and classify each host as client or server. In order to do so, you must provide a hint to tcpprep as to how to search for clients and servers.  Valid hints are:
.sp
\fBbridge\fP
.RS 4
Bridge mode processes each packet to try to determine if the sender is a client or server.  Once all the packets are processed, the results are weighed according to the server/client ratio (\f(CR\-\-ratio\fP) and systems are assigned an interface.  If tcpprep is unable to determine what role a system plays, tcpprep will abort.
.RE
.sp
\fBrouter\fP
.RS 4
Router mode works just like bridge mode, except that after weighing is done, systems which are undetermined are considered a server if they fall inside a network known to contain other servers.  Router has a greater chance of successfully splitting clients and servers but is not 100% foolproof.
.RE
.sp
\fBclient\fP
.RS 4
Client mode works just like bridge mode, except that unclassified systems are treated as clients.  Client mode should always complete successfully.
.RE
.sp
\fBserver\fP
.RS 4
Server mode works just like bridge mode, except that unclassified systems are treated as servers.  Server mode should always complete successfully.
.RE
.sp
\fBfirst\fP
.RS 4
First mode works by looking at the first time each IP is seen in the SRC and DST fields in the IP header.  If the host is first seen in the SRC field, it is a client and if it\(cqs first seen in the DST field, it is marked as a server.   This effectively replicates the processing of the tomahawk test tool.  First mode should always complete successfully.
.RE
.RE
.sp
\fB\-c\fP, \fB\-\-cidr\fP=\fIstring\fP
.RS 4
CIDR\-split mode. Cannot be combined with: \fB\-\-auto\fP, \fB\-\-port\fP, \fB\-\-regex\fP, \fB\-\-mac\fP.
.sp
Specify a comma delimited list of CIDR netblocks to match against the source IP of each packet.  Packets matching any of the CIDR\(cqs are classified as servers.
.sp
IPv4 Example:
.sp
.if n .RS 4
.nf
.fam C
\-\-cidr=192.168.0.0/16,172.16.0.0/12,10.0.0.0/8
.fam
.fi
.if n .RE
.sp
IPv6 Example:
.sp
.if n .RS 4
.nf
.fam C
\-\-cidr=[::ffff:0:0/96],[fe80::/16]
.fam
.fi
.if n .RE
.RE
.sp
\fB\-r\fP, \fB\-\-regex\fP=\fIstring\fP
.RS 4
Regex\-split mode. Cannot be combined with: \fB\-\-auto\fP, \fB\-\-port\fP, \fB\-\-cidr\fP, \fB\-\-mac\fP.
.sp
Specify a regular expression to match against the source IP of each packet.  Packets matching the regex are classified as servers.
.RE
.sp
\fB\-p\fP, \fB\-\-port\fP
.RS 4
Port\-split mode. Cannot be combined with: \fB\-\-auto\fP, \fB\-\-regex\fP, \fB\-\-cidr\fP, \fB\-\-mac\fP.
.sp
Specifies that TCP and UDP traffic over IPv4 and IPv6 should be classified as client or server based upon the destination port of the header.
.RE
.sp
\fB\-e\fP, \fB\-\-mac\fP=\fIstring\fP
.RS 4
Source MAC split mode. Cannot be combined with: \fB\-\-auto\fP, \fB\-\-regex\fP, \fB\-\-cidr\fP, \fB\-\-port\fP.
.sp
Specify a list of MAC addresses to match against the source MAC of each packet.  Packets matching one of the values are classified as servers.
.RE
.sp
\fB\-\-reverse\fP
.RS 4
Matches to be client instead of server.
.sp
Normally the \f(CR\-\-mac\fP, \f(CR\-\-regex\fP and \f(CR\-\-cidr\fP flags specify are used to specify the servers and non\-IP packets are classified as clients.  By using \f(CR\-\-reverse\fP, these features are reversed so that the flags specify clients and non\-IP packets are classified as servers.
.RE
.sp
\fB\-C\fP, \fB\-\-comment\fP=\fIstring\fP
.RS 4
Embedded cache file comment.
.sp
Specify a comment to be imbedded within the output cache file and later viewed.
.RE
.sp
\fB\-\-no\-arg\-comment\fP
.RS 4
Do not embed any cache file comment.
.sp
By default, tcpprep includes the arguments passed on the command line in the cache file comment (in addition to any user specified \-\-comment). If for some reason you do not wish to include this, specify this option.
.RE
.sp
\fB\-x\fP, \fB\-\-include\fP=\fIstring\fP
.RS 4
Include only packets matching rule. Cannot be combined with: \fB\-\-exclude\fP.
.sp
Override default of processing all packets stored in the capture file and only send/edit packets which match the provided rule.  Rules can be one of:
.sp
\fBS:<CIDR1>,...\fP
.RS 4
Source IP must match specified IPv4/v6 CIDR(s)
.RE
.sp
\fBD:<CIDR1>,...\fP
.RS 4
Destination IP must match specified IPv4/v6 CIDR(s)
.RE
.sp
\fBB:<CIDR1>,...\fP
.RS 4
Both source and destination IP must match specified IPv4/v6 CIDR(s)
.RE
.sp
\fBE:<CIDR1>,...\fP
.RS 4
Either IP must match specified IPv4/v6 CIDR(s)
.RE
.sp
\fBP:<LIST>\fP
.RS 4
Must be one of the listed packets where the list corresponds to the packet number in the capture file.
.sp
.if n .RS 4
.nf
.fam C
\-x P:1\-5,9,15,72\-
.fam
.fi
.if n .RE
.sp
would process packets 1 through 5, the 9th and 15th packet, and packets 72 until the end of the file
.RE
.sp
\fBF:\*(Aq<bpf>\*(Aq\fP
.RS 4
BPF filter.  See the \fItcpdump(8)\fP man page for syntax.
.RE
.RE
.sp
\fB\-X\fP, \fB\-\-exclude\fP=\fIstring\fP
.RS 4
Exclude any packet matching this rule. Cannot be combined with: \fB\-\-include\fP.
.sp
Override default of processing all packets stored in the capture file and only send/edit packets which do NOT match the provided rule.  Rules can be one of:
.sp
\fBS:<CIDR1>,...\fP
.RS 4
Source IP must not match specified IPv4/v6 CIDR(s)
.RE
.sp
\fBD:<CIDR1>,...\fP
.RS 4
Destination IP must not match specified IPv4/v6 CIDR(s)
.RE
.sp
\fBB:<CIDR1>,...\fP
.RS 4
Both source and destination IP must not match specified IPv4/v6 CIDR(s)
.RE
.sp
\fBE:<CIDR1>,...\fP
.RS 4
Either IP must not match specified IPv4/v6 CIDR(s)
.RE
.sp
\fBP:<LIST>\fP
.RS 4
Must not be one of the listed packets where the list corresponds to the packet number in the capture file.
.sp
.if n .RS 4
.nf
.fam C
\-x P:1\-5,9,15,72\-
.fam
.fi
.if n .RE
.sp
would skip packets 1 through 5, the 9th and 15th packet, and packets 72 until the end of the file
.RE
.RE
.sp
\fB\-o\fP, \fB\-\-cachefile\fP=\fIstring\fP
.RS 4
Output cache file.
.RE
.sp
\fB\-i\fP, \fB\-\-pcap\fP=\fIstring\fP
.RS 4
Input pcap file to process.
.RE
.sp
\fB\-P\fP, \fB\-\-print\-comment\fP=\fIstring\fP
.RS 4
Print embedded comment in the specified cache file.
.RE
.sp
\fB\-I\fP, \fB\-\-print\-info\fP=\fIstring\fP
.RS 4
Print basic info from the specified cache file.
.RE
.sp
\fB\-S\fP, \fB\-\-print\-stats\fP=\fIstring\fP
.RS 4
Print statistical information about the specified cache file.
.RE
.sp
\fB\-s\fP, \fB\-\-services\fP=\fIstring\fP
.RS 4
Load services file for server ports. Requires: \fB\-\-port\fP.
.sp
Uses a list of ports used by servers in the same format as of /etc/services: <service_name>        <port>/<protocol> # comment
.sp
Example: http            80/tcp
.RE
.sp
\fB\-N\fP, \fB\-\-nonip\fP
.RS 4
Send non\-IP traffic out server interface.
.sp
By default, non\-IP traffic which can not be classified as client or server is classified as "client".  Specifying \f(CR\-\-nonip\fP will reclassify non\-IP traffic as "server".  Note that the meaning of this flag is reversed if \f(CR\-\-reverse\fP is used.
.RE
.sp
\fB\-R\fP, \fB\-\-ratio\fP=\fIstring\fP
.RS 4
Ratio of client to server packets. Default: \f(CR2.0\fP. Requires: \fB\-\-auto\fP.
.sp
Since a given host may have both client and server traffic being sent to/from it, tcpprep uses a ratio to weigh these packets.  If you would like to override the default of 2:1 server to client packets required for a host to be classified as a server, specify it as a floating point value.
.RE
.sp
\fB\-m\fP, \fB\-\-minmask\fP=\fInumber\fP
.RS 4
Minimum network mask length in auto mode. Range: 0 to 32. Default: \f(CR30\fP. Requires: \fB\-\-auto\fP.
.sp
By default, auto modes use a minimum network mask length of 30 bits to build networks containing clients and servers.  This allows you to override this value.  Larger values will increase performance but may provide inaccurate results.
.RE
.sp
\fB\-M\fP, \fB\-\-maxmask\fP=\fInumber\fP
.RS 4
Maximum network mask length in auto mode. Range: 0 to 32. Default: \f(CR8\fP. Requires: \fB\-\-auto\fP.
.sp
By default, auto modes use a maximum network mask length of 8 bits to build networks containing clients and servers.  This allows you to override this value.  Larger values will decrease performance and accuracy but will provide greater chance of success.
.RE
.sp
\fB\-v\fP, \fB\-\-verbose\fP
.RS 4
Print decoded packets via tcpdump to STDOUT.
.RE
.sp
\fB\-A\fP, \fB\-\-decode\fP=\fIstring\fP
.RS 4
Arguments passed to tcpdump decoder. Requires: \fB\-\-verbose\fP.
.sp
When enabling verbose mode (\f(CR\-v\fP) you may also specify one or more additional arguments to pass to \f(CRtcpdump\fP to modify the way packets are decoded.  By default, \-n and \-l are used. Be sure to quote the arguments so that they are not interpreted by tcprewrite.  The following arguments are valid:
.sp
.if n .RS 4
.nf
.fam C
    [ \-aAeNqRStuvxX ]
    [ \-E spi@ipaddr algo:secret,... ]
    [ \-s snaplen ]
.fam
.fi
.if n .RE
.RE
.sp
\fB\-V\fP, \fB\-\-version\fP
.RS 4
Print version information.
.RE
.sp
\fB\-h\fP, \fB\-\-less\-help\fP
.RS 4
Display less usage information and exit.
.RE
.sp
\fB\-w\fP, \fB\-\-suppress\-warnings\fP
.RS 4
suppress printing warning messages.
.RE
.sp
\fB\-H\fP, \fB\-\-help\fP
.RS 4
Display usage information and exit.
.RE
.sp
\fB\-\-more\-help\fP
.RS 4
Pass the extended usage information through a pager.
.RE
.sp
\fB\-\-save\-opts\fP[=\fIstring\fP]
.RS 4
Save the current option state to a config file.
.RE
.sp
\fB\-\-load\-opts\fP=\fIstring\fP, \fB\-\-no\-load\-opts\fP
.RS 4
Load options from a config file; \fB\-\-no\-load\-opts\fP disables this.
.RE
.SH "OPTION PRESETS"
.sp
Any option that is not marked as \fInot presettable\fP may be preset by loading values from configuration ("RC" or ".INI") file(s).
The homerc file is \fI$$/\fP, unless that is a directory; in that case \fI.tcppreprc\fP is searched for within it.
.SH "FILES"
.sp
See \fBOPTION PRESETS\fP for configuration files.
.SH "EXIT STATUS"
.sp
One of the following exit values will be returned:
.sp
\fB0\fP (EXIT_SUCCESS)
.RS 4
Successful program execution.
.RE
.sp
\fB1\fP (EXIT_FAILURE)
.RS 4
The operation failed or the command syntax was not valid.
.RE
.sp
\fB66\fP (EX_NOINPUT)
.RS 4
A specified configuration file could not be loaded.
.RE
.sp
\fB70\fP (EX_SOFTWARE)
.RS 4
libopts had an internal operational error. Please report it to \c
.MTO "autogen\-users\(atlists.sourceforge.net" "" "."
Thank you.
.RE
.SH "AUTHORS"
.sp
Copyright 2013\-2026 Fred Klassen \- AppNeta
.sp
Copyright 2000\-2012 Aaron Turner
.sp
For support please use the \c
.MTO "tcpreplay\-users\(atlists.sourceforge.net" "" ""
mailing list.
.sp
The latest version of this software is always available from: \c
.URL "http://tcpreplay.appneta.com/" "" ""
.SH "COPYRIGHT"
.sp
Copyright \(co 2000\-2026 Aaron Turner and Fred Klassen, all rights reserved.
This program is released under the terms of the GNU General Public License, version 3 or later.
.SH "BUGS"
.sp
Please send bug reports to: \c
.MTO "tcpreplay\-users\(atlists.sourceforge.net" "" ""
.SH "NOTES"
.sp
This manual page was generated from the tcpprep option definitions.