'\" t
.\"     Title: tcpreplay
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2026-07-19
.\"    Manual: Tcpreplay Suite
.\"    Source: Tcpreplay Suite
.\"  Language: English
.\"
.TH "TCPREPLAY" "1" "2026-07-19" "Tcpreplay Suite" "Tcpreplay Suite"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
tcpreplay \- Replay network traffic stored in pcap files
.SH "SYNOPSIS"
.sp
\fBtcpreplay\fP [\fIOPTION\fP]... <pcap_file(s)> | <pcap_dir(s)>
.SH "DESCRIPTION"
.sp
tcpreplay is a tool for replaying network traffic from files saved with tcpdump or other tools which write pcap(3) files.
.sp
The basic operation of tcpreplay is to resend  all  packets  from  the input file(s) at the speed at which they were recorded, or a specified data rate, up to as fast as the hardware is capable.
.sp
+
Optionally, the traffic can be split between two interfaces, written to files, filtered and edited in various ways, providing the means to test firewalls, NIDS and other network devices.
.sp
+
On Linux, raw IP (layer 3 only) interfaces such as WireGuard and tun are supported automatically: any layer 2 header in the input file (Ethernet including VLAN tags, Linux SLL, loopback, ...) is stripped and packets are sent as bare IPv4/IPv6. Non\-IP packets such as ARP cannot be sent on these interfaces and are reported as failed.
.sp
+
For more details, please see the Tcpreplay Manual at: \c
.URL "http://tcpreplay.appneta.com" "" ""
.SH "OPTIONS"
.sp
\fB\-r\fP, \fB\-\-portmap\fP=\fIstring\fP
.RS 4
Rewrite TCP/UDP ports. May appear up to 9999 times.
.sp
Specify a list of comma delimited port mappings consisting of colon delimited port number pairs.  Each colon delimited port pair consists of the port to match followed by the port number to rewrite.
.sp
Examples:
.sp
.if n .RS 4
.nf
.fam C
\-\-portmap=80:8000 \-\-portmap=8080:80\&    # 80\->8000 and 8080\->80
\-\-portmap=8000,8080,88888:80\&           # 3 different ports become 80
\-\-portmap=8000\-8999:80\&                 # ports 8000 to 8999 become 80
.fam
.fi
.if n .RE
.RE
.sp
\fB\-s\fP, \fB\-\-seed\fP=\fInumber\fP
.RS 4
Randomize src/dst IPv4/v6 addresses w/ given seed. Cannot be combined with: \fB\-\-fuzz\-seed\fP.
.sp
Causes the source and destination IPv4/v6 addresses to be pseudo randomized but still maintain client/server relationships. Since the randomization is deterministic based on the seed, you can reuse the same seed value to recreate the traffic.
.RE
.sp
\fB\-N\fP, \fB\-\-pnat\fP=\fIstring\fP
.RS 4
Rewrite IPv4/v6 addresses using pseudo\-NAT. May appear up to 2 times. Cannot be combined with: \fB\-\-srcipmap\fP.
.sp
Takes a comma delimited series of colon delimited CIDR netblock pairs.  Each netblock pair is evaluated in order against the IP addresses.  If the IP address in the packet matches the first netblock, it is rewritten using the second netblock as a mask against the high order bits.
.sp
IPv4 Example:
.sp
.if n .RS 4
.nf
.fam C
\-\-pnat=192.168.0.0/16:10.77.0.0/16,172.16.0.0/12:10.1.0.0/24
.fam
.fi
.if n .RE
.sp
IPv6 Example:
.sp
.if n .RS 4
.nf
.fam C
\-\-pnat=[2001:db8::/32]:[dead::/16],[2001:db8::/32]:[::ffff:0:0/96]
.fam
.fi
.if n .RE
.RE
.sp
\fB\-S\fP, \fB\-\-srcipmap\fP=\fIstring\fP
.RS 4
Rewrite source IPv4/v6 addresses using pseudo\-NAT. Cannot be combined with: \fB\-\-pnat\fP.
.sp
Works just like the \-\-pnat option, but only affects the source IP addresses in the IPv4/v6 header.
.RE
.sp
\fB\-D\fP, \fB\-\-dstipmap\fP=\fIstring\fP
.RS 4
Rewrite destination IPv4/v6 addresses using pseudo\-NAT. Cannot be combined with: \fB\-\-pnat\fP.
.sp
Works just like the \-\-pnat option, but only affects the destination IP addresses in the IPv4/v6 header.
.RE
.sp
\fB\-e\fP, \fB\-\-endpoints\fP=\fIstring\fP
.RS 4
Rewrite IP addresses to be between two endpoints. Requires: \fB\-\-cachefile\fP.
.sp
Takes a pair of colon delimited IPv4/v6 addresses which will be used to rewrite all traffic to appear to be between the two IP addresses.
.sp
IPv4 Example:
.sp
.if n .RS 4
.nf
.fam C
\-\-endpoints=172.16.0.1:172.16.0.2
.fam
.fi
.if n .RE
.sp
IPv6 Example:
.sp
.if n .RS 4
.nf
.fam C
\-\-endpoints=[2001:db8::dead:beef]:[::ffff:0:0:ac:f:0:2]
.fam
.fi
.if n .RE
.RE
.sp
\fB\-\-tcp\-sequence\fP=\fInumber\fP
.RS 4
Change TCP Sequence (and ACK) numbers /w given seed. Range: 1 to any. Default: \f(CR0\fP.
.sp
Change all TCP sequence numbers, and related sequence\-acknowledgement numbers. They will be shifted by a random amount based on the provided seed.
.RE
.sp
\fB\-b\fP, \fB\-\-skipbroadcast\fP
.RS 4
Skip rewriting broadcast/multicast IPv4/v6 addresses.
.sp
By default \-\-seed, \-\-pnat and \-\-endpoints will rewrite broadcast and multicast IPv4/v6 and MAC addresses.	Setting this flag will keep broadcast/multicast IPv4/v6 and MAC addresses from being rewritten.
.RE
.sp
\fB\-C\fP, \fB\-\-fixcsum\fP
.RS 4
Force recalculation of IPv4/TCP/UDP header checksums.
.sp
Causes each IPv4/v6 packet to have their checksums recalculated and fixed.  Automatically enabled for packets modified with \f(CR\-\-seed\fP, \f(CR\-\-pnat\fP, \f(CR\-\-endpoints\fP or \f(CR\-\-fixlen\fP.
.RE
.sp
\fB\-\-fixhdrlen\fP
.RS 4
Alter IP/TCP header len to match packet length.
.sp
By default, tcpreplay will send packets with the original packet length, However, you may want the packet length revised to minimum packet size. Using this option, tcpreplay will rewrite (fix) the packet length, and recalculate checksums when packet length changes. Caution: undesired packet changes may occur when this option is specified.
.RE
.sp
\fB\-m\fP, \fB\-\-mtu\fP=\fInumber\fP
.RS 4
Override default MTU length (1500 bytes). Range: 1 to MAX_SNAPLEN.
.sp
Override the default 1500 byte MTU size for determining the maximum padding length (\-\-fixlen=pad) or when truncating (\-\-mtu\-trunc).
.RE
.sp
\fB\-\-mtu\-trunc\fP
.RS 4
Truncate packets larger then specified MTU.
.sp
Similar to \-\-fixlen, this option will truncate data in packets from Layer 3 and above to be no larger then the MTU.
.RE
.sp
\fB\-E\fP, \fB\-\-efcs\fP
.RS 4
Remove Ethernet checksums (FCS) from end of frames.
.sp
Note, this option is pretty dangerous!  We do not actually check to see if a FCS actually exists in the frame, we just blindly delete the last 4 bytes.  Hence, you should only use this if you know know that your OS provides the FCS when reading raw packets.
.RE
.sp
\fB\-\-ttl\fP=\fIstring\fP
.RS 4
Modify the IPv4/v6 TTL/Hop Limit.
.sp
Allows you to modify the TTL/Hop Limit of all the IPv4/v6 packets.  Specify a number to hard\-code the value or +/\-value to increase or decrease by the value provided (limited to 1\-255).
.sp
Examples:
.sp
.if n .RS 4
.nf
.fam C
\-\-ttl=10
\-\-ttl=+7
\-\-ttl=\-64
.fam
.fi
.if n .RE
.RE
.sp
\fB\-\-tos\fP=\fInumber\fP
.RS 4
Set the IPv4 TOS/DiffServ/ECN byte. Range: 0 to 255.
.sp
Allows you to override the TOS (also known as DiffServ/ECN) value in IPv4.
.RE
.sp
\fB\-\-tclass\fP=\fInumber\fP
.RS 4
Set the IPv6 Traffic Class byte. Range: 0 to 255.
.sp
Allows you to override the IPv6 Traffic Class field.
.RE
.sp
\fB\-\-flowlabel\fP=\fInumber\fP
.RS 4
Set the IPv6 Flow Label. Range: 0 to 1048575.
.sp
Allows you to override the 20bit IPv6 Flow Label field.  Has no effect on IPv4 packets.
.RE
.sp
\fB\-F\fP, \fB\-\-fixlen\fP=\fIstring\fP
.RS 4
Pad or truncate packet data to match header length.
.sp
Packets may be truncated during capture if the snaplen is smaller then the packet.  This option allows you to modify the packet to pad the packet back out to the size stored in the IPv4/v6 header or rewrite the IP header total length to reflect the stored packet length. @table @bullet @item \fIpad\fP Truncated packets will be padded out so that the packet length matches the IPv4 total length @item \fItrunc\fP Truncated packets will have their IPv4 total length field rewritten to match the actual packet length @item \fIdel\fP Delete the packet
.RE
.sp
\fB\-\-fuzz\-seed\fP=\fInumber\fP
.RS 4
Fuzz 1 in X packets. Edit bytes, length, or emulate packet drop. Range: 0 to any. Default: \f(CR0\fP.
.sp
This fuzzing was designed as to test layer 7 protocols such as voip protocols. It modifies randomly 1 out of X packets (where X = \fI\-\-fuzz\-factor\fP) in order for stateful protocols to cover more of their code.  The random fuzzing actions focus on data start and end because it often is the part of the data application protocols base their decisions on.
.sp
Possible fuzzing actions list: * drop packet * reduce packet size * edit packet Bytes:
.sp
.if n .RS 4
.nf
.fam C
   * Not all Bytes have the same probability of appearance in real life.
     Replace with 0x00, 0xFF, or a random byte with equal likelihood.
   * Not all Bytes have the same significance in a packet.
     Replace the start, the end, or the middle of the packet with equal likelihood.
.fam
.fi
.if n .RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
do nothing (7 out of 8 packets)
.RE
.RE
.sp
\fB\-\-fuzz\-factor\fP=\fInumber\fP
.RS 4
Set the Fuzz 1 in X packet ratio (default 1 in 8 packets). Range: 1 to any. Default: \f(CR8\fP. Requires: \fB\-\-fuzz\-seed\fP.
.sp
Sets the ratio of for \fI\-\-fuzz\-seed\fP option. By default this value is 8, which means 1 in 8 packets are modified by fuzzing. Note that this ratio is based on the random number generated by the supplied fuzz seed. Therefore by default you cannot expect that exactly every eighth packet will be modified.
.RE
.sp
\fB\-\-skipl2broadcast\fP
.RS 4
Skip rewriting broadcast/multicast Layer 2 addresses.
.sp
By default, editing Layer 2 addresses will rewrite broadcast and multicast MAC addresses.	Setting this flag will keep broadcast/multicast MAC addresses from being rewritten.
.RE
.sp
\fB\-\-dlt\fP=\fIstring\fP
.RS 4
Override output DLT encapsulation.
.sp
By default, no DLT (data link type) conversion will be made. To change the DLT type of the output pcap, select one of the following values:
.sp
\fBenet\fP
.RS 4
Ethernet aka DLT_EN10MB
.RE
.sp
\fBhdlc\fP
.RS 4
Cisco HDLC aka DLT_C_HDLC
.RE
.sp
\fBjnpr_eth\fP
.RS 4
Juniper Ethernet DLT_C_JNPR_ETHER
.RE
.sp
\fBpppserial\fP
.RS 4
PPP Serial aka DLT_PPP_SERIAL
.RE
.sp
\fBuser\fP
.RS 4
User specified Layer 2 header and DLT type
.RE
.RE
.sp
\fB\-\-enet\-dmac\fP=\fIstring\fP
.RS 4
Override destination ethernet MAC addresses.
.sp
Takes a pair of comma deliminated ethernet MAC addresses which will replace the destination MAC address of outbound packets. The first MAC address will be used for the server to client traffic and the optional second MAC address will be used for the client to server traffic.
.sp
Example:
.sp
.if n .RS 4
.nf
.fam C
\-\-enet\-dmac=00:12:13:14:15:16,00:22:33:44:55:66
.fam
.fi
.if n .RE
.RE
.sp
\fB\-\-enet\-smac\fP=\fIstring\fP
.RS 4
Override source ethernet MAC addresses.
.sp
Takes a pair of comma deliminated ethernet MAC addresses which will replace the source MAC address of outbound packets. The first MAC address will be used for the server to client traffic and the optional second MAC address will be used for the client to server traffic.
.sp
Example:
.sp
.if n .RS 4
.nf
.fam C
\-\-enet\-smac=00:12:13:14:15:16,00:22:33:44:55:66
.fam
.fi
.if n .RE
.RE
.sp
\fB\-\-enet\-subsmac\fP=\fIstring\fP
.RS 4
Substitute MAC addresses. May appear up to 9999 times.
.sp
Allows you to rewrite ethernet MAC addresses of packets. It takes comma delimited pair or MACs address and rewrites all occurrences of the first MAC with the value of the second MAC. Example:
.sp
.if n .RS 4
.nf
.fam C
\-\-enet\-subsmac=00:12:13:14:15:16,00:22:33:44:55:66
.fam
.fi
.if n .RE
.RE
.sp
\fB\-\-enet\-mac\-seed\fP=\fInumber\fP
.RS 4
Randomize MAC addresses. Cannot be combined with: \fB\-\-enet\-smac\fP, \fB\-\-enet\-dmac\fP, \fB\-\-enet\-subsmac\fP.
.sp
Allows you to randomize ethernet MAC addresses of packets, mostly like what \fI\-\-seed\fP option does for IPv4/IPv6 addresses.
.RE
.sp
\fB\-\-enet\-mac\-seed\-keep\-bytes\fP=\fInumber\fP
.RS 4
Randomize MAC addresses. Range: 1 to 6. Requires: \fB\-\-enet\-mac\-seed\fP.
.sp
Keep some bytes untouched when usinging \fI\-\-enet\-mac\-seed\fP option.
.RE
.sp
\fB\-\-enet\-vlan\fP=\fIstring\fP
.RS 4
Specify ethernet 802.1q VLAN tag mode.
.sp
Allows you to rewrite ethernet frames to add a 802.1q header to standard 802.3 ethernet headers or remove the 802.1q VLAN tag information. @table @bullet @item \fIadd\fP Adds an 802.1q VLAN header to the existing 802.3 ethernet header. If a VLAN header already exists, a new VLAN header is added outside of the existing header.
.sp
Note that you will be allowed to run this option multiple times to create more than 2 VLAN headers, however those packets will be valid. At most you should have 2 X 802.1q VLAN tags, or outer an 802.1ad and an inner 802.1q VLAN tag. @item \fIdel\fP Rewrites the existing 802.1q VLAN header as an 802.3 ethernet header
.RE
.sp
\fB\-\-enet\-vlan\-tag\fP=\fInumber\fP
.RS 4
Specify the new ethernet 802.1q VLAN tag value. Range: 0 to 4095. Requires: \fB\-\-enet\-vlan\fP.
.sp
Mandatory when \fI\-\-enet\-vlan=add\fP is used on packets that are not already VLAN tagged.
.RE
.sp
\fB\-\-enet\-vlan\-cfi\fP=\fInumber\fP
.RS 4
Specify the ethernet 802.1q VLAN CFI value. Range: 0 to 1. Requires: \fB\-\-enet\-vlan\fP.
.sp
When omitted, the CFI bit of an existing VLAN header is preserved; a newly added tag on a previously untagged packet defaults to 0 (a one\-time notice is printed).
.RE
.sp
\fB\-\-enet\-vlan\-pri\fP=\fInumber\fP
.RS 4
Specify the ethernet 802.1q VLAN priority. Range: 0 to 7. Requires: \fB\-\-enet\-vlan\fP.
.sp
When omitted, the priority of an existing VLAN header is preserved; a newly added tag on a previously untagged packet defaults to 0 (a one\-time notice is printed).
.RE
.sp
\fB\-\-enet\-vlan\-proto\fP=\fIstring\fP
.RS 4
Specify VLAN tag protocol 802.1q or 802.1ad.
.sp
Allows you to specify the protocol of the added VLAN tags. @table @bullet @item \fI802.1q\fP Specifies that 802.1q VLAN headers are to be added. This is the default. @item \fI802.1ad\fP Specifies that 802.1ad Q\-in\-Q VLAN headers are to be added. To make valid packets, input packets must already have 802.1q VLAN headers.
.RE
.sp
\fB\-\-hdlc\-control\fP=\fInumber\fP
.RS 4
Specify HDLC control value.
.sp
The Cisco HDLC header has a 1 byte "control" field.  Apparently this should always be 0, but if you can use any 1 byte value.
.RE
.sp
\fB\-\-hdlc\-address\fP=\fInumber\fP
.RS 4
Specify HDLC address.
.sp
The Cisco HDLC header has a 1 byte "address" field which has two valid values:
.sp
\fB0x0F\fP
.RS 4
Unicast
.RE
.sp
\fB0xBF\fP
.RS 4
Broadcast
.RE
.RE
.sp
You can however specify any single byte value.
.sp
\fB\-\-user\-dlt\fP=\fInumber\fP
.RS 4
Set output file DLT type.
.sp
Set the DLT value of the output pcap file.
.RE
.sp
\fB\-\-user\-dlink\fP=\fIstring\fP
.RS 4
Rewrite Data\-Link layer with user specified data. May appear up to 2 times.
.sp
Provide a series of comma deliminated hex values which will be used to rewrite or create the Layer 2 header of the packets. The first instance of this argument will rewrite both server and client traffic, but if this argument is specified a second time, it will be used for the client traffic.
.sp
Example:
.sp
.if n .RS 4
.nf
.fam C
\-\-user\-dlink=01,02,03,04,05,06,00,1A,2B,3C,4D,5E,6F,08,00
.fam
.fi
.if n .RE
.RE
.sp
\fB\-d\fP, \fB\-\-dbug\fP=\fInumber\fP
.RS 4
Enable debugging output. Range: 0 to 5. Default: \f(CR0\fP.
.sp
If configured with \-\-enable\-debug, then you can specify a verbosity level for debugging output.  Higher numbers increase verbosity.
.RE
.sp
\fB\-q\fP, \fB\-\-quiet\fP
.RS 4
Quiet mode.
.sp
Print nothing except the statistics at the end of the run
.RE
.sp
\fB\-T\fP, \fB\-\-timer\fP=\fIstring\fP
.RS 4
Select packet timing mode: select, ioport, gtod, nano. Default: \f(CRgtod\fP.
.sp
Allows you to select the packet timing method to use:
.sp
\fBnano\fP
.RS 4
Use nanosleep() API
.RE
.sp
\fBselect\fP
.RS 4
Use select() API
.RE
.sp
\fBioport\fP
.RS 4
Write to the i386 IO Port 0x80
.RE
.sp
\fBgtod [default]\fP
.RS 4
Use a gettimeofday() loop
.RE
.RE
.sp
\fB\-\-maxsleep\fP=\fInumber\fP
.RS 4
Sleep for no more then X milliseconds between packets. Default: \f(CR0\fP.
.sp
Set a limit for the maximum number of milliseconds that tcpreplay will sleep between packets.  Effectively prevents long delays between packets without effecting the majority of packets.  Default is disabled.
.RE
.sp
\fB\-v\fP, \fB\-\-verbose\fP
.RS 4
Print decoded packets via tcpdump to STDOUT.
.RE
.sp
\fB\-A\fP, \fB\-\-decode\fP=\fIstring\fP
.RS 4
Arguments passed to tcpdump decoder. Requires: \fB\-\-verbose\fP.
.sp
When enabling verbose mode (\fI\-v\fP) you may also specify one or more additional  arguments to pass to \f(CRtcpdump\fP to modify the way packets are decoded.  By default, \-n and \-l are used.   Be  sure  to quote the arguments like: \-A "\-axxx" so that they are not interpreted by tcpreplay.   Please see the tcpdump(1) man page for a complete list of options.
.RE
.sp
\fB\-K\fP, \fB\-\-preload_pcap\fP
.RS 4
Preloads packets into RAM before sending.
.sp
This option loads the specified pcap(s) into RAM before starting to send in order to improve replay performance while introducing a startup performance hit. Preloading can be used with or without \fI\-\-loop\fP. This option also suppresses flow statistics collection for every iteration, which can significantly reduce memory usage. Flow statistics are predicted based on options supplied and statistics collected from the first loop iteration.
.RE
.sp
\fB\-c\fP, \fB\-\-cachefile\fP=\fIstring\fP
.RS 4
Split traffic via a tcpprep cache file. Requires: \fB\-\-intf2\fP. Cannot be combined with: \fB\-\-dualfile\fP.
.sp
If you have a pcap file you would like to use to send bi\-directional traffic through a device (firewall, router, IDS, etc) then using tcpprep you can create a cachefile which tcpreplay will use to split the traffic across two network interfaces.
.RE
.sp
\fB\-2\fP, \fB\-\-dualfile\fP
.RS 4
Replay two files at a time from a network tap. Requires: \fB\-\-intf2\fP. Cannot be combined with: \fB\-\-cachefile\fP.
.sp
If you captured network traffic using a network tap, then you can end up with two pcap files\- one for each direction.  This option will replay these two files at the same time, one on each interface and inter\-mix them using the timestamps in each.
.RE
.sp
\fB\-i\fP, \fB\-\-intf1\fP=\fIstring\fP
.RS 4
Client to server/RX/primary traffic output interface. This option is required.
.sp
Required network interface used to send either all traffic or traffic which is marked as \*(Aqprimary\*(Aq via tcpprep.  Primary traffic is usually client\-to\-server or inbound (RX) on khial virtual interfaces.
.RE
.sp
\fB\-I\fP, \fB\-\-intf2\fP=\fIstring\fP
.RS 4
Server to client/TX/secondary traffic output interface.
.sp
Optional network interface used to send traffic which is marked as \*(Aqsecondary\*(Aq via tcpprep.  Secondary traffic is usually server\-to\-client or outbound (TX) on khial virtual interfaces.  Generally, it only makes sense to use this option with \-\-cachefile.
.RE
.sp
\fB\-w\fP, \fB\-\-write\fP=\fIstring\fP
.RS 4
Pcap file to receive traffic outputs. Cannot be combined with: \fB\-\-intf2\fP.
.sp
Optional pcap file name used to receive traffic.
.RE
.sp
\fB\-\-include\fP=\fIstring\fP
.RS 4
Send only selected packet numbers. Cannot be combined with: \fB\-\-exclude\fP.
.sp
Override default of processing all packets stored in the capture file and only send packets that are part of a supplied list of packet numbers.
.sp
.if n .RS 4
.nf
.fam C
\-x P:1\-5,9,15,72\-
.fam
.fi
.if n .RE
.sp
would skip packets 1 through 5, the 9th and 15th packet, and packets 72 until the end of the file
.RE
.sp
\fB\-\-exclude\fP=\fIstring\fP
.RS 4
Send all but selected packet numbers. Cannot be combined with: \fB\-\-include\fP.
.sp
Override default of processing all packets stored in the capture file and only send packets that are NOT part of a supplied list of packet numbers.
.sp
.if n .RS 4
.nf
.fam C
\-x P:1\-5,9,15,72\-
.fam
.fi
.if n .RE
.sp
would skip packets 1 through 5, the 9th and 15th packet, and packets 72 until the end of the file
.RE
.sp
\fB\-\-listnics\fP
.RS 4
List available network interfaces and exit.
.RE
.sp
\fB\-l\fP, \fB\-\-loop\fP=\fInumber\fP
.RS 4
Loop through the capture file X times. Range: 0 to any. Default: \f(CR1\fP.
.RE
.sp
\fB\-\-loopdelay\-ms\fP=\fInumber\fP
.RS 4
Delay between loops in milliseconds. Range: 0 to any. Default: \f(CR0\fP. Requires: \fB\-\-loop\fP. Cannot be combined with: \fB\-\-loopdelay\-ns\fP.
.RE
.sp
\fB\-\-loopdelay\-ns\fP=\fInumber\fP
.RS 4
Delay between loops in nanoseconds. Range: 0 to any. Default: \f(CR0\fP. Requires: \fB\-\-loop\fP. Cannot be combined with: \fB\-\-loopdelay\-ms\fP.
.sp
By default, tcpreplay will use loop delay with microsecond accuracy (loopdelay\-ms). In order to use loop delay with nanosecond accuracy you need to use nano packet timing mode.
.RE
.sp
\fB\-\-pktlen\fP
.RS 4
Override the snaplen and use the actual packet len.
.sp
By default, tcpreplay will send packets based on the size of the "snaplen" stored in the pcap file which is usually the correct thing to do.  However, occasionally, tools will store more bytes then told to.  By specifying this option, tcpreplay will ignore the snaplen field and instead try to send packets based on the original packet length.  Bad things may happen if you specify this option.
.RE
.sp
\fB\-L\fP, \fB\-\-limit\fP=\fInumber\fP
.RS 4
Limit the number of packets to send. Range: 1 to any. Default: \f(CR\-1\fP.
.sp
By default, tcpreplay will send all the packets.  Alternatively, you can specify a maximum number of packets to send.
.RE
.sp
\fB\-\-duration\fP=\fInumber\fP
.RS 4
Limit the number of seconds to send. Range: 1 to any. Default: \f(CR\-1\fP.
.sp
By default, tcpreplay will send all the packets.  Alternatively, you can specify a maximum number of seconds to transmit.
.RE
.sp
\fB\-x\fP, \fB\-\-multiplier\fP=\fIstring\fP
.RS 4
Modify replay speed to a given multiple. Cannot be combined with: \fB\-\-pps\fP, \fB\-\-mbps\fP, \fB\-\-oneatatime\fP, \fB\-\-topspeed\fP.
.sp
Specify a value to modify the packet replay speed. Examples:
.sp
.if n .RS 4
.nf
.fam C
    2.0 will replay traffic at twice the speed captured
    0.7 will replay traffic at 70% the speed captured
.fam
.fi
.if n .RE
.RE
.sp
\fB\-p\fP, \fB\-\-pps\fP=\fIstring\fP
.RS 4
Replay packets at a given packets/sec. Cannot be combined with: \fB\-\-multiplier\fP, \fB\-\-mbps\fP, \fB\-\-oneatatime\fP, \fB\-\-topspeed\fP.
.sp
Specify a value to regulate the packet replay to a specific packet\-per\-second rate. Examples:
.sp
.if n .RS 4
.nf
.fam C
    200 will replay traffic at 200 packets per second
    0.25 will replay traffic at 15 packets per minute
.fam
.fi
.if n .RE
.RE
.sp
\fB\-M\fP, \fB\-\-mbps\fP=\fIstring\fP
.RS 4
Replay packets at a given Mbps. Cannot be combined with: \fB\-\-multiplier\fP, \fB\-\-pps\fP, \fB\-\-oneatatime\fP, \fB\-\-topspeed\fP.
.sp
Specify a floating point value for the Mbps rate that tcpreplay should send packets at.
.RE
.sp
\fB\-t\fP, \fB\-\-topspeed\fP
.RS 4
Replay packets as fast as possible. Cannot be combined with: \fB\-\-mbps\fP, \fB\-\-multiplier\fP, \fB\-\-pps\fP, \fB\-\-oneatatime\fP.
.RE
.sp
\fB\-o\fP, \fB\-\-oneatatime\fP
.RS 4
Replay one packet at a time for each user input. Cannot be combined with: \fB\-\-mbps\fP, \fB\-\-pps\fP, \fB\-\-multiplier\fP, \fB\-\-topspeed\fP.
.sp
Allows you to step through one or more packets at a time.
.RE
.sp
\fB\-\-pps\-multi\fP=\fInumber\fP
.RS 4
Number of packets to send for each time interval. Range: 1 to any. Default: \f(CR1\fP. Requires: \fB\-\-pps\fP.
.sp
When trying to send packets at very high rates, the time between each packet can be so short that it is impossible to accurately sleep for the required period of time.  This option allows you to send multiple packets at a time, thus allowing for longer sleep times which can be more accurately implemented.
.RE
.sp
\fB\-\-unique\-ip\fP
.RS 4
Modify IP addresses each loop iteration to generate unique flows. Requires: \fB\-\-loop\fP. Cannot be combined with: \fB\-\-seed\fP, \fB\-\-fuzz\-seed\fP.
.sp
Ensure IPv4 and IPv6 packets will be unique for each \fI\-\-loop\fP iteration. This is done in a way that will not alter packet CRC, and therefore will generally not affect performance. This option will significantly increase the flows/sec over generated over multiple loop iterations.
.RE
.sp
\fB\-\-unique\-ip\-loops\fP=\fIstring\fP
.RS 4
Number of times to loop before assigning new unique ip. Requires: \fB\-\-unique\-ip\fP.
.sp
Number of \fI\-\-loop\fP iterations before a new unique IP is assigned. Default is 1. Assumes both \fI\-\-loop\fP and \fI\-\-unique\-ip\fP.
.RE
.sp
\fB\-\-netmap\fP
.RS 4
Write packets directly to netmap enabled network adapter.
.sp
This feature will detect netmap capable network drivers on Linux and BSD systems. If detected, the network driver is bypassed for the execution duration, and network buffers will be written to directly. This will allow you to achieve full line rates on commodity network adapters, similar to rates achieved by commercial network traffic generators. Note that bypassing the network driver will disrupt other applications connected through the test interface. See INSTALL for more information.
.sp
This feature can also be enabled by specifying an interface as \*(Aqnetmap:<intf>\*(Aq or \*(Aqvale:<intf>. For example \*(Aqnetmap:eth0\*(Aq specifies netmap over interface eth0.
.RE
.sp
\fB\-\-nm\-delay\fP=\fInumber\fP
.RS 4
Netmap startup delay. Default: \f(CR10\fP.
.sp
Number of seconds to delay after netmap is loaded. Required to ensure interfaces are fully up before netmap transmit. Requires netmap option. Default is 10 seconds.
.RE
.sp
\fB\-\-no\-flow\-stats\fP
.RS 4
Suppress printing and tracking flow count, rates and expirations.
.sp
Suppress the collection and printing of flow statistics. This option may improve performance when not using \fI\-\-preload\-pcap\fP option, otherwise its only function is to suppress printing.
.sp
The flow feature will track and print statistics of the flows being sent. A flow is loosely defined as a unique combination of a 5\-tuple, i.e. source IP, destination IP, source port, destination port and protocol.
.sp
If \fI\-\-loop\fP is specified, the flows from one iteration to the next will not be unique, unless the packets are altered. Use \fI\-\-unique\-ip\fP or \fItcpreplay\-edit\fP to alter packets between iterations.
.RE
.sp
\fB\-\-flow\-expiry\fP=\fInumber\fP
.RS 4
Number of inactive seconds before a flow is considered expired. Range: 0 to any. Default: \f(CR0\fP. Cannot be combined with: \fB\-\-no\-flow\-stats\fP.
.sp
This option will track and report flow expirations based on the flow idle times. The timestamps within the pcap file are used to determine the expiry, not the actual timestamp of the packets are replayed. For example, a value of 30 suggests that if no traffic is seen on a flow for 30 seconds, any subsequent traffic would be considered a new flow, and thereby will increment the flows and flows per second (fps) statistics.
.sp
This option can be used to optimize flow timeout settings for flow products. Setting the timeout low may lead to flows being dropped when in fact the flow is simply slow to respond. Configuring your flow timeouts too high may increase resources required by your flow product.
.sp
Note that using this option while replaying at higher than original speeds can lead to inflated flows and fps counts.
.sp
Default is 0 (no expiry) and a typical value is 30\-120 seconds.
.RE
.sp
\fB\-P\fP, \fB\-\-pid\fP
.RS 4
Print the PID of tcpreplay at startup.
.RE
.sp
\fB\-\-stats\fP=\fInumber\fP
.RS 4
Print statistics every X seconds, or every loop if \*(Aq0\*(Aq. Range: 0 to any.
.sp
Note that timed delays are a "best effort" and long delays between sending packets may cause equally long delays between printing statistics.
.RE
.sp
\fB\-W\fP, \fB\-\-suppress\-warnings\fP
.RS 4
suppress printing warning messages.
.RE
.sp
\fB\-\-xdp\fP
.RS 4
Write packets directly to AF_XDP enabled network adapter.
.sp
This feature will detect AF_XDP capable network drivers on Linux systems that have \*(Aqlibxdp\-dev\*(Aq and \*(Aqlibbpf\-dev\*(Aq installed. If detected, the network stack is bypassed and packets are sent directly to an eBPF enabled driver directly. This will allow you to achieve full line rates on commodity network adapters, similar to rates achieved by commercial network traffic generators.
.RE
.sp
\fB\-\-xdp\-batch\-size\fP=\fInumber\fP
.RS 4
The maximum number of packets that can be submitted to the AF_XDP TX ring at once. Range: 1 to 4096. Default: \f(CR1\fP. Requires: \fB\-\-xdp\fP, \fB\-\-topspeed\fP. Cannot be combined with: \fB\-\-oneatatime\fP, \fB\-\-pps\-multi\fP.
.sp
Only allowed if sending at top speed. Values higher than 1 may improve performance at the cost of accuracy.
.RE
.sp
\fB\-\-io\-uring\fP
.RS 4
Send packets asynchronously via Linux io_uring.
.sp
This feature is available on Linux systems with a kernel that supports io_uring and \*(Aqliburing\-dev\*(Aq installed. Packets are still sent through a PF_PACKET raw socket, but sends are submitted asynchronously through an io_uring submission queue, which reduces per\-packet syscall overhead and lets the kernel process transmissions while tcpreplay prepares the next packet.
.RE
.sp
\fB\-V\fP, \fB\-\-version\fP
.RS 4
Print version information.
.RE
.sp
\fB\-h\fP, \fB\-\-less\-help\fP
.RS 4
Display less usage information and exit.
.RE
.sp
\fB\-H\fP, \fB\-\-help\fP
.RS 4
Display usage information and exit.
.RE
.sp
\fB\-\-more\-help\fP
.RS 4
Pass the extended usage information through a pager.
.RE
.sp
\fB\-\-save\-opts\fP[=\fIstring\fP]
.RS 4
Save the current option state to a config file.
.RE
.sp
\fB\-\-load\-opts\fP=\fIstring\fP, \fB\-\-no\-load\-opts\fP
.RS 4
Load options from a config file; \fB\-\-no\-load\-opts\fP disables this.
.RE
.SH "OPTION PRESETS"
.sp
Any option that is not marked as \fInot presettable\fP may be preset by loading values from configuration ("RC" or ".INI") file(s).
The homerc file is \fI$$/\fP, unless that is a directory; in that case \fI.tcpreplayrc\fP is searched for within it.
.SH "FILES"
.sp
See \fBOPTION PRESETS\fP for configuration files.
.SH "EXIT STATUS"
.sp
One of the following exit values will be returned:
.sp
\fB0\fP (EXIT_SUCCESS)
.RS 4
Successful program execution.
.RE
.sp
\fB1\fP (EXIT_FAILURE)
.RS 4
The operation failed or the command syntax was not valid.
.RE
.sp
\fB66\fP (EX_NOINPUT)
.RS 4
A specified configuration file could not be loaded.
.RE
.sp
\fB70\fP (EX_SOFTWARE)
.RS 4
libopts had an internal operational error. Please report it to \c
.MTO "autogen\-users\(atlists.sourceforge.net" "" "."
Thank you.
.RE
.SH "AUTHORS"
.sp
Copyright 2013\-2026 Fred Klassen \- AppNeta
.sp
Copyright 2000\-2012 Aaron Turner
.sp
For support please use the \c
.MTO "tcpreplay\-users\(atlists.sourceforge.net" "" ""
mailing list.
.sp
The latest version of this software is always available from: \c
.URL "http://tcpreplay.appneta.com/" "" ""
.SH "COPYRIGHT"
.sp
Copyright \(co 2000\-2026 Aaron Turner and Fred Klassen, all rights reserved.
This program is released under the terms of the GNU General Public License, version 3 or later.
.SH "BUGS"
.sp
Please send bug reports to: \c
.MTO "tcpreplay\-users\(atlists.sourceforge.net" "" ""
.SH "NOTES"
.sp
This manual page was generated from the tcpreplay option definitions.