/*   -*- buffer-read-only: t -*- vi: set ro:
 *  
 *  DO NOT EDIT THIS FILE   (tcprewrite_opts.c)
 *  
 *  It has been AutoGen-ed  May  7, 2013 at 11:11:45 PM by AutoGen 5.16.2
 *  From the definitions    tcprewrite_opts.def
 *  and the template file   options
 *
 * Generated from AutoOpts 36:5:11 templates.
 *
 *  AutoOpts is a copyrighted work.  This source file is not encumbered
 *  by AutoOpts licensing, but is provided under the licensing terms chosen
 *  by the tcprewrite author or copyright holder.  AutoOpts is
 *  licensed under the terms of the LGPL.  The redistributable library
 *  (``libopts'') is licensed under the terms of either the LGPL or, at the
 *  users discretion, the BSD license.  See the AutoOpts and/or libopts sources
 *  for details.
 *
 * The tcprewrite program is copyrighted and licensed
 * under the following terms:
 *
 *  Copyright (C) 2000-2010 Aaron Turner, all rights reserved.
 *  This is free software. It is licensed for use, modification and
 *  redistribution under the terms of the
 *  GNU General Public License, version 3 or later
 *      <http://gnu.org/licenses/gpl.html>
 *
 *  tcprewrite is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  tcprewrite is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along
 *  with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __doxygen__
#define OPTION_CODE_COMPILE 1
#include "tcprewrite_opts.h"
#include <sys/types.h>

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

#ifdef  __cplusplus
extern "C" {
#endif
extern FILE * option_usage_fp;

/* TRANSLATORS: choose the translation for option names wisely because you
                cannot ever change your mind. */
#define zCopyright      (tcprewrite_opt_strs+0)
#define zLicenseDescrip (tcprewrite_opt_strs+272)

/*
 *  global included definitions
 */
#include "defines.h"
#include "common.h"
#include "config.h"
#include "tcprewrite.h"
#include <stdlib.h>
#include <string.h>
extern tcprewrite_opt_t options;


#ifndef NULL
#  define NULL 0
#endif

/*
 *  tcprewrite option static const strings
 */
static char const tcprewrite_opt_strs[4563] =
/*     0 */ "tcprewrite (tcprewrite)\n"
            "Copyright (C) 2000-2010 Aaron Turner, all rights reserved.\n"
            "This is free software. It is licensed for use, modification and\n"
            "redistribution under the terms of the\n"
            "GNU General Public License, version 3 or later\n"
            "    <http://gnu.org/licenses/gpl.html>\n\0"
/*   272 */ "tcprewrite is free software: you can redistribute it and/or modify it under\n"
            "the terms of the GNU General Public License as published by the Free\n"
            "Software Foundation, either version 3 of the License, or (at your option)\n"
            "any later version.\n\n"
            "tcprewrite is distributed in the hope that it will be useful, but WITHOUT\n"
            "ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or\n"
            "FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for\n"
            "more details.\n\n"
            "You should have received a copy of the GNU General Public License along\n"
            "with this program.  If not, see <http://www.gnu.org/licenses/>.\n\0"
/*   881 */ ":\0"
/*   883 */ "Rewrite TCP/UDP ports\0"
/*   905 */ "PORTMAP\0"
/*   913 */ "portmap\0"
/*   921 */ "Randomize src/dst IPv4/v6 addresses w/ given seed\0"
/*   971 */ "SEED\0"
/*   976 */ "seed\0"
/*   981 */ "Rewrite IPv4/v6 addresses using pseudo-NAT\0"
/*  1024 */ "PNAT\0"
/*  1029 */ "pnat\0"
/*  1034 */ "Rewrite source IPv4/v6 addresses using pseudo-NAT\0"
/*  1084 */ "SRCIPMAP\0"
/*  1093 */ "srcipmap\0"
/*  1102 */ "Rewrite destination IPv4/v6 addresses using pseudo-NAT\0"
/*  1157 */ "DSTIPMAP\0"
/*  1166 */ "dstipmap\0"
/*  1175 */ "Rewrite IP addresses to be between two endpoints\0"
/*  1224 */ "ENDPOINTS\0"
/*  1234 */ "endpoints\0"
/*  1244 */ "Skip rewriting broadcast/multicast IPv4/v6 addresses\0"
/*  1297 */ "SKIPBROADCAST\0"
/*  1311 */ "skipbroadcast\0"
/*  1325 */ "Force recalculation of IPv4/TCP/UDP header checksums\0"
/*  1378 */ "FIXCSUM\0"
/*  1386 */ "fixcsum\0"
/*  1394 */ "Override default MTU length (1500 bytes)\0"
/*  1435 */ "MTU\0"
/*  1439 */ "mtu\0"
/*  1443 */ "Truncate packets larger then specified MTU\0"
/*  1486 */ "MTU_TRUNC\0"
/*  1496 */ "mtu-trunc\0"
/*  1506 */ "Remove Ethernet checksums (FCS) from end of frames\0"
/*  1557 */ "EFCS\0"
/*  1562 */ "efcs\0"
/*  1567 */ "Modify the IPv4/v6 TTL/Hop Limit\0"
/*  1600 */ "TTL\0"
/*  1604 */ "ttl\0"
/*  1608 */ "Set the IPv4 TOS/DiffServ/ECN byte\0"
/*  1643 */ "TOS\0"
/*  1647 */ "tos\0"
/*  1651 */ "Set the IPv6 Traffic Class byte\0"
/*  1683 */ "TCLASS\0"
/*  1690 */ "tclass\0"
/*  1697 */ "Set the IPv6 Flow Label\0"
/*  1721 */ "FLOWLABEL\0"
/*  1731 */ "flowlabel\0"
/*  1741 */ "Pad or truncate packet data to match header length\0"
/*  1792 */ "FIXLEN\0"
/*  1799 */ "fixlen\0"
/*  1806 */ "Skip rewriting broadcast/multicast Layer 2 addresses\0"
/*  1859 */ "SKIPL2BROADCAST\0"
/*  1875 */ "skipl2broadcast\0"
/*  1891 */ "Override output DLT encapsulation\0"
/*  1925 */ "DLT\0"
/*  1929 */ "dlt\0"
/*  1933 */ "Override destination ethernet MAC addresses\0"
/*  1977 */ "ENET_DMAC\0"
/*  1987 */ "enet-dmac\0"
/*  1997 */ "Override source ethernet MAC addresses\0"
/*  2036 */ "ENET_SMAC\0"
/*  2046 */ "enet-smac\0"
/*  2056 */ "Specify ethernet 802.1q VLAN tag mode\0"
/*  2094 */ "ENET_VLAN\0"
/*  2104 */ "enet-vlan\0"
/*  2114 */ "Specify the new ethernet 802.1q VLAN tag value\0"
/*  2161 */ "ENET_VLAN_TAG\0"
/*  2175 */ "enet-vlan-tag\0"
/*  2189 */ "Specify the ethernet 802.1q VLAN CFI value\0"
/*  2232 */ "ENET_VLAN_CFI\0"
/*  2246 */ "enet-vlan-cfi\0"
/*  2260 */ "Specify the ethernet 802.1q VLAN priority\0"
/*  2302 */ "ENET_VLAN_PRI\0"
/*  2316 */ "enet-vlan-pri\0"
/*  2330 */ "Specify HDLC control value\0"
/*  2357 */ "HDLC_CONTROL\0"
/*  2370 */ "hdlc-control\0"
/*  2383 */ "Specify HDLC address\0"
/*  2404 */ "HDLC_ADDRESS\0"
/*  2417 */ "hdlc-address\0"
/*  2430 */ "Set output file DLT type\0"
/*  2455 */ "USER_DLT\0"
/*  2464 */ "user-dlt\0"
/*  2473 */ "Rewrite Data-Link layer with user specified data\0"
/*  2522 */ "USER_DLINK\0"
/*  2533 */ "user-dlink\0"
/*  2544 */ "Enable debugging output\0"
/*  2568 */ "DBUG\0"
/*  2573 */ "dbug\0"
/*  2578 */ "Input pcap file to be processed\0"
/*  2610 */ "INFILE\0"
/*  2617 */ "infile\0"
/*  2624 */ "Output pcap file\0"
/*  2641 */ "OUTFILE\0"
/*  2649 */ "outfile\0"
/*  2657 */ "Split traffic via tcpprep cache file\0"
/*  2694 */ "CACHEFILE\0"
/*  2704 */ "cachefile\0"
/*  2714 */ "Print decoded packets via tcpdump to STDOUT\0"
/*  2758 */ "VERBOSE\0"
/*  2766 */ "verbose\0"
/*  2774 */ "Arguments passed to tcpdump decoder\0"
/*  2810 */ "DECODE\0"
/*  2817 */ "decode\0"
/*  2824 */ "Parse fragroute configuration file\0"
/*  2859 */ "FRAGROUTE\0"
/*  2869 */ "fragroute\0"
/*  2879 */ "Which flows to apply fragroute to: c2s, s2c, both\0"
/*  2929 */ "FRAGDIR\0"
/*  2937 */ "fragdir\0"
/*  2945 */ "Skip writing packets with soft errors\0"
/*  2983 */ "SKIP_SOFT_ERRORS\0"
/*  3000 */ "skip-soft-errors\0"
/*  3017 */ "Print version information\0"
/*  3043 */ "VERSION\0"
/*  3051 */ "version\0"
/*  3059 */ "Display less usage information and exit\0"
/*  3099 */ "LESS_HELP\0"
/*  3109 */ "less-help\0"
/*  3119 */ "Display extended usage information and exit\0"
/*  3163 */ "help\0"
/*  3168 */ "Extended usage information passed thru pager\0"
/*  3213 */ "more-help\0"
/*  3223 */ "Save the option state to a config file\0"
/*  3262 */ "save-opts\0"
/*  3272 */ "Load options from a config file\0"
/*  3304 */ "LOAD_OPTS\0"
/*  3314 */ "no-load-opts\0"
/*  3327 */ "no\0"
/*  3330 */ "TCPREWRITE\0"
/*  3341 */ "tcprewrite (tcprewrite) - Rewrite the packets in a pcap file.\n"
            "USAGE:  %s [ -<flag> [<val>] | --<name>[{=| }<val>] ]...\n\0"
/*  3461 */ "$$/\0"
/*  3465 */ ".tcprewriterc\0"
/*  3479 */ "tcpreplay-users@lists.sourceforge.net\0"
/*  3517 */ "\n"
            "Tcprewrite is a tool to rewrite packets stored in ``pcap(3)'' file format,\n"
            "such as crated by tools such as ``tcpdump(1)'' and ``ethereal(1)''.  Once a\n"
            "pcap file has had it's packets rewritten, they can be replayed back out on\n"
            "the network using ``tcpreplay(1)''.\n\n"
            "tcprewrite currently supports reading the following DLT types:\n\n\n"
            "``DLT_C_HDLC'' aka Cisco HDLC\n\n\n"
            "``DLT_EN10MB'' aka Ethernet\n\n\n"
            "``DLT_LINUX_SLL'' aka Linux Cooked Socket\n\n\n"
            "``DLT_RAW'' aka RAW IP\n\n\n"
            "``DLT_NULL'' aka BSD Loopback\n\n\n"
            "``DLT_LOOP'' aka OpenBSD Loopback\n\n\n"
            "``DLT_IEEE802_11'' aka 802.11a/b/g\n\n\n"
            "``DLT_IEEE802_11_RADIO'' aka 802.11a/b/g with Radiotap headers\n\n\n"
            "``DLT_JUNIPER_ETHER'' aka Juniper Encapsulated Ethernet\n\n\n"
            "``DLT_PPP_SERIAL'' aka PPP over serial with HDLC encapsulation\n\n"
            "Please see the --dlt option for supported DLT types for writing.\n\n"
            "The packet editing features of tcprewrite which distinguish between\n"
            "\"client\" and \"server\" traffic requires a tcpprep(1) cache file.\n\n"
            "For more details, please see the Tcpreplay Manual at:\n"
            "http://tcpreplay.synfin.net/wiki/manual\n";

/*
 *  tcpedit option description:
 */
#define TCPEDIT_DESC      (tcprewrite_opt_strs+881)
#define TCPEDIT_FLAGS     (OPTST_DOCUMENT | OPTST_NO_INIT)

/*
 *  portmap option description:
 */
#define PORTMAP_DESC      (tcprewrite_opt_strs+883)
#define PORTMAP_NAME      (tcprewrite_opt_strs+905)
#define PORTMAP_name      (tcprewrite_opt_strs+913)
#define PORTMAP_FLAGS     (OPTST_DISABLED | OPTST_STACKED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  seed option description:
 */
#define SEED_DESC      (tcprewrite_opt_strs+921)
#define SEED_NAME      (tcprewrite_opt_strs+971)
#define SEED_name      (tcprewrite_opt_strs+976)
#define SEED_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  pnat option description with
 *  "Must also have options" and "Incompatible options":
 */
#define PNAT_DESC      (tcprewrite_opt_strs+981)
#define PNAT_NAME      (tcprewrite_opt_strs+1024)
#define PNAT_name      (tcprewrite_opt_strs+1029)
static int const aPnatCantList[] = {
    INDEX_OPT_SRCIPMAP, NO_EQUIVALENT };
#define PNAT_FLAGS     (OPTST_DISABLED | OPTST_STACKED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  srcipmap option description with
 *  "Must also have options" and "Incompatible options":
 */
#define SRCIPMAP_DESC      (tcprewrite_opt_strs+1034)
#define SRCIPMAP_NAME      (tcprewrite_opt_strs+1084)
#define SRCIPMAP_name      (tcprewrite_opt_strs+1093)
static int const aSrcipmapCantList[] = {
    INDEX_OPT_PNAT, NO_EQUIVALENT };
#define SRCIPMAP_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  dstipmap option description with
 *  "Must also have options" and "Incompatible options":
 */
#define DSTIPMAP_DESC      (tcprewrite_opt_strs+1102)
#define DSTIPMAP_NAME      (tcprewrite_opt_strs+1157)
#define DSTIPMAP_name      (tcprewrite_opt_strs+1166)
static int const aDstipmapCantList[] = {
    INDEX_OPT_PNAT, NO_EQUIVALENT };
#define DSTIPMAP_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  endpoints option description with
 *  "Must also have options" and "Incompatible options":
 */
#ifdef HAVE_CACHEFILE_SUPPORT
#define ENDPOINTS_DESC      (tcprewrite_opt_strs+1175)
#define ENDPOINTS_NAME      (tcprewrite_opt_strs+1224)
#define ENDPOINTS_name      (tcprewrite_opt_strs+1234)
static int const aEndpointsMustList[] = {
    INDEX_OPT_CACHEFILE, NO_EQUIVALENT };
#define ENDPOINTS_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

#else   /* disable endpoints */
#define ENDPOINTS_FLAGS     (OPTST_OMITTED | OPTST_NO_INIT)
#define aEndpointsMustList   NULL
#define ENDPOINTS_NAME      NULL
#define ENDPOINTS_DESC      NULL
#define ENDPOINTS_name      NULL
#endif  /* HAVE_CACHEFILE_SUPPORT */

/*
 *  skipbroadcast option description:
 */
#define SKIPBROADCAST_DESC      (tcprewrite_opt_strs+1244)
#define SKIPBROADCAST_NAME      (tcprewrite_opt_strs+1297)
#define SKIPBROADCAST_name      (tcprewrite_opt_strs+1311)
#define SKIPBROADCAST_FLAGS     (OPTST_DISABLED)

/*
 *  fixcsum option description:
 */
#define FIXCSUM_DESC      (tcprewrite_opt_strs+1325)
#define FIXCSUM_NAME      (tcprewrite_opt_strs+1378)
#define FIXCSUM_name      (tcprewrite_opt_strs+1386)
#define FIXCSUM_FLAGS     (OPTST_DISABLED)

/*
 *  mtu option description:
 */
#define MTU_DESC      (tcprewrite_opt_strs+1394)
#define MTU_NAME      (tcprewrite_opt_strs+1435)
#define MTU_name      (tcprewrite_opt_strs+1439)
#define MTU_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  mtu-trunc option description:
 */
#define MTU_TRUNC_DESC      (tcprewrite_opt_strs+1443)
#define MTU_TRUNC_NAME      (tcprewrite_opt_strs+1486)
#define MTU_TRUNC_name      (tcprewrite_opt_strs+1496)
#define MTU_TRUNC_FLAGS     (OPTST_DISABLED)

/*
 *  efcs option description:
 */
#define EFCS_DESC      (tcprewrite_opt_strs+1506)
#define EFCS_NAME      (tcprewrite_opt_strs+1557)
#define EFCS_name      (tcprewrite_opt_strs+1562)
#define EFCS_FLAGS     (OPTST_DISABLED)

/*
 *  ttl option description:
 */
#define TTL_DESC      (tcprewrite_opt_strs+1567)
#define TTL_NAME      (tcprewrite_opt_strs+1600)
#define TTL_name      (tcprewrite_opt_strs+1604)
#define TTL_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  tos option description:
 */
#define TOS_DESC      (tcprewrite_opt_strs+1608)
#define TOS_NAME      (tcprewrite_opt_strs+1643)
#define TOS_name      (tcprewrite_opt_strs+1647)
#define TOS_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  tclass option description:
 */
#define TCLASS_DESC      (tcprewrite_opt_strs+1651)
#define TCLASS_NAME      (tcprewrite_opt_strs+1683)
#define TCLASS_name      (tcprewrite_opt_strs+1690)
#define TCLASS_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  flowlabel option description:
 */
#define FLOWLABEL_DESC      (tcprewrite_opt_strs+1697)
#define FLOWLABEL_NAME      (tcprewrite_opt_strs+1721)
#define FLOWLABEL_name      (tcprewrite_opt_strs+1731)
#define FLOWLABEL_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  fixlen option description:
 */
#define FIXLEN_DESC      (tcprewrite_opt_strs+1741)
#define FIXLEN_NAME      (tcprewrite_opt_strs+1792)
#define FIXLEN_name      (tcprewrite_opt_strs+1799)
#define FIXLEN_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  skipl2broadcast option description:
 */
#define SKIPL2BROADCAST_DESC      (tcprewrite_opt_strs+1806)
#define SKIPL2BROADCAST_NAME      (tcprewrite_opt_strs+1859)
#define SKIPL2BROADCAST_name      (tcprewrite_opt_strs+1875)
#define SKIPL2BROADCAST_FLAGS     (OPTST_DISABLED)

/*
 *  dlt option description:
 */
#define DLT_DESC      (tcprewrite_opt_strs+1891)
#define DLT_NAME      (tcprewrite_opt_strs+1925)
#define DLT_name      (tcprewrite_opt_strs+1929)
#define DLT_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  enet-dmac option description:
 */
#define ENET_DMAC_DESC      (tcprewrite_opt_strs+1933)
#define ENET_DMAC_NAME      (tcprewrite_opt_strs+1977)
#define ENET_DMAC_name      (tcprewrite_opt_strs+1987)
#define ENET_DMAC_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  enet-smac option description:
 */
#define ENET_SMAC_DESC      (tcprewrite_opt_strs+1997)
#define ENET_SMAC_NAME      (tcprewrite_opt_strs+2036)
#define ENET_SMAC_name      (tcprewrite_opt_strs+2046)
#define ENET_SMAC_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  enet-vlan option description:
 */
#define ENET_VLAN_DESC      (tcprewrite_opt_strs+2056)
#define ENET_VLAN_NAME      (tcprewrite_opt_strs+2094)
#define ENET_VLAN_name      (tcprewrite_opt_strs+2104)
#define ENET_VLAN_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  enet-vlan-tag option description with
 *  "Must also have options" and "Incompatible options":
 */
#define ENET_VLAN_TAG_DESC      (tcprewrite_opt_strs+2114)
#define ENET_VLAN_TAG_NAME      (tcprewrite_opt_strs+2161)
#define ENET_VLAN_TAG_name      (tcprewrite_opt_strs+2175)
static int const aEnet_Vlan_TagMustList[] = {
    INDEX_OPT_ENET_VLAN, NO_EQUIVALENT };
#define ENET_VLAN_TAG_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  enet-vlan-cfi option description with
 *  "Must also have options" and "Incompatible options":
 */
#define ENET_VLAN_CFI_DESC      (tcprewrite_opt_strs+2189)
#define ENET_VLAN_CFI_NAME      (tcprewrite_opt_strs+2232)
#define ENET_VLAN_CFI_name      (tcprewrite_opt_strs+2246)
static int const aEnet_Vlan_CfiMustList[] = {
    INDEX_OPT_ENET_VLAN, NO_EQUIVALENT };
#define ENET_VLAN_CFI_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  enet-vlan-pri option description with
 *  "Must also have options" and "Incompatible options":
 */
#define ENET_VLAN_PRI_DESC      (tcprewrite_opt_strs+2260)
#define ENET_VLAN_PRI_NAME      (tcprewrite_opt_strs+2302)
#define ENET_VLAN_PRI_name      (tcprewrite_opt_strs+2316)
static int const aEnet_Vlan_PriMustList[] = {
    INDEX_OPT_ENET_VLAN, NO_EQUIVALENT };
#define ENET_VLAN_PRI_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  hdlc-control option description:
 */
#define HDLC_CONTROL_DESC      (tcprewrite_opt_strs+2330)
#define HDLC_CONTROL_NAME      (tcprewrite_opt_strs+2357)
#define HDLC_CONTROL_name      (tcprewrite_opt_strs+2370)
#define HDLC_CONTROL_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  hdlc-address option description:
 */
#define HDLC_ADDRESS_DESC      (tcprewrite_opt_strs+2383)
#define HDLC_ADDRESS_NAME      (tcprewrite_opt_strs+2404)
#define HDLC_ADDRESS_name      (tcprewrite_opt_strs+2417)
#define HDLC_ADDRESS_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  user-dlt option description:
 */
#define USER_DLT_DESC      (tcprewrite_opt_strs+2430)
#define USER_DLT_NAME      (tcprewrite_opt_strs+2455)
#define USER_DLT_name      (tcprewrite_opt_strs+2464)
#define USER_DLT_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  user-dlink option description:
 */
#define USER_DLINK_DESC      (tcprewrite_opt_strs+2473)
#define USER_DLINK_NAME      (tcprewrite_opt_strs+2522)
#define USER_DLINK_name      (tcprewrite_opt_strs+2533)
#define USER_DLINK_FLAGS     (OPTST_DISABLED | OPTST_STACKED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  dbug option description:
 */
#ifdef DEBUG
#define DBUG_DESC      (tcprewrite_opt_strs+2544)
#define DBUG_NAME      (tcprewrite_opt_strs+2568)
#define DBUG_name      (tcprewrite_opt_strs+2573)
#define DBUG_DFT_ARG   ((char const*)0)
#define DBUG_FLAGS     (OPTST_DISABLED | OPTST_IMM \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

#else   /* disable dbug */
#define DBUG_FLAGS     (OPTST_OMITTED | OPTST_NO_INIT)
#define DBUG_DFT_ARG   NULL
#define DBUG_NAME      NULL
#define DBUG_DESC      NULL
#define DBUG_name      NULL
#endif  /* DEBUG */

/*
 *  infile option description:
 */
#define INFILE_DESC      (tcprewrite_opt_strs+2578)
#define INFILE_NAME      (tcprewrite_opt_strs+2610)
#define INFILE_name      (tcprewrite_opt_strs+2617)
#define INFILE_FLAGS     (OPTST_DISABLED | OPTST_MUST_SET | OPTST_IMM \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  outfile option description:
 */
#define OUTFILE_DESC      (tcprewrite_opt_strs+2624)
#define OUTFILE_NAME      (tcprewrite_opt_strs+2641)
#define OUTFILE_name      (tcprewrite_opt_strs+2649)
#define OUTFILE_FLAGS     (OPTST_DISABLED | OPTST_MUST_SET \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  cachefile option description:
 */
#define CACHEFILE_DESC      (tcprewrite_opt_strs+2657)
#define CACHEFILE_NAME      (tcprewrite_opt_strs+2694)
#define CACHEFILE_name      (tcprewrite_opt_strs+2704)
#define CACHEFILE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  verbose option description:
 */
#ifdef ENABLE_VERBOSE
#define VERBOSE_DESC      (tcprewrite_opt_strs+2714)
#define VERBOSE_NAME      (tcprewrite_opt_strs+2758)
#define VERBOSE_name      (tcprewrite_opt_strs+2766)
#define VERBOSE_FLAGS     (OPTST_DISABLED | OPTST_IMM)

#else   /* disable verbose */
#define VERBOSE_FLAGS     (OPTST_OMITTED | OPTST_NO_INIT)
#define VERBOSE_NAME      NULL
#define VERBOSE_DESC      NULL
#define VERBOSE_name      NULL
#endif  /* ENABLE_VERBOSE */

/*
 *  decode option description with
 *  "Must also have options" and "Incompatible options":
 */
#ifdef ENABLE_VERBOSE
#define DECODE_DESC      (tcprewrite_opt_strs+2774)
#define DECODE_NAME      (tcprewrite_opt_strs+2810)
#define DECODE_name      (tcprewrite_opt_strs+2817)
static int const aDecodeMustList[] = {
    INDEX_OPT_VERBOSE, NO_EQUIVALENT };
#define DECODE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

#else   /* disable decode */
#define DECODE_FLAGS     (OPTST_OMITTED | OPTST_NO_INIT)
#define aDecodeMustList   NULL
#define DECODE_NAME      NULL
#define DECODE_DESC      NULL
#define DECODE_name      NULL
#endif  /* ENABLE_VERBOSE */

/*
 *  fragroute option description:
 */
#ifdef ENABLE_FRAGROUTE
#define FRAGROUTE_DESC      (tcprewrite_opt_strs+2824)
#define FRAGROUTE_NAME      (tcprewrite_opt_strs+2859)
#define FRAGROUTE_name      (tcprewrite_opt_strs+2869)
#define FRAGROUTE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

#else   /* disable fragroute */
#define FRAGROUTE_FLAGS     (OPTST_OMITTED | OPTST_NO_INIT)
#define FRAGROUTE_NAME      NULL
#define FRAGROUTE_DESC      NULL
#define FRAGROUTE_name      NULL
#endif  /* ENABLE_FRAGROUTE */

/*
 *  fragdir option description with
 *  "Must also have options" and "Incompatible options":
 */
#ifdef ENABLE_FRAGROUTE
#define FRAGDIR_DESC      (tcprewrite_opt_strs+2879)
#define FRAGDIR_NAME      (tcprewrite_opt_strs+2929)
#define FRAGDIR_name      (tcprewrite_opt_strs+2937)
static int const aFragdirMustList[] = {
    INDEX_OPT_CACHEFILE, NO_EQUIVALENT };
#define FRAGDIR_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

#else   /* disable fragdir */
#define FRAGDIR_FLAGS     (OPTST_OMITTED | OPTST_NO_INIT)
#define aFragdirMustList   NULL
#define FRAGDIR_NAME      NULL
#define FRAGDIR_DESC      NULL
#define FRAGDIR_name      NULL
#endif  /* ENABLE_FRAGROUTE */

/*
 *  skip-soft-errors option description:
 */
#define SKIP_SOFT_ERRORS_DESC      (tcprewrite_opt_strs+2945)
#define SKIP_SOFT_ERRORS_NAME      (tcprewrite_opt_strs+2983)
#define SKIP_SOFT_ERRORS_name      (tcprewrite_opt_strs+3000)
#define SKIP_SOFT_ERRORS_FLAGS     (OPTST_DISABLED)

/*
 *  version option description:
 */
#define VERSION_DESC      (tcprewrite_opt_strs+3017)
#define VERSION_NAME      (tcprewrite_opt_strs+3043)
#define VERSION_name      (tcprewrite_opt_strs+3051)
#define VERSION_FLAGS     (OPTST_DISABLED)

/*
 *  less-help option description:
 */
#define LESS_HELP_DESC      (tcprewrite_opt_strs+3059)
#define LESS_HELP_NAME      (tcprewrite_opt_strs+3099)
#define LESS_HELP_name      (tcprewrite_opt_strs+3109)
#define LESS_HELP_FLAGS     (OPTST_DISABLED | OPTST_IMM)

/*
 *  Help/More_Help option descriptions:
 */
#define HELP_DESC       (tcprewrite_opt_strs+3119)
#define HELP_name       (tcprewrite_opt_strs+3163)
#ifdef HAVE_WORKING_FORK
#define MORE_HELP_DESC  (tcprewrite_opt_strs+3168)
#define MORE_HELP_name  (tcprewrite_opt_strs+3213)
#define MORE_HELP_FLAGS (OPTST_IMM | OPTST_NO_INIT)
#else
#define MORE_HELP_DESC  NULL
#define MORE_HELP_name  NULL
#define MORE_HELP_FLAGS (OPTST_OMITTED | OPTST_NO_INIT)
#endif
#define SAVE_OPTS_DESC  (tcprewrite_opt_strs+3223)
#define SAVE_OPTS_name  (tcprewrite_opt_strs+3262)
#define LOAD_OPTS_DESC     (tcprewrite_opt_strs+3272)
#define LOAD_OPTS_NAME     (tcprewrite_opt_strs+3304)
#define NO_LOAD_OPTS_name  (tcprewrite_opt_strs+3314)
#define LOAD_OPTS_pfx      (tcprewrite_opt_strs+3327)
#define LOAD_OPTS_name     (NO_LOAD_OPTS_name + 3)
/*
 *  Declare option callback procedures
 */
#ifdef DEBUG
  static tOptProc doOptDbug;
#else /* not DEBUG */
# define doOptDbug NULL
#endif /* def/not DEBUG */
extern tOptProc
    optionBooleanVal,   optionNestedVal,    optionNumericVal,
    optionPagedUsage,   optionPrintVersion, optionResetOpt,
    optionStackArg,     optionTimeDate,     optionTimeVal,
    optionUnstackArg,   optionVendorOption;
static tOptProc
    doOptCachefile,     doOptEnet_Vlan_Cfi, doOptEnet_Vlan_Pri,
    doOptEnet_Vlan_Tag, doOptFlowlabel,     doOptLess_Help,
    doOptMtu,           doOptTclass,        doOptTos,
    doOptVersion,       doUsageOpt;

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 *  Define the tcprewrite Option Descriptions.
 * This is an array of OPTION_CT entries, one for each
 * option that the tcprewrite program responds to.
 */
static tOptDesc optDesc[OPTION_CT] = {
  {  /* entry idx, value */ 0, 0,
     /* equiv idx, value */ 0, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 0, 0,
     /* opt state flags  */ TCPEDIT_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ TCPEDIT_DESC, NULL, NULL,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 1, VALUE_OPT_PORTMAP,
     /* equiv idx, value */ 1, VALUE_OPT_PORTMAP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, -1, 0,
     /* opt state flags  */ PORTMAP_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --portmap */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionStackArg,
     /* desc, NAME, name */ PORTMAP_DESC, PORTMAP_NAME, PORTMAP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 2, VALUE_OPT_SEED,
     /* equiv idx, value */ 2, VALUE_OPT_SEED,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SEED_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --seed */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionNumericVal,
     /* desc, NAME, name */ SEED_DESC, SEED_NAME, SEED_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 3, VALUE_OPT_PNAT,
     /* equiv idx, value */ 3, VALUE_OPT_PNAT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 2, 0,
     /* opt state flags  */ PNAT_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --pnat */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aPnatCantList,
     /* option proc      */ optionStackArg,
     /* desc, NAME, name */ PNAT_DESC, PNAT_NAME, PNAT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 4, VALUE_OPT_SRCIPMAP,
     /* equiv idx, value */ 4, VALUE_OPT_SRCIPMAP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SRCIPMAP_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --srcipmap */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aSrcipmapCantList,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SRCIPMAP_DESC, SRCIPMAP_NAME, SRCIPMAP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 5, VALUE_OPT_DSTIPMAP,
     /* equiv idx, value */ 5, VALUE_OPT_DSTIPMAP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DSTIPMAP_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --dstipmap */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aDstipmapCantList,
     /* option proc      */ NULL,
     /* desc, NAME, name */ DSTIPMAP_DESC, DSTIPMAP_NAME, DSTIPMAP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 6, VALUE_OPT_ENDPOINTS,
     /* equiv idx, value */ 6, VALUE_OPT_ENDPOINTS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ ENDPOINTS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --endpoints */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aEndpointsMustList, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ ENDPOINTS_DESC, ENDPOINTS_NAME, ENDPOINTS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 7, VALUE_OPT_SKIPBROADCAST,
     /* equiv idx, value */ 7, VALUE_OPT_SKIPBROADCAST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SKIPBROADCAST_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --skipbroadcast */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SKIPBROADCAST_DESC, SKIPBROADCAST_NAME, SKIPBROADCAST_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 8, VALUE_OPT_FIXCSUM,
     /* equiv idx, value */ 8, VALUE_OPT_FIXCSUM,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ FIXCSUM_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --fixcsum */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ FIXCSUM_DESC, FIXCSUM_NAME, FIXCSUM_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 9, VALUE_OPT_MTU,
     /* equiv idx, value */ 9, VALUE_OPT_MTU,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MTU_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --mtu */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptMtu,
     /* desc, NAME, name */ MTU_DESC, MTU_NAME, MTU_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 10, VALUE_OPT_MTU_TRUNC,
     /* equiv idx, value */ 10, VALUE_OPT_MTU_TRUNC,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MTU_TRUNC_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --mtu-trunc */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ MTU_TRUNC_DESC, MTU_TRUNC_NAME, MTU_TRUNC_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 11, VALUE_OPT_EFCS,
     /* equiv idx, value */ 11, VALUE_OPT_EFCS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ EFCS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --efcs */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ EFCS_DESC, EFCS_NAME, EFCS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 12, VALUE_OPT_TTL,
     /* equiv idx, value */ 12, VALUE_OPT_TTL,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TTL_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --ttl */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ TTL_DESC, TTL_NAME, TTL_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 13, VALUE_OPT_TOS,
     /* equiv idx, value */ 13, VALUE_OPT_TOS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TOS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --tos */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptTos,
     /* desc, NAME, name */ TOS_DESC, TOS_NAME, TOS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 14, VALUE_OPT_TCLASS,
     /* equiv idx, value */ 14, VALUE_OPT_TCLASS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TCLASS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --tclass */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptTclass,
     /* desc, NAME, name */ TCLASS_DESC, TCLASS_NAME, TCLASS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 15, VALUE_OPT_FLOWLABEL,
     /* equiv idx, value */ 15, VALUE_OPT_FLOWLABEL,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ FLOWLABEL_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --flowlabel */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptFlowlabel,
     /* desc, NAME, name */ FLOWLABEL_DESC, FLOWLABEL_NAME, FLOWLABEL_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 16, VALUE_OPT_FIXLEN,
     /* equiv idx, value */ 16, VALUE_OPT_FIXLEN,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ FIXLEN_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --fixlen */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ FIXLEN_DESC, FIXLEN_NAME, FIXLEN_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 17, VALUE_OPT_SKIPL2BROADCAST,
     /* equiv idx, value */ 17, VALUE_OPT_SKIPL2BROADCAST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SKIPL2BROADCAST_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --skipl2broadcast */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SKIPL2BROADCAST_DESC, SKIPL2BROADCAST_NAME, SKIPL2BROADCAST_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 18, VALUE_OPT_DLT,
     /* equiv idx, value */ 18, VALUE_OPT_DLT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DLT_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --dlt */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ DLT_DESC, DLT_NAME, DLT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 19, VALUE_OPT_ENET_DMAC,
     /* equiv idx, value */ 19, VALUE_OPT_ENET_DMAC,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ ENET_DMAC_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --enet-dmac */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ ENET_DMAC_DESC, ENET_DMAC_NAME, ENET_DMAC_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 20, VALUE_OPT_ENET_SMAC,
     /* equiv idx, value */ 20, VALUE_OPT_ENET_SMAC,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ ENET_SMAC_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --enet-smac */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ ENET_SMAC_DESC, ENET_SMAC_NAME, ENET_SMAC_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 21, VALUE_OPT_ENET_VLAN,
     /* equiv idx, value */ 21, VALUE_OPT_ENET_VLAN,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ ENET_VLAN_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --enet-vlan */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ ENET_VLAN_DESC, ENET_VLAN_NAME, ENET_VLAN_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 22, VALUE_OPT_ENET_VLAN_TAG,
     /* equiv idx, value */ 22, VALUE_OPT_ENET_VLAN_TAG,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ ENET_VLAN_TAG_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --enet-vlan-tag */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aEnet_Vlan_TagMustList, NULL,
     /* option proc      */ doOptEnet_Vlan_Tag,
     /* desc, NAME, name */ ENET_VLAN_TAG_DESC, ENET_VLAN_TAG_NAME, ENET_VLAN_TAG_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 23, VALUE_OPT_ENET_VLAN_CFI,
     /* equiv idx, value */ 23, VALUE_OPT_ENET_VLAN_CFI,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ ENET_VLAN_CFI_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --enet-vlan-cfi */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aEnet_Vlan_CfiMustList, NULL,
     /* option proc      */ doOptEnet_Vlan_Cfi,
     /* desc, NAME, name */ ENET_VLAN_CFI_DESC, ENET_VLAN_CFI_NAME, ENET_VLAN_CFI_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 24, VALUE_OPT_ENET_VLAN_PRI,
     /* equiv idx, value */ 24, VALUE_OPT_ENET_VLAN_PRI,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ ENET_VLAN_PRI_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --enet-vlan-pri */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aEnet_Vlan_PriMustList, NULL,
     /* option proc      */ doOptEnet_Vlan_Pri,
     /* desc, NAME, name */ ENET_VLAN_PRI_DESC, ENET_VLAN_PRI_NAME, ENET_VLAN_PRI_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 25, VALUE_OPT_HDLC_CONTROL,
     /* equiv idx, value */ 25, VALUE_OPT_HDLC_CONTROL,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ HDLC_CONTROL_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --hdlc-control */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionNumericVal,
     /* desc, NAME, name */ HDLC_CONTROL_DESC, HDLC_CONTROL_NAME, HDLC_CONTROL_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 26, VALUE_OPT_HDLC_ADDRESS,
     /* equiv idx, value */ 26, VALUE_OPT_HDLC_ADDRESS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ HDLC_ADDRESS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --hdlc-address */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionNumericVal,
     /* desc, NAME, name */ HDLC_ADDRESS_DESC, HDLC_ADDRESS_NAME, HDLC_ADDRESS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 27, VALUE_OPT_USER_DLT,
     /* equiv idx, value */ 27, VALUE_OPT_USER_DLT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ USER_DLT_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --user-dlt */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionNumericVal,
     /* desc, NAME, name */ USER_DLT_DESC, USER_DLT_NAME, USER_DLT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 28, VALUE_OPT_USER_DLINK,
     /* equiv idx, value */ 28, VALUE_OPT_USER_DLINK,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 2, 0,
     /* opt state flags  */ USER_DLINK_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --user-dlink */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionStackArg,
     /* desc, NAME, name */ USER_DLINK_DESC, USER_DLINK_NAME, USER_DLINK_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 29, VALUE_OPT_DBUG,
     /* equiv idx, value */ 29, VALUE_OPT_DBUG,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DBUG_FLAGS, 0,
     /* last opt argumnt */ { DBUG_DFT_ARG },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptDbug,
     /* desc, NAME, name */ DBUG_DESC, DBUG_NAME, DBUG_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 30, VALUE_OPT_INFILE,
     /* equiv idx, value */ 30, VALUE_OPT_INFILE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 1, 1, 0,
     /* opt state flags  */ INFILE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --infile */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ INFILE_DESC, INFILE_NAME, INFILE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 31, VALUE_OPT_OUTFILE,
     /* equiv idx, value */ 31, VALUE_OPT_OUTFILE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 1, 1, 0,
     /* opt state flags  */ OUTFILE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --outfile */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ OUTFILE_DESC, OUTFILE_NAME, OUTFILE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 32, VALUE_OPT_CACHEFILE,
     /* equiv idx, value */ 32, VALUE_OPT_CACHEFILE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ CACHEFILE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --cachefile */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptCachefile,
     /* desc, NAME, name */ CACHEFILE_DESC, CACHEFILE_NAME, CACHEFILE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 33, VALUE_OPT_VERBOSE,
     /* equiv idx, value */ 33, VALUE_OPT_VERBOSE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ VERBOSE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --verbose */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ VERBOSE_DESC, VERBOSE_NAME, VERBOSE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 34, VALUE_OPT_DECODE,
     /* equiv idx, value */ 34, VALUE_OPT_DECODE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DECODE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --decode */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aDecodeMustList, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ DECODE_DESC, DECODE_NAME, DECODE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 35, VALUE_OPT_FRAGROUTE,
     /* equiv idx, value */ 35, VALUE_OPT_FRAGROUTE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ FRAGROUTE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --fragroute */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ FRAGROUTE_DESC, FRAGROUTE_NAME, FRAGROUTE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 36, VALUE_OPT_FRAGDIR,
     /* equiv idx, value */ 36, VALUE_OPT_FRAGDIR,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ FRAGDIR_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --fragdir */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aFragdirMustList, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ FRAGDIR_DESC, FRAGDIR_NAME, FRAGDIR_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 37, VALUE_OPT_SKIP_SOFT_ERRORS,
     /* equiv idx, value */ 37, VALUE_OPT_SKIP_SOFT_ERRORS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SKIP_SOFT_ERRORS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --skip-soft-errors */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SKIP_SOFT_ERRORS_DESC, SKIP_SOFT_ERRORS_NAME, SKIP_SOFT_ERRORS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 38, VALUE_OPT_VERSION,
     /* equiv idx, value */ 38, VALUE_OPT_VERSION,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ VERSION_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --version */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptVersion,
     /* desc, NAME, name */ VERSION_DESC, VERSION_NAME, VERSION_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 39, VALUE_OPT_LESS_HELP,
     /* equiv idx, value */ 39, VALUE_OPT_LESS_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LESS_HELP_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --less-help */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptLess_Help,
     /* desc, NAME, name */ LESS_HELP_DESC, LESS_HELP_NAME, LESS_HELP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_HELP, VALUE_OPT_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doUsageOpt,
     /* desc, NAME, name */ HELP_DESC, NULL, HELP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_MORE_HELP, VALUE_OPT_MORE_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_MORE_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MORE_HELP_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ optionPagedUsage,
     /* desc, NAME, name */ MORE_HELP_DESC, NULL, MORE_HELP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_SAVE_OPTS, VALUE_OPT_SAVE_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_SAVE_OPTS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_SET_ARGTYPE(OPARG_TYPE_STRING)
                          | OPTST_ARG_OPTIONAL | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SAVE_OPTS_DESC, NULL, SAVE_OPTS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_LOAD_OPTS, VALUE_OPT_LOAD_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_LOAD_OPTS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ OPTST_SET_ARGTYPE(OPARG_TYPE_STRING)
			  | OPTST_DISABLE_IMM, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionLoadOpt,
     /* desc, NAME, name */ LOAD_OPTS_DESC, LOAD_OPTS_NAME, LOAD_OPTS_name,
     /* disablement strs */ NO_LOAD_OPTS_name, LOAD_OPTS_pfx }
};

tOptDesc * const tcpedit_tcpedit_optDesc_p = optDesc + 0;

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the tcprewrite Option Environment
 */
#define zPROGNAME       (tcprewrite_opt_strs+3330)
#define zUsageTitle     (tcprewrite_opt_strs+3341)
#define zRcName         (tcprewrite_opt_strs+3465)
static char const * const apzHomeList[2] = {
    tcprewrite_opt_strs+3461,
    NULL };
#define zBugsAddr       (tcprewrite_opt_strs+3479)
#define zExplain        (NULL)
#define zDetail         (tcprewrite_opt_strs+3517)
#define zFullVersion    (NULL)
/* extracted from optcode.tlib near line 350 */

#if defined(ENABLE_NLS)
# define OPTPROC_BASE OPTPROC_TRANSLATE
  static tOptionXlateProc translate_option_strings;
#else
# define OPTPROC_BASE OPTPROC_NONE
# define translate_option_strings NULL
#endif /* ENABLE_NLS */


#define tcprewrite_full_usage (NULL)

#define tcprewrite_short_usage (NULL)

#endif /* not defined __doxygen__ */

/*
 *  Create the static procedure(s) declared above.
 */
/**
 * The callout function that invokes the optionUsage function.
 *
 * @param pOptions the AutoOpts option description structure
 * @param pOptDesc the descriptor for the "help" (usage) option.
 * @noreturn
 */
static void
doUsageOpt(tOptions * pOptions, tOptDesc * pOptDesc)
{
    optionUsage(&tcprewriteOptions, TCPREWRITE_EXIT_SUCCESS);
    /* NOTREACHED */
    (void)pOptDesc;
    (void)pOptions;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the mtu option.
 *
 * @param pOptions the tcprewrite options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptMtu(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 1, MAXPACKET } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the tos option.
 *
 * @param pOptions the tcprewrite options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptTos(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0, 255 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the tclass option.
 *
 * @param pOptions the tcprewrite options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptTclass(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0, 255 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the flowlabel option.
 *
 * @param pOptions the tcprewrite options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptFlowlabel(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0, 1048575 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the enet-vlan-tag option.
 *
 * @param pOptions the tcprewrite options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptEnet_Vlan_Tag(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0, 4095 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the enet-vlan-cfi option.
 *
 * @param pOptions the tcprewrite options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptEnet_Vlan_Cfi(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0, 1 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the enet-vlan-pri option.
 *
 * @param pOptions the tcprewrite options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptEnet_Vlan_Pri(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0, 7 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the dbug option, when DEBUG is #define-d.
 *
 * @param pOptions the tcprewrite options data structure
 * @param pOptDesc the option descriptor for this option.
 */
#ifdef DEBUG
static void
doOptDbug(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0, 5 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}
#endif /* defined DEBUG */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the cachefile option.
 *
 * @param pOptions the tcprewrite options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptCachefile(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /* extracted from tcprewrite_opts.def, line 152 */

    options.cache_packets =
        read_cache(&options.cachedata, OPT_ARG(CACHEFILE), &options.comment);

    (void)pOptDesc;
    (void)pOptions;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the version option.
 *
 * @param pOptions the tcprewrite options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptVersion(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /* extracted from tcprewrite_opts.def, line 243 */

    fprintf(stderr, "tcprewrite version: %s (build %s)", VERSION, git_version());
#ifdef DEBUG
    fprintf(stderr, " (debug)");
#endif
    fprintf(stderr, "\n");
    fprintf(stderr, "Copyright 2000-2010 by Aaron Turner <aturner at synfin dot net>\n");
    fprintf(stderr, "The entire Tcpreplay Suite is licensed under the GPLv3\n");
    fprintf(stderr, "Cache file supported: %s\n", CACHEVERSION);
#ifdef HAVE_LIBDNET
    fprintf(stderr, "Compiled against libdnet: %s\n", LIBDNET_VERSION);
#else
    fprintf(stderr, "Not compiled with libdnet.\n");
#endif
#ifdef HAVE_WINPCAP
    fprintf(stderr, "Compiled against winpcap: %s\n", get_pcap_version());
#else
    fprintf(stderr, "Compiled against libpcap: %s\n", get_pcap_version());
#endif
#ifdef ENABLE_64BITS
    fprintf(stderr, "64 bit packet counters: enabled\n");
#else
    fprintf(stderr, "64 bit packet counters: disabled\n");
#endif
#ifdef ENABLE_VERBOSE
    fprintf(stderr, "Verbose printing via tcpdump: enabled\n");
#else
    fprintf(stderr, "Verbose printing via tcpdump: disabled\n");
#endif
#ifdef ENABLE_FRAGROUTE
    fprintf(stderr, "Fragroute engine: enabled\n");
#else
    fprintf(stderr, "Fragroute engine: disabled\n");
#endif
    exit(0);

    (void)pOptDesc;
    (void)pOptions;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the less-help option.
 *
 * @param pOptions the tcprewrite options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptLess_Help(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /* extracted from tcprewrite_opts.def, line 289 */

    USAGE(EXIT_FAILURE);

    (void)pOptDesc;
    (void)pOptions;
}
/* extracted from optmain.tlib near line 1146 */

/**
 * The directory containing the data associated with tcprewrite.
 */
#ifndef  PKGDATADIR
# define PKGDATADIR ""
#endif

/**
 * Information about the person or institution that packaged tcprewrite
 * for the current distribution.
 */
#ifndef  WITH_PACKAGER
# define tcprewrite_packager_info NULL
#else
static char const tcprewrite_packager_info[] =
    "Packaged by " WITH_PACKAGER

# ifdef WITH_PACKAGER_VERSION
        " ("WITH_PACKAGER_VERSION")"
# endif

# ifdef WITH_PACKAGER_BUG_REPORTS
    "\nReport tcprewrite bugs to " WITH_PACKAGER_BUG_REPORTS
# endif
    "\n";
#endif
#ifndef __doxygen__

#endif /* __doxygen__ */
/**
 * The option definitions for tcprewrite.  The one structure that
 * binds them all.
 */
tOptions tcprewriteOptions = {
    OPTIONS_STRUCT_VERSION,
    0, NULL,                    /* original argc + argv    */
    ( OPTPROC_BASE
    + OPTPROC_ERRSTOP
    + OPTPROC_SHORTOPT
    + OPTPROC_LONGOPT
    + OPTPROC_NO_REQ_OPT
    + OPTPROC_NO_ARGS
    + OPTPROC_GNUUSAGE ),
    0, NULL,                    /* current option index, current option */
    NULL,         NULL,         zPROGNAME,
    zRcName,      zCopyright,   zLicenseDescrip,
    zFullVersion, apzHomeList,  zUsageTitle,
    zExplain,     zDetail,      optDesc,
    zBugsAddr,                  /* address to send bugs to */
    NULL, NULL,                 /* extensions/saved state  */
    optionUsage, /* usage procedure */
    translate_option_strings,   /* translation procedure */
    /*
     *  Indexes to special options
     */
    { INDEX_OPT_MORE_HELP, /* more-help option index */
      INDEX_OPT_SAVE_OPTS, /* save option index */
      NO_EQUIVALENT, /* '-#' option index */
      9 /* index of default opt */
    },
    44 /* full option count */, 40 /* user option count */,
    tcprewrite_full_usage, tcprewrite_short_usage,
    NULL, NULL,
    PKGDATADIR, tcprewrite_packager_info
};

#if ENABLE_NLS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <autoopts/usage-txt.h>

static char* AO_gettext(char const* pz);
static void  coerce_it(void** s);

/**
 * AutoGen specific wrapper function for gettext.
 * It relies on the macro _() to convert from English to the target
 * language, then strdup-duplicates the result string.
 *
 * @param[in] pz the input text used as a lookup key.
 * @returns the translated text (if there is one),
 *   or the original text (if not).
 */
static char *
AO_gettext(char const* pz)
{
    char* pzRes;
    if (pz == NULL)
        return NULL;
    pzRes = _(pz);
    if (pzRes == pz)
        return pzRes;
    pzRes = strdup(pzRes);
    if (pzRes == NULL) {
        fputs(_("No memory for duping translated strings\n"), stderr);
        exit(TCPREWRITE_EXIT_FAILURE);
    }
    return pzRes;
}

static void coerce_it(void** s) { *s = AO_gettext(*s);
}

/**
 * Translate all the translatable strings in the tcprewriteOptions
 * structure defined above.  This is done only once.
 */
static void
translate_option_strings(void)
{
    tOptions * const pOpt = &tcprewriteOptions;

    /*
     *  Guard against re-translation.  It won't work.  The strings will have
     *  been changed by the first pass through this code.  One shot only.
     */
    if (option_usage_text.field_ct != 0) {
        /*
         *  Do the translations.  The first pointer follows the field count
         *  field.  The field count field is the size of a pointer.
         */
        tOptDesc * pOD = pOpt->pOptDesc;
        char **    ppz = (char**)(void*)&(option_usage_text);
        int        ix  = option_usage_text.field_ct;

        do {
            ppz++;
            *ppz = AO_gettext(*ppz);
        } while (--ix > 0);

        coerce_it((void*)&(pOpt->pzCopyright));
        coerce_it((void*)&(pOpt->pzCopyNotice));
        coerce_it((void*)&(pOpt->pzFullVersion));
        coerce_it((void*)&(pOpt->pzUsageTitle));
        coerce_it((void*)&(pOpt->pzExplain));
        coerce_it((void*)&(pOpt->pzDetail));
        coerce_it((void*)&(pOpt->pzPackager));
        option_usage_text.field_ct = 0;

        for (ix = pOpt->optCt; ix > 0; ix--, pOD++)
            coerce_it((void*)&(pOD->pzText));
    }

    if ((pOpt->fOptSet & OPTPROC_NXLAT_OPT_CFG) == 0) {
        tOptDesc * pOD = pOpt->pOptDesc;
        int        ix;

        for (ix = pOpt->optCt; ix > 0; ix--, pOD++) {
            coerce_it((void*)&(pOD->pz_Name));
            coerce_it((void*)&(pOD->pz_DisableName));
            coerce_it((void*)&(pOD->pz_DisablePfx));
        }
        /* prevent re-translation */
        tcprewriteOptions.fOptSet |= OPTPROC_NXLAT_OPT_CFG | OPTPROC_NXLAT_OPT;
    }
}

#endif /* ENABLE_NLS */

#ifdef  __cplusplus
}
#endif
/* tcprewrite_opts.c ends here */
