/*   -*- buffer-read-only: t -*- vi: set ro:
 *  
 *  DO NOT EDIT THIS FILE   (tcpreplay_edit_opts.c)
 *  
 *  It has been AutoGen-ed  May  8, 2013 at 01:38:26 PM by AutoGen 5.16.2
 *  From the definitions    tcpreplay_opts.def
 *  and the template file   options
 *
 * Generated from AutoOpts 36:5:11 templates.
 *
 *  AutoOpts is a copyrighted work.  This source file is not encumbered
 *  by AutoOpts licensing, but is provided under the licensing terms chosen
 *  by the tcpreplay-edit author or copyright holder.  AutoOpts is
 *  licensed under the terms of the LGPL.  The redistributable library
 *  (``libopts'') is licensed under the terms of either the LGPL or, at the
 *  users discretion, the BSD license.  See the AutoOpts and/or libopts sources
 *  for details.
 *
 * The tcpreplay-edit program is copyrighted and licensed
 * under the following terms:
 *
 *  Copyright (C) 2000-2010 Aaron Turner, all rights reserved.
 *  This is free software. It is licensed for use, modification and
 *  redistribution under the terms of the
 *  GNU General Public License, version 3 or later
 *      <http://gnu.org/licenses/gpl.html>
 *
 *  tcpreplay-edit is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  tcpreplay-edit is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along
 *  with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __doxygen__
#define OPTION_CODE_COMPILE 1
#include "tcpreplay_edit_opts.h"
#include <sys/types.h>

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

#ifdef  __cplusplus
extern "C" {
#endif
extern FILE * option_usage_fp;

/* TRANSLATORS: choose the translation for option names wisely because you
                cannot ever change your mind. */
#define zCopyright      (tcpreplay_edit_opt_strs+0)
#define zLicenseDescrip (tcpreplay_edit_opt_strs+275)

/*
 *  global included definitions
 */
#include "defines.h"
#include "tcpreplay.h"
#include "common.h"
#include "config.h"
#include <stdlib.h>
#include <sys/types.h>
#include <unistd.h>


#ifndef NULL
#  define NULL 0
#endif

/*
 *  tcpreplay-edit option static const strings
 */
static char const tcpreplay_edit_opt_strs[5111] =
/*     0 */ "tcpreplay-edit (tcpreplay)\n"
            "Copyright (C) 2000-2010 Aaron Turner, all rights reserved.\n"
            "This is free software. It is licensed for use, modification and\n"
            "redistribution under the terms of the\n"
            "GNU General Public License, version 3 or later\n"
            "    <http://gnu.org/licenses/gpl.html>\n\0"
/*   275 */ "tcpreplay-edit is free software: you can redistribute it and/or modify it\n"
            "under the terms of the GNU General Public License as published by the Free\n"
            "Software Foundation, either version 3 of the License, or (at your option)\n"
            "any later version.\n\n"
            "tcpreplay-edit is distributed in the hope that it will be useful, but\n"
            "WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY\n"
            "or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License\n"
            "for more details.\n\n"
            "You should have received a copy of the GNU General Public License along\n"
            "with this program.  If not, see <http://www.gnu.org/licenses/>.\n\0"
/*   892 */ ":\0"
/*   894 */ "Rewrite TCP/UDP ports\0"
/*   916 */ "PORTMAP\0"
/*   924 */ "portmap\0"
/*   932 */ "Randomize src/dst IPv4/v6 addresses w/ given seed\0"
/*   982 */ "SEED\0"
/*   987 */ "seed\0"
/*   992 */ "Rewrite IPv4/v6 addresses using pseudo-NAT\0"
/*  1035 */ "PNAT\0"
/*  1040 */ "pnat\0"
/*  1045 */ "Rewrite source IPv4/v6 addresses using pseudo-NAT\0"
/*  1095 */ "SRCIPMAP\0"
/*  1104 */ "srcipmap\0"
/*  1113 */ "Rewrite destination IPv4/v6 addresses using pseudo-NAT\0"
/*  1168 */ "DSTIPMAP\0"
/*  1177 */ "dstipmap\0"
/*  1186 */ "Rewrite IP addresses to be between two endpoints\0"
/*  1235 */ "ENDPOINTS\0"
/*  1245 */ "endpoints\0"
/*  1255 */ "Skip rewriting broadcast/multicast IPv4/v6 addresses\0"
/*  1308 */ "SKIPBROADCAST\0"
/*  1322 */ "skipbroadcast\0"
/*  1336 */ "Force recalculation of IPv4/TCP/UDP header checksums\0"
/*  1389 */ "FIXCSUM\0"
/*  1397 */ "fixcsum\0"
/*  1405 */ "Override default MTU length (1500 bytes)\0"
/*  1446 */ "MTU\0"
/*  1450 */ "mtu\0"
/*  1454 */ "Truncate packets larger then specified MTU\0"
/*  1497 */ "MTU_TRUNC\0"
/*  1507 */ "mtu-trunc\0"
/*  1517 */ "Remove Ethernet checksums (FCS) from end of frames\0"
/*  1568 */ "EFCS\0"
/*  1573 */ "efcs\0"
/*  1578 */ "Modify the IPv4/v6 TTL/Hop Limit\0"
/*  1611 */ "TTL\0"
/*  1615 */ "ttl\0"
/*  1619 */ "Set the IPv4 TOS/DiffServ/ECN byte\0"
/*  1654 */ "TOS\0"
/*  1658 */ "tos\0"
/*  1662 */ "Set the IPv6 Traffic Class byte\0"
/*  1694 */ "TCLASS\0"
/*  1701 */ "tclass\0"
/*  1708 */ "Set the IPv6 Flow Label\0"
/*  1732 */ "FLOWLABEL\0"
/*  1742 */ "flowlabel\0"
/*  1752 */ "Pad or truncate packet data to match header length\0"
/*  1803 */ "FIXLEN\0"
/*  1810 */ "fixlen\0"
/*  1817 */ "Skip rewriting broadcast/multicast Layer 2 addresses\0"
/*  1870 */ "SKIPL2BROADCAST\0"
/*  1886 */ "skipl2broadcast\0"
/*  1902 */ "Override output DLT encapsulation\0"
/*  1936 */ "DLT\0"
/*  1940 */ "dlt\0"
/*  1944 */ "Override destination ethernet MAC addresses\0"
/*  1988 */ "ENET_DMAC\0"
/*  1998 */ "enet-dmac\0"
/*  2008 */ "Override source ethernet MAC addresses\0"
/*  2047 */ "ENET_SMAC\0"
/*  2057 */ "enet-smac\0"
/*  2067 */ "Specify ethernet 802.1q VLAN tag mode\0"
/*  2105 */ "ENET_VLAN\0"
/*  2115 */ "enet-vlan\0"
/*  2125 */ "Specify the new ethernet 802.1q VLAN tag value\0"
/*  2172 */ "ENET_VLAN_TAG\0"
/*  2186 */ "enet-vlan-tag\0"
/*  2200 */ "Specify the ethernet 802.1q VLAN CFI value\0"
/*  2243 */ "ENET_VLAN_CFI\0"
/*  2257 */ "enet-vlan-cfi\0"
/*  2271 */ "Specify the ethernet 802.1q VLAN priority\0"
/*  2313 */ "ENET_VLAN_PRI\0"
/*  2327 */ "enet-vlan-pri\0"
/*  2341 */ "Specify HDLC control value\0"
/*  2368 */ "HDLC_CONTROL\0"
/*  2381 */ "hdlc-control\0"
/*  2394 */ "Specify HDLC address\0"
/*  2415 */ "HDLC_ADDRESS\0"
/*  2428 */ "hdlc-address\0"
/*  2441 */ "Set output file DLT type\0"
/*  2466 */ "USER_DLT\0"
/*  2475 */ "user-dlt\0"
/*  2484 */ "Rewrite Data-Link layer with user specified data\0"
/*  2533 */ "USER_DLINK\0"
/*  2544 */ "user-dlink\0"
/*  2555 */ "Enable debugging output\0"
/*  2579 */ "DBUG\0"
/*  2584 */ "dbug\0"
/*  2589 */ "Quiet mode\0"
/*  2600 */ "QUIET\0"
/*  2606 */ "quiet\0"
/*  2612 */ "Select packet timing mode: select, ioport, rdtsc, gtod, nano, abstime\0"
/*  2682 */ "TIMER\0"
/*  2688 */ "timer\0"
/*  2694 */ "gtod\0"
/*  2699 */ "Reduce the amount of time to sleep by specified usec\0"
/*  2752 */ "SLEEP_ACCEL\0"
/*  2764 */ "sleep-accel\0"
/*  2776 */ "Specify the RDTSC clicks/usec\0"
/*  2806 */ "RDTSC_CLICKS\0"
/*  2819 */ "rdtsc-clicks\0"
/*  2832 */ "Print decoded packets via tcpdump to STDOUT\0"
/*  2876 */ "VERBOSE\0"
/*  2884 */ "verbose\0"
/*  2892 */ "Arguments passed to tcpdump decoder\0"
/*  2928 */ "DECODE\0"
/*  2935 */ "decode\0"
/*  2942 */ "Enable caching of packets to internal memory\0"
/*  2987 */ "ENABLE_FILE_CACHE\0"
/*  3005 */ "enable-file-cache\0"
/*  3023 */ "Preloads packets into RAM before sending\0"
/*  3064 */ "PRELOAD_PCAP\0"
/*  3077 */ "preload-pcap\0"
/*  3090 */ "Split traffic via a tcpprep cache file\0"
/*  3129 */ "CACHEFILE\0"
/*  3139 */ "cachefile\0"
/*  3149 */ "Replay two files at a time from a network tap\0"
/*  3195 */ "DUALFILE\0"
/*  3204 */ "dualfile\0"
/*  3213 */ "Server/primary traffic output interface\0"
/*  3253 */ "INTF1\0"
/*  3259 */ "intf1\0"
/*  3265 */ "Client/secondary traffic output interface\0"
/*  3307 */ "INTF2\0"
/*  3313 */ "intf2\0"
/*  3319 */ "List available network interfaces and exit\0"
/*  3362 */ "LISTNICS\0"
/*  3371 */ "listnics\0"
/*  3380 */ "Loop through the capture file X times\0"
/*  3418 */ "LOOP\0"
/*  3423 */ "loop\0"
/*  3428 */ "Override the snaplen and use the actual packet len\0"
/*  3479 */ "PKTLEN\0"
/*  3486 */ "pktlen\0"
/*  3493 */ "Limit the number of packets to send\0"
/*  3529 */ "LIMIT\0"
/*  3535 */ "limit\0"
/*  3541 */ "Modify replay speed to a given multiple\0"
/*  3581 */ "MULTIPLIER\0"
/*  3592 */ "multiplier\0"
/*  3603 */ "Replay packets at a given packets/sec\0"
/*  3641 */ "PPS\0"
/*  3645 */ "pps\0"
/*  3649 */ "Replay packets at a given Mbps\0"
/*  3680 */ "MBPS\0"
/*  3685 */ "mbps\0"
/*  3690 */ "Replay packets as fast as possible\0"
/*  3725 */ "TOPSPEED\0"
/*  3734 */ "topspeed\0"
/*  3743 */ "Replay one packet at a time for each user input\0"
/*  3791 */ "ONEATATIME\0"
/*  3802 */ "oneatatime\0"
/*  3813 */ "Number of packets to send for each time interval\0"
/*  3862 */ "PPS_MULTI\0"
/*  3872 */ "pps-multi\0"
/*  3882 */ "Print the PID of tcpreplay at startup\0"
/*  3920 */ "PID\0"
/*  3924 */ "pid\0"
/*  3928 */ "Print statistics every X seconds\0"
/*  3961 */ "STATS\0"
/*  3967 */ "stats\0"
/*  3973 */ "Print version information\0"
/*  3999 */ "VERSION\0"
/*  4007 */ "version\0"
/*  4015 */ "Display less usage information and exit\0"
/*  4055 */ "LESS_HELP\0"
/*  4065 */ "less-help\0"
/*  4075 */ "Display extended usage information and exit\0"
/*  4119 */ "help\0"
/*  4124 */ "Extended usage information passed thru pager\0"
/*  4169 */ "more-help\0"
/*  4179 */ "Save the option state to a config file\0"
/*  4218 */ "save-opts\0"
/*  4228 */ "Load options from a config file\0"
/*  4260 */ "LOAD_OPTS\0"
/*  4270 */ "no-load-opts\0"
/*  4283 */ "no\0"
/*  4286 */ "TCPREPLAY_EDIT\0"
/*  4301 */ "tcpreplay-edit (tcpreplay) - Replay network traffic stored in pcap files\n"
            "USAGE:  %s [ -<flag> [<val>] | --<name>[{=| }<val>] ]... \\\n"
            "\t\t<pcap_file(s)>\n\0"
/*  4451 */ "$$/\0"
/*  4455 */ ".tcpreplay_editrc\0"
/*  4473 */ "tcpreplay-users@lists.sourceforge.net\0"
/*  4511 */ "\n"
            "tcpreplay is a tool for replaying network traffic from files saved with\n"
            "tcpdump or other tools which write pcap(3) files.\n\0"
/*  4635 */ "\n"
            "The basic operation of tcpreplay is to resend all packets from the input\n"
            "file(s) at the speed at which they were recorded, or a specified data rate,\n"
            "up to as fast as the hardware is capable.\n\n"
            "Optionally, the traffic can be split between two interfaces, written to\n"
            "files, filtered and edited in various ways, providing the means to test\n"
            "firewalls, NIDS and other network devices.\n\n"
            "For more details, please see the Tcpreplay Manual at:\n"
            "http://tcpreplay.synfin.net/wiki/manual\n";

/*
 *  tcpedit option description:
 */
#define TCPEDIT_DESC      (tcpreplay_edit_opt_strs+892)
#define TCPEDIT_FLAGS     (OPTST_DOCUMENT | OPTST_NO_INIT)

/*
 *  portmap option description:
 */
#define PORTMAP_DESC      (tcpreplay_edit_opt_strs+894)
#define PORTMAP_NAME      (tcpreplay_edit_opt_strs+916)
#define PORTMAP_name      (tcpreplay_edit_opt_strs+924)
#define PORTMAP_FLAGS     (OPTST_DISABLED | OPTST_STACKED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  seed option description:
 */
#define SEED_DESC      (tcpreplay_edit_opt_strs+932)
#define SEED_NAME      (tcpreplay_edit_opt_strs+982)
#define SEED_name      (tcpreplay_edit_opt_strs+987)
#define SEED_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  pnat option description with
 *  "Must also have options" and "Incompatible options":
 */
#define PNAT_DESC      (tcpreplay_edit_opt_strs+992)
#define PNAT_NAME      (tcpreplay_edit_opt_strs+1035)
#define PNAT_name      (tcpreplay_edit_opt_strs+1040)
static int const aPnatCantList[] = {
    INDEX_OPT_SRCIPMAP, NO_EQUIVALENT };
#define PNAT_FLAGS     (OPTST_DISABLED | OPTST_STACKED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  srcipmap option description with
 *  "Must also have options" and "Incompatible options":
 */
#define SRCIPMAP_DESC      (tcpreplay_edit_opt_strs+1045)
#define SRCIPMAP_NAME      (tcpreplay_edit_opt_strs+1095)
#define SRCIPMAP_name      (tcpreplay_edit_opt_strs+1104)
static int const aSrcipmapCantList[] = {
    INDEX_OPT_PNAT, NO_EQUIVALENT };
#define SRCIPMAP_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  dstipmap option description with
 *  "Must also have options" and "Incompatible options":
 */
#define DSTIPMAP_DESC      (tcpreplay_edit_opt_strs+1113)
#define DSTIPMAP_NAME      (tcpreplay_edit_opt_strs+1168)
#define DSTIPMAP_name      (tcpreplay_edit_opt_strs+1177)
static int const aDstipmapCantList[] = {
    INDEX_OPT_PNAT, NO_EQUIVALENT };
#define DSTIPMAP_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  endpoints option description with
 *  "Must also have options" and "Incompatible options":
 */
#ifdef HAVE_CACHEFILE_SUPPORT
#define ENDPOINTS_DESC      (tcpreplay_edit_opt_strs+1186)
#define ENDPOINTS_NAME      (tcpreplay_edit_opt_strs+1235)
#define ENDPOINTS_name      (tcpreplay_edit_opt_strs+1245)
static int const aEndpointsMustList[] = {
    INDEX_OPT_CACHEFILE, NO_EQUIVALENT };
#define ENDPOINTS_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

#else   /* disable endpoints */
#define ENDPOINTS_FLAGS     (OPTST_OMITTED | OPTST_NO_INIT)
#define aEndpointsMustList   NULL
#define ENDPOINTS_NAME      NULL
#define ENDPOINTS_DESC      NULL
#define ENDPOINTS_name      NULL
#endif  /* HAVE_CACHEFILE_SUPPORT */

/*
 *  skipbroadcast option description:
 */
#define SKIPBROADCAST_DESC      (tcpreplay_edit_opt_strs+1255)
#define SKIPBROADCAST_NAME      (tcpreplay_edit_opt_strs+1308)
#define SKIPBROADCAST_name      (tcpreplay_edit_opt_strs+1322)
#define SKIPBROADCAST_FLAGS     (OPTST_DISABLED)

/*
 *  fixcsum option description:
 */
#define FIXCSUM_DESC      (tcpreplay_edit_opt_strs+1336)
#define FIXCSUM_NAME      (tcpreplay_edit_opt_strs+1389)
#define FIXCSUM_name      (tcpreplay_edit_opt_strs+1397)
#define FIXCSUM_FLAGS     (OPTST_DISABLED)

/*
 *  mtu option description:
 */
#define MTU_DESC      (tcpreplay_edit_opt_strs+1405)
#define MTU_NAME      (tcpreplay_edit_opt_strs+1446)
#define MTU_name      (tcpreplay_edit_opt_strs+1450)
#define MTU_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  mtu-trunc option description:
 */
#define MTU_TRUNC_DESC      (tcpreplay_edit_opt_strs+1454)
#define MTU_TRUNC_NAME      (tcpreplay_edit_opt_strs+1497)
#define MTU_TRUNC_name      (tcpreplay_edit_opt_strs+1507)
#define MTU_TRUNC_FLAGS     (OPTST_DISABLED)

/*
 *  efcs option description:
 */
#define EFCS_DESC      (tcpreplay_edit_opt_strs+1517)
#define EFCS_NAME      (tcpreplay_edit_opt_strs+1568)
#define EFCS_name      (tcpreplay_edit_opt_strs+1573)
#define EFCS_FLAGS     (OPTST_DISABLED)

/*
 *  ttl option description:
 */
#define TTL_DESC      (tcpreplay_edit_opt_strs+1578)
#define TTL_NAME      (tcpreplay_edit_opt_strs+1611)
#define TTL_name      (tcpreplay_edit_opt_strs+1615)
#define TTL_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  tos option description:
 */
#define TOS_DESC      (tcpreplay_edit_opt_strs+1619)
#define TOS_NAME      (tcpreplay_edit_opt_strs+1654)
#define TOS_name      (tcpreplay_edit_opt_strs+1658)
#define TOS_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  tclass option description:
 */
#define TCLASS_DESC      (tcpreplay_edit_opt_strs+1662)
#define TCLASS_NAME      (tcpreplay_edit_opt_strs+1694)
#define TCLASS_name      (tcpreplay_edit_opt_strs+1701)
#define TCLASS_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  flowlabel option description:
 */
#define FLOWLABEL_DESC      (tcpreplay_edit_opt_strs+1708)
#define FLOWLABEL_NAME      (tcpreplay_edit_opt_strs+1732)
#define FLOWLABEL_name      (tcpreplay_edit_opt_strs+1742)
#define FLOWLABEL_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  fixlen option description:
 */
#define FIXLEN_DESC      (tcpreplay_edit_opt_strs+1752)
#define FIXLEN_NAME      (tcpreplay_edit_opt_strs+1803)
#define FIXLEN_name      (tcpreplay_edit_opt_strs+1810)
#define FIXLEN_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  skipl2broadcast option description:
 */
#define SKIPL2BROADCAST_DESC      (tcpreplay_edit_opt_strs+1817)
#define SKIPL2BROADCAST_NAME      (tcpreplay_edit_opt_strs+1870)
#define SKIPL2BROADCAST_name      (tcpreplay_edit_opt_strs+1886)
#define SKIPL2BROADCAST_FLAGS     (OPTST_DISABLED)

/*
 *  dlt option description:
 */
#define DLT_DESC      (tcpreplay_edit_opt_strs+1902)
#define DLT_NAME      (tcpreplay_edit_opt_strs+1936)
#define DLT_name      (tcpreplay_edit_opt_strs+1940)
#define DLT_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  enet-dmac option description:
 */
#define ENET_DMAC_DESC      (tcpreplay_edit_opt_strs+1944)
#define ENET_DMAC_NAME      (tcpreplay_edit_opt_strs+1988)
#define ENET_DMAC_name      (tcpreplay_edit_opt_strs+1998)
#define ENET_DMAC_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  enet-smac option description:
 */
#define ENET_SMAC_DESC      (tcpreplay_edit_opt_strs+2008)
#define ENET_SMAC_NAME      (tcpreplay_edit_opt_strs+2047)
#define ENET_SMAC_name      (tcpreplay_edit_opt_strs+2057)
#define ENET_SMAC_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  enet-vlan option description:
 */
#define ENET_VLAN_DESC      (tcpreplay_edit_opt_strs+2067)
#define ENET_VLAN_NAME      (tcpreplay_edit_opt_strs+2105)
#define ENET_VLAN_name      (tcpreplay_edit_opt_strs+2115)
#define ENET_VLAN_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  enet-vlan-tag option description with
 *  "Must also have options" and "Incompatible options":
 */
#define ENET_VLAN_TAG_DESC      (tcpreplay_edit_opt_strs+2125)
#define ENET_VLAN_TAG_NAME      (tcpreplay_edit_opt_strs+2172)
#define ENET_VLAN_TAG_name      (tcpreplay_edit_opt_strs+2186)
static int const aEnet_Vlan_TagMustList[] = {
    INDEX_OPT_ENET_VLAN, NO_EQUIVALENT };
#define ENET_VLAN_TAG_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  enet-vlan-cfi option description with
 *  "Must also have options" and "Incompatible options":
 */
#define ENET_VLAN_CFI_DESC      (tcpreplay_edit_opt_strs+2200)
#define ENET_VLAN_CFI_NAME      (tcpreplay_edit_opt_strs+2243)
#define ENET_VLAN_CFI_name      (tcpreplay_edit_opt_strs+2257)
static int const aEnet_Vlan_CfiMustList[] = {
    INDEX_OPT_ENET_VLAN, NO_EQUIVALENT };
#define ENET_VLAN_CFI_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  enet-vlan-pri option description with
 *  "Must also have options" and "Incompatible options":
 */
#define ENET_VLAN_PRI_DESC      (tcpreplay_edit_opt_strs+2271)
#define ENET_VLAN_PRI_NAME      (tcpreplay_edit_opt_strs+2313)
#define ENET_VLAN_PRI_name      (tcpreplay_edit_opt_strs+2327)
static int const aEnet_Vlan_PriMustList[] = {
    INDEX_OPT_ENET_VLAN, NO_EQUIVALENT };
#define ENET_VLAN_PRI_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  hdlc-control option description:
 */
#define HDLC_CONTROL_DESC      (tcpreplay_edit_opt_strs+2341)
#define HDLC_CONTROL_NAME      (tcpreplay_edit_opt_strs+2368)
#define HDLC_CONTROL_name      (tcpreplay_edit_opt_strs+2381)
#define HDLC_CONTROL_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  hdlc-address option description:
 */
#define HDLC_ADDRESS_DESC      (tcpreplay_edit_opt_strs+2394)
#define HDLC_ADDRESS_NAME      (tcpreplay_edit_opt_strs+2415)
#define HDLC_ADDRESS_name      (tcpreplay_edit_opt_strs+2428)
#define HDLC_ADDRESS_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  user-dlt option description:
 */
#define USER_DLT_DESC      (tcpreplay_edit_opt_strs+2441)
#define USER_DLT_NAME      (tcpreplay_edit_opt_strs+2466)
#define USER_DLT_name      (tcpreplay_edit_opt_strs+2475)
#define USER_DLT_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  user-dlink option description:
 */
#define USER_DLINK_DESC      (tcpreplay_edit_opt_strs+2484)
#define USER_DLINK_NAME      (tcpreplay_edit_opt_strs+2533)
#define USER_DLINK_name      (tcpreplay_edit_opt_strs+2544)
#define USER_DLINK_FLAGS     (OPTST_DISABLED | OPTST_STACKED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  dbug option description:
 */
#ifdef DEBUG
#define DBUG_DESC      (tcpreplay_edit_opt_strs+2555)
#define DBUG_NAME      (tcpreplay_edit_opt_strs+2579)
#define DBUG_name      (tcpreplay_edit_opt_strs+2584)
#define DBUG_DFT_ARG   ((char const*)0)
#define DBUG_FLAGS     (OPTST_DISABLED | OPTST_IMM \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

#else   /* disable dbug */
#define DBUG_FLAGS     (OPTST_OMITTED | OPTST_NO_INIT)
#define DBUG_DFT_ARG   NULL
#define DBUG_NAME      NULL
#define DBUG_DESC      NULL
#define DBUG_name      NULL
#endif  /* DEBUG */

/*
 *  quiet option description:
 */
#define QUIET_DESC      (tcpreplay_edit_opt_strs+2589)
#define QUIET_NAME      (tcpreplay_edit_opt_strs+2600)
#define QUIET_name      (tcpreplay_edit_opt_strs+2606)
#define QUIET_FLAGS     (OPTST_DISABLED)

/*
 *  timer option description:
 */
#define TIMER_DESC      (tcpreplay_edit_opt_strs+2612)
#define TIMER_NAME      (tcpreplay_edit_opt_strs+2682)
#define TIMER_name      (tcpreplay_edit_opt_strs+2688)
#define TIMER_DFT_ARG   (tcpreplay_edit_opt_strs+2694)
#define TIMER_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  sleep-accel option description:
 */
#define SLEEP_ACCEL_DESC      (tcpreplay_edit_opt_strs+2699)
#define SLEEP_ACCEL_NAME      (tcpreplay_edit_opt_strs+2752)
#define SLEEP_ACCEL_name      (tcpreplay_edit_opt_strs+2764)
#define SLEEP_ACCEL_DFT_ARG   ((char const*)0)
#define SLEEP_ACCEL_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  rdtsc-clicks option description:
 */
#define RDTSC_CLICKS_DESC      (tcpreplay_edit_opt_strs+2776)
#define RDTSC_CLICKS_NAME      (tcpreplay_edit_opt_strs+2806)
#define RDTSC_CLICKS_name      (tcpreplay_edit_opt_strs+2819)
#define RDTSC_CLICKS_DFT_ARG   ((char const*)0)
#define RDTSC_CLICKS_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  verbose option description:
 */
#ifdef ENABLE_VERBOSE
#define VERBOSE_DESC      (tcpreplay_edit_opt_strs+2832)
#define VERBOSE_NAME      (tcpreplay_edit_opt_strs+2876)
#define VERBOSE_name      (tcpreplay_edit_opt_strs+2884)
#define VERBOSE_FLAGS     (OPTST_DISABLED | OPTST_IMM)

#else   /* disable verbose */
#define VERBOSE_FLAGS     (OPTST_OMITTED | OPTST_NO_INIT)
#define VERBOSE_NAME      NULL
#define VERBOSE_DESC      NULL
#define VERBOSE_name      NULL
#endif  /* ENABLE_VERBOSE */

/*
 *  decode option description with
 *  "Must also have options" and "Incompatible options":
 */
#ifdef ENABLE_VERBOSE
#define DECODE_DESC      (tcpreplay_edit_opt_strs+2892)
#define DECODE_NAME      (tcpreplay_edit_opt_strs+2928)
#define DECODE_name      (tcpreplay_edit_opt_strs+2935)
static int const aDecodeMustList[] = {
    INDEX_OPT_VERBOSE, NO_EQUIVALENT };
#define DECODE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

#else   /* disable decode */
#define DECODE_FLAGS     (OPTST_OMITTED | OPTST_NO_INIT)
#define aDecodeMustList   NULL
#define DECODE_NAME      NULL
#define DECODE_DESC      NULL
#define DECODE_name      NULL
#endif  /* ENABLE_VERBOSE */

/*
 *  enable_file_cache option description with
 *  "Must also have options" and "Incompatible options":
 */
#define ENABLE_FILE_CACHE_DESC      (tcpreplay_edit_opt_strs+2942)
#define ENABLE_FILE_CACHE_NAME      (tcpreplay_edit_opt_strs+2987)
#define ENABLE_FILE_CACHE_name      (tcpreplay_edit_opt_strs+3005)
static int const aEnable_File_CacheMustList[] = {
    INDEX_OPT_LOOP, NO_EQUIVALENT };
#define ENABLE_FILE_CACHE_FLAGS     (OPTST_DISABLED)

/*
 *  preload_pcap option description:
 */
#define PRELOAD_PCAP_DESC      (tcpreplay_edit_opt_strs+3023)
#define PRELOAD_PCAP_NAME      (tcpreplay_edit_opt_strs+3064)
#define PRELOAD_PCAP_name      (tcpreplay_edit_opt_strs+3077)
#define PRELOAD_PCAP_FLAGS     (OPTST_DISABLED)

/*
 *  cachefile option description with
 *  "Must also have options" and "Incompatible options":
 */
#define CACHEFILE_DESC      (tcpreplay_edit_opt_strs+3090)
#define CACHEFILE_NAME      (tcpreplay_edit_opt_strs+3129)
#define CACHEFILE_name      (tcpreplay_edit_opt_strs+3139)
static int const aCachefileMustList[] = {
    INDEX_OPT_INTF2, NO_EQUIVALENT };
static int const aCachefileCantList[] = {
    INDEX_OPT_DUALFILE, NO_EQUIVALENT };
#define CACHEFILE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  dualfile option description with
 *  "Must also have options" and "Incompatible options":
 */
#define DUALFILE_DESC      (tcpreplay_edit_opt_strs+3149)
#define DUALFILE_NAME      (tcpreplay_edit_opt_strs+3195)
#define DUALFILE_name      (tcpreplay_edit_opt_strs+3204)
static int const aDualfileMustList[] = {
    INDEX_OPT_INTF2, NO_EQUIVALENT };
static int const aDualfileCantList[] = {
    INDEX_OPT_CACHEFILE, NO_EQUIVALENT };
#define DUALFILE_FLAGS     (OPTST_DISABLED)

/*
 *  intf1 option description:
 */
#define INTF1_DESC      (tcpreplay_edit_opt_strs+3213)
#define INTF1_NAME      (tcpreplay_edit_opt_strs+3253)
#define INTF1_name      (tcpreplay_edit_opt_strs+3259)
#define INTF1_FLAGS     (OPTST_DISABLED | OPTST_MUST_SET \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  intf2 option description:
 */
#define INTF2_DESC      (tcpreplay_edit_opt_strs+3265)
#define INTF2_NAME      (tcpreplay_edit_opt_strs+3307)
#define INTF2_name      (tcpreplay_edit_opt_strs+3313)
#define INTF2_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  listnics option description:
 */
#ifdef ENABLE_PCAP_FINDALLDEVS
#define LISTNICS_DESC      (tcpreplay_edit_opt_strs+3319)
#define LISTNICS_NAME      (tcpreplay_edit_opt_strs+3362)
#define LISTNICS_name      (tcpreplay_edit_opt_strs+3371)
#define LISTNICS_FLAGS     (OPTST_DISABLED | OPTST_IMM)

#else   /* disable listnics */
#define LISTNICS_FLAGS     (OPTST_OMITTED | OPTST_NO_INIT)
#define LISTNICS_NAME      NULL
#define LISTNICS_DESC      NULL
#define LISTNICS_name      NULL
#endif  /* ENABLE_PCAP_FINDALLDEVS */

/*
 *  loop option description:
 */
#define LOOP_DESC      (tcpreplay_edit_opt_strs+3380)
#define LOOP_NAME      (tcpreplay_edit_opt_strs+3418)
#define LOOP_name      (tcpreplay_edit_opt_strs+3423)
#define LOOP_DFT_ARG   ((char const*)1)
#define LOOP_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  pktlen option description:
 */
#define PKTLEN_DESC      (tcpreplay_edit_opt_strs+3428)
#define PKTLEN_NAME      (tcpreplay_edit_opt_strs+3479)
#define PKTLEN_name      (tcpreplay_edit_opt_strs+3486)
#define PKTLEN_FLAGS     (OPTST_DISABLED)

/*
 *  limit option description:
 */
#define LIMIT_DESC      (tcpreplay_edit_opt_strs+3493)
#define LIMIT_NAME      (tcpreplay_edit_opt_strs+3529)
#define LIMIT_name      (tcpreplay_edit_opt_strs+3535)
#define LIMIT_DFT_ARG   ((char const*)-1)
#define LIMIT_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  multiplier option description with
 *  "Must also have options" and "Incompatible options":
 */
#define MULTIPLIER_DESC      (tcpreplay_edit_opt_strs+3541)
#define MULTIPLIER_NAME      (tcpreplay_edit_opt_strs+3581)
#define MULTIPLIER_name      (tcpreplay_edit_opt_strs+3592)
static int const aMultiplierCantList[] = {
    INDEX_OPT_PPS,
    INDEX_OPT_MBPS,
    INDEX_OPT_ONEATATIME,
    INDEX_OPT_TOPSPEED, NO_EQUIVALENT };
#define MULTIPLIER_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  pps option description with
 *  "Must also have options" and "Incompatible options":
 */
#define PPS_DESC      (tcpreplay_edit_opt_strs+3603)
#define PPS_NAME      (tcpreplay_edit_opt_strs+3641)
#define PPS_name      (tcpreplay_edit_opt_strs+3645)
static int const aPpsCantList[] = {
    INDEX_OPT_MULTIPLIER,
    INDEX_OPT_MBPS,
    INDEX_OPT_ONEATATIME,
    INDEX_OPT_TOPSPEED, NO_EQUIVALENT };
#define PPS_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  mbps option description with
 *  "Must also have options" and "Incompatible options":
 */
#define MBPS_DESC      (tcpreplay_edit_opt_strs+3649)
#define MBPS_NAME      (tcpreplay_edit_opt_strs+3680)
#define MBPS_name      (tcpreplay_edit_opt_strs+3685)
static int const aMbpsCantList[] = {
    INDEX_OPT_MULTIPLIER,
    INDEX_OPT_PPS,
    INDEX_OPT_ONEATATIME,
    INDEX_OPT_TOPSPEED, NO_EQUIVALENT };
#define MBPS_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  topspeed option description with
 *  "Must also have options" and "Incompatible options":
 */
#define TOPSPEED_DESC      (tcpreplay_edit_opt_strs+3690)
#define TOPSPEED_NAME      (tcpreplay_edit_opt_strs+3725)
#define TOPSPEED_name      (tcpreplay_edit_opt_strs+3734)
static int const aTopspeedCantList[] = {
    INDEX_OPT_MBPS,
    INDEX_OPT_MULTIPLIER,
    INDEX_OPT_PPS,
    INDEX_OPT_ONEATATIME, NO_EQUIVALENT };
#define TOPSPEED_FLAGS     (OPTST_DISABLED)

/*
 *  oneatatime option description with
 *  "Must also have options" and "Incompatible options":
 */
#define ONEATATIME_DESC      (tcpreplay_edit_opt_strs+3743)
#define ONEATATIME_NAME      (tcpreplay_edit_opt_strs+3791)
#define ONEATATIME_name      (tcpreplay_edit_opt_strs+3802)
static int const aOneatatimeCantList[] = {
    INDEX_OPT_MBPS,
    INDEX_OPT_PPS,
    INDEX_OPT_MULTIPLIER,
    INDEX_OPT_TOPSPEED, NO_EQUIVALENT };
#define ONEATATIME_FLAGS     (OPTST_DISABLED)

/*
 *  pps-multi option description with
 *  "Must also have options" and "Incompatible options":
 */
#define PPS_MULTI_DESC      (tcpreplay_edit_opt_strs+3813)
#define PPS_MULTI_NAME      (tcpreplay_edit_opt_strs+3862)
#define PPS_MULTI_name      (tcpreplay_edit_opt_strs+3872)
#define PPS_MULTI_DFT_ARG   ((char const*)1)
static int const aPps_MultiMustList[] = {
    INDEX_OPT_PPS, NO_EQUIVALENT };
#define PPS_MULTI_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  pid option description:
 */
#define PID_DESC      (tcpreplay_edit_opt_strs+3882)
#define PID_NAME      (tcpreplay_edit_opt_strs+3920)
#define PID_name      (tcpreplay_edit_opt_strs+3924)
#define PID_FLAGS     (OPTST_DISABLED)

/*
 *  stats option description:
 */
#define STATS_DESC      (tcpreplay_edit_opt_strs+3928)
#define STATS_NAME      (tcpreplay_edit_opt_strs+3961)
#define STATS_name      (tcpreplay_edit_opt_strs+3967)
#define STATS_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  version option description:
 */
#define VERSION_DESC      (tcpreplay_edit_opt_strs+3973)
#define VERSION_NAME      (tcpreplay_edit_opt_strs+3999)
#define VERSION_name      (tcpreplay_edit_opt_strs+4007)
#define VERSION_FLAGS     (OPTST_DISABLED)

/*
 *  less-help option description:
 */
#define LESS_HELP_DESC      (tcpreplay_edit_opt_strs+4015)
#define LESS_HELP_NAME      (tcpreplay_edit_opt_strs+4055)
#define LESS_HELP_name      (tcpreplay_edit_opt_strs+4065)
#define LESS_HELP_FLAGS     (OPTST_DISABLED | OPTST_IMM)

/*
 *  Help/More_Help option descriptions:
 */
#define HELP_DESC       (tcpreplay_edit_opt_strs+4075)
#define HELP_name       (tcpreplay_edit_opt_strs+4119)
#ifdef HAVE_WORKING_FORK
#define MORE_HELP_DESC  (tcpreplay_edit_opt_strs+4124)
#define MORE_HELP_name  (tcpreplay_edit_opt_strs+4169)
#define MORE_HELP_FLAGS (OPTST_IMM | OPTST_NO_INIT)
#else
#define MORE_HELP_DESC  NULL
#define MORE_HELP_name  NULL
#define MORE_HELP_FLAGS (OPTST_OMITTED | OPTST_NO_INIT)
#endif
#define SAVE_OPTS_DESC  (tcpreplay_edit_opt_strs+4179)
#define SAVE_OPTS_name  (tcpreplay_edit_opt_strs+4218)
#define LOAD_OPTS_DESC     (tcpreplay_edit_opt_strs+4228)
#define LOAD_OPTS_NAME     (tcpreplay_edit_opt_strs+4260)
#define NO_LOAD_OPTS_name  (tcpreplay_edit_opt_strs+4270)
#define LOAD_OPTS_pfx      (tcpreplay_edit_opt_strs+4283)
#define LOAD_OPTS_name     (NO_LOAD_OPTS_name + 3)
/*
 *  Declare option callback procedures
 */
#ifdef DEBUG
  static tOptProc doOptDbug;
#else /* not DEBUG */
# define doOptDbug NULL
#endif /* def/not DEBUG */
#ifdef ENABLE_PCAP_FINDALLDEVS
  static tOptProc doOptListnics;
#else /* not ENABLE_PCAP_FINDALLDEVS */
# define doOptListnics NULL
#endif /* def/not ENABLE_PCAP_FINDALLDEVS */
extern tOptProc
    optionBooleanVal,   optionNestedVal,    optionNumericVal,
    optionPagedUsage,   optionPrintVersion, optionResetOpt,
    optionStackArg,     optionTimeDate,     optionTimeVal,
    optionUnstackArg,   optionVendorOption;
static tOptProc
    doOptEnet_Vlan_Cfi, doOptEnet_Vlan_Pri, doOptEnet_Vlan_Tag,
    doOptFlowlabel,     doOptLess_Help,     doOptLimit,
    doOptLoop,          doOptMtu,           doOptPid,
    doOptPps_Multi,     doOptStats,         doOptTclass,
    doOptTos,           doOptVersion,       doUsageOpt;

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 *  Define the tcpreplay-edit Option Descriptions.
 * This is an array of OPTION_CT entries, one for each
 * option that the tcpreplay-edit program responds to.
 */
static tOptDesc optDesc[OPTION_CT] = {
  {  /* entry idx, value */ 0, 0,
     /* equiv idx, value */ 0, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 0, 0,
     /* opt state flags  */ TCPEDIT_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ TCPEDIT_DESC, NULL, NULL,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 1, VALUE_OPT_PORTMAP,
     /* equiv idx, value */ 1, VALUE_OPT_PORTMAP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, -1, 0,
     /* opt state flags  */ PORTMAP_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --portmap */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionStackArg,
     /* desc, NAME, name */ PORTMAP_DESC, PORTMAP_NAME, PORTMAP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 2, VALUE_OPT_SEED,
     /* equiv idx, value */ 2, VALUE_OPT_SEED,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SEED_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --seed */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionNumericVal,
     /* desc, NAME, name */ SEED_DESC, SEED_NAME, SEED_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 3, VALUE_OPT_PNAT,
     /* equiv idx, value */ 3, VALUE_OPT_PNAT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 2, 0,
     /* opt state flags  */ PNAT_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --pnat */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aPnatCantList,
     /* option proc      */ optionStackArg,
     /* desc, NAME, name */ PNAT_DESC, PNAT_NAME, PNAT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 4, VALUE_OPT_SRCIPMAP,
     /* equiv idx, value */ 4, VALUE_OPT_SRCIPMAP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SRCIPMAP_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --srcipmap */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aSrcipmapCantList,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SRCIPMAP_DESC, SRCIPMAP_NAME, SRCIPMAP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 5, VALUE_OPT_DSTIPMAP,
     /* equiv idx, value */ 5, VALUE_OPT_DSTIPMAP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DSTIPMAP_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --dstipmap */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aDstipmapCantList,
     /* option proc      */ NULL,
     /* desc, NAME, name */ DSTIPMAP_DESC, DSTIPMAP_NAME, DSTIPMAP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 6, VALUE_OPT_ENDPOINTS,
     /* equiv idx, value */ 6, VALUE_OPT_ENDPOINTS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ ENDPOINTS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --endpoints */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aEndpointsMustList, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ ENDPOINTS_DESC, ENDPOINTS_NAME, ENDPOINTS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 7, VALUE_OPT_SKIPBROADCAST,
     /* equiv idx, value */ 7, VALUE_OPT_SKIPBROADCAST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SKIPBROADCAST_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --skipbroadcast */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SKIPBROADCAST_DESC, SKIPBROADCAST_NAME, SKIPBROADCAST_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 8, VALUE_OPT_FIXCSUM,
     /* equiv idx, value */ 8, VALUE_OPT_FIXCSUM,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ FIXCSUM_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --fixcsum */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ FIXCSUM_DESC, FIXCSUM_NAME, FIXCSUM_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 9, VALUE_OPT_MTU,
     /* equiv idx, value */ 9, VALUE_OPT_MTU,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MTU_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --mtu */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptMtu,
     /* desc, NAME, name */ MTU_DESC, MTU_NAME, MTU_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 10, VALUE_OPT_MTU_TRUNC,
     /* equiv idx, value */ 10, VALUE_OPT_MTU_TRUNC,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MTU_TRUNC_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --mtu-trunc */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ MTU_TRUNC_DESC, MTU_TRUNC_NAME, MTU_TRUNC_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 11, VALUE_OPT_EFCS,
     /* equiv idx, value */ 11, VALUE_OPT_EFCS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ EFCS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --efcs */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ EFCS_DESC, EFCS_NAME, EFCS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 12, VALUE_OPT_TTL,
     /* equiv idx, value */ 12, VALUE_OPT_TTL,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TTL_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --ttl */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ TTL_DESC, TTL_NAME, TTL_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 13, VALUE_OPT_TOS,
     /* equiv idx, value */ 13, VALUE_OPT_TOS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TOS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --tos */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptTos,
     /* desc, NAME, name */ TOS_DESC, TOS_NAME, TOS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 14, VALUE_OPT_TCLASS,
     /* equiv idx, value */ 14, VALUE_OPT_TCLASS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TCLASS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --tclass */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptTclass,
     /* desc, NAME, name */ TCLASS_DESC, TCLASS_NAME, TCLASS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 15, VALUE_OPT_FLOWLABEL,
     /* equiv idx, value */ 15, VALUE_OPT_FLOWLABEL,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ FLOWLABEL_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --flowlabel */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptFlowlabel,
     /* desc, NAME, name */ FLOWLABEL_DESC, FLOWLABEL_NAME, FLOWLABEL_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 16, VALUE_OPT_FIXLEN,
     /* equiv idx, value */ 16, VALUE_OPT_FIXLEN,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ FIXLEN_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --fixlen */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ FIXLEN_DESC, FIXLEN_NAME, FIXLEN_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 17, VALUE_OPT_SKIPL2BROADCAST,
     /* equiv idx, value */ 17, VALUE_OPT_SKIPL2BROADCAST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SKIPL2BROADCAST_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --skipl2broadcast */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SKIPL2BROADCAST_DESC, SKIPL2BROADCAST_NAME, SKIPL2BROADCAST_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 18, VALUE_OPT_DLT,
     /* equiv idx, value */ 18, VALUE_OPT_DLT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DLT_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --dlt */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ DLT_DESC, DLT_NAME, DLT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 19, VALUE_OPT_ENET_DMAC,
     /* equiv idx, value */ 19, VALUE_OPT_ENET_DMAC,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ ENET_DMAC_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --enet-dmac */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ ENET_DMAC_DESC, ENET_DMAC_NAME, ENET_DMAC_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 20, VALUE_OPT_ENET_SMAC,
     /* equiv idx, value */ 20, VALUE_OPT_ENET_SMAC,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ ENET_SMAC_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --enet-smac */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ ENET_SMAC_DESC, ENET_SMAC_NAME, ENET_SMAC_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 21, VALUE_OPT_ENET_VLAN,
     /* equiv idx, value */ 21, VALUE_OPT_ENET_VLAN,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ ENET_VLAN_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --enet-vlan */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ ENET_VLAN_DESC, ENET_VLAN_NAME, ENET_VLAN_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 22, VALUE_OPT_ENET_VLAN_TAG,
     /* equiv idx, value */ 22, VALUE_OPT_ENET_VLAN_TAG,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ ENET_VLAN_TAG_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --enet-vlan-tag */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aEnet_Vlan_TagMustList, NULL,
     /* option proc      */ doOptEnet_Vlan_Tag,
     /* desc, NAME, name */ ENET_VLAN_TAG_DESC, ENET_VLAN_TAG_NAME, ENET_VLAN_TAG_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 23, VALUE_OPT_ENET_VLAN_CFI,
     /* equiv idx, value */ 23, VALUE_OPT_ENET_VLAN_CFI,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ ENET_VLAN_CFI_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --enet-vlan-cfi */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aEnet_Vlan_CfiMustList, NULL,
     /* option proc      */ doOptEnet_Vlan_Cfi,
     /* desc, NAME, name */ ENET_VLAN_CFI_DESC, ENET_VLAN_CFI_NAME, ENET_VLAN_CFI_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 24, VALUE_OPT_ENET_VLAN_PRI,
     /* equiv idx, value */ 24, VALUE_OPT_ENET_VLAN_PRI,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ ENET_VLAN_PRI_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --enet-vlan-pri */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aEnet_Vlan_PriMustList, NULL,
     /* option proc      */ doOptEnet_Vlan_Pri,
     /* desc, NAME, name */ ENET_VLAN_PRI_DESC, ENET_VLAN_PRI_NAME, ENET_VLAN_PRI_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 25, VALUE_OPT_HDLC_CONTROL,
     /* equiv idx, value */ 25, VALUE_OPT_HDLC_CONTROL,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ HDLC_CONTROL_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --hdlc-control */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionNumericVal,
     /* desc, NAME, name */ HDLC_CONTROL_DESC, HDLC_CONTROL_NAME, HDLC_CONTROL_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 26, VALUE_OPT_HDLC_ADDRESS,
     /* equiv idx, value */ 26, VALUE_OPT_HDLC_ADDRESS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ HDLC_ADDRESS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --hdlc-address */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionNumericVal,
     /* desc, NAME, name */ HDLC_ADDRESS_DESC, HDLC_ADDRESS_NAME, HDLC_ADDRESS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 27, VALUE_OPT_USER_DLT,
     /* equiv idx, value */ 27, VALUE_OPT_USER_DLT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ USER_DLT_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --user-dlt */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionNumericVal,
     /* desc, NAME, name */ USER_DLT_DESC, USER_DLT_NAME, USER_DLT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 28, VALUE_OPT_USER_DLINK,
     /* equiv idx, value */ 28, VALUE_OPT_USER_DLINK,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 2, 0,
     /* opt state flags  */ USER_DLINK_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --user-dlink */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionStackArg,
     /* desc, NAME, name */ USER_DLINK_DESC, USER_DLINK_NAME, USER_DLINK_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 29, VALUE_OPT_DBUG,
     /* equiv idx, value */ 29, VALUE_OPT_DBUG,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DBUG_FLAGS, 0,
     /* last opt argumnt */ { DBUG_DFT_ARG },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptDbug,
     /* desc, NAME, name */ DBUG_DESC, DBUG_NAME, DBUG_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 30, VALUE_OPT_QUIET,
     /* equiv idx, value */ 30, VALUE_OPT_QUIET,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ QUIET_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --quiet */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ QUIET_DESC, QUIET_NAME, QUIET_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 31, VALUE_OPT_TIMER,
     /* equiv idx, value */ 31, VALUE_OPT_TIMER,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TIMER_FLAGS, 0,
     /* last opt argumnt */ { TIMER_DFT_ARG },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ TIMER_DESC, TIMER_NAME, TIMER_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 32, VALUE_OPT_SLEEP_ACCEL,
     /* equiv idx, value */ 32, VALUE_OPT_SLEEP_ACCEL,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SLEEP_ACCEL_FLAGS, 0,
     /* last opt argumnt */ { SLEEP_ACCEL_DFT_ARG },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionNumericVal,
     /* desc, NAME, name */ SLEEP_ACCEL_DESC, SLEEP_ACCEL_NAME, SLEEP_ACCEL_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 33, VALUE_OPT_RDTSC_CLICKS,
     /* equiv idx, value */ 33, VALUE_OPT_RDTSC_CLICKS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ RDTSC_CLICKS_FLAGS, 0,
     /* last opt argumnt */ { RDTSC_CLICKS_DFT_ARG },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionNumericVal,
     /* desc, NAME, name */ RDTSC_CLICKS_DESC, RDTSC_CLICKS_NAME, RDTSC_CLICKS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 34, VALUE_OPT_VERBOSE,
     /* equiv idx, value */ 34, VALUE_OPT_VERBOSE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ VERBOSE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --verbose */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ VERBOSE_DESC, VERBOSE_NAME, VERBOSE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 35, VALUE_OPT_DECODE,
     /* equiv idx, value */ 35, VALUE_OPT_DECODE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DECODE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --decode */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aDecodeMustList, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ DECODE_DESC, DECODE_NAME, DECODE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 36, VALUE_OPT_ENABLE_FILE_CACHE,
     /* equiv idx, value */ 36, VALUE_OPT_ENABLE_FILE_CACHE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ ENABLE_FILE_CACHE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --enable_file_cache */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aEnable_File_CacheMustList, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ ENABLE_FILE_CACHE_DESC, ENABLE_FILE_CACHE_NAME, ENABLE_FILE_CACHE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 37, VALUE_OPT_PRELOAD_PCAP,
     /* equiv idx, value */ 37, VALUE_OPT_PRELOAD_PCAP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PRELOAD_PCAP_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --preload_pcap */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ PRELOAD_PCAP_DESC, PRELOAD_PCAP_NAME, PRELOAD_PCAP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 38, VALUE_OPT_CACHEFILE,
     /* equiv idx, value */ 38, VALUE_OPT_CACHEFILE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ CACHEFILE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --cachefile */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aCachefileMustList, aCachefileCantList,
     /* option proc      */ NULL,
     /* desc, NAME, name */ CACHEFILE_DESC, CACHEFILE_NAME, CACHEFILE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 39, VALUE_OPT_DUALFILE,
     /* equiv idx, value */ 39, VALUE_OPT_DUALFILE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DUALFILE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --dualfile */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aDualfileMustList, aDualfileCantList,
     /* option proc      */ NULL,
     /* desc, NAME, name */ DUALFILE_DESC, DUALFILE_NAME, DUALFILE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 40, VALUE_OPT_INTF1,
     /* equiv idx, value */ 40, VALUE_OPT_INTF1,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 1, 1, 0,
     /* opt state flags  */ INTF1_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --intf1 */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ INTF1_DESC, INTF1_NAME, INTF1_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 41, VALUE_OPT_INTF2,
     /* equiv idx, value */ 41, VALUE_OPT_INTF2,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ INTF2_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --intf2 */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ INTF2_DESC, INTF2_NAME, INTF2_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 42, VALUE_OPT_LISTNICS,
     /* equiv idx, value */ 42, VALUE_OPT_LISTNICS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LISTNICS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --listnics */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptListnics,
     /* desc, NAME, name */ LISTNICS_DESC, LISTNICS_NAME, LISTNICS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 43, VALUE_OPT_LOOP,
     /* equiv idx, value */ 43, VALUE_OPT_LOOP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LOOP_FLAGS, 0,
     /* last opt argumnt */ { LOOP_DFT_ARG },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptLoop,
     /* desc, NAME, name */ LOOP_DESC, LOOP_NAME, LOOP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 44, VALUE_OPT_PKTLEN,
     /* equiv idx, value */ 44, VALUE_OPT_PKTLEN,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PKTLEN_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --pktlen */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ PKTLEN_DESC, PKTLEN_NAME, PKTLEN_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 45, VALUE_OPT_LIMIT,
     /* equiv idx, value */ 45, VALUE_OPT_LIMIT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LIMIT_FLAGS, 0,
     /* last opt argumnt */ { LIMIT_DFT_ARG },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptLimit,
     /* desc, NAME, name */ LIMIT_DESC, LIMIT_NAME, LIMIT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 46, VALUE_OPT_MULTIPLIER,
     /* equiv idx, value */ 46, VALUE_OPT_MULTIPLIER,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MULTIPLIER_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --multiplier */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aMultiplierCantList,
     /* option proc      */ NULL,
     /* desc, NAME, name */ MULTIPLIER_DESC, MULTIPLIER_NAME, MULTIPLIER_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 47, VALUE_OPT_PPS,
     /* equiv idx, value */ 47, VALUE_OPT_PPS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PPS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --pps */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aPpsCantList,
     /* option proc      */ optionNumericVal,
     /* desc, NAME, name */ PPS_DESC, PPS_NAME, PPS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 48, VALUE_OPT_MBPS,
     /* equiv idx, value */ 48, VALUE_OPT_MBPS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MBPS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --mbps */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aMbpsCantList,
     /* option proc      */ NULL,
     /* desc, NAME, name */ MBPS_DESC, MBPS_NAME, MBPS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 49, VALUE_OPT_TOPSPEED,
     /* equiv idx, value */ 49, VALUE_OPT_TOPSPEED,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TOPSPEED_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --topspeed */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aTopspeedCantList,
     /* option proc      */ NULL,
     /* desc, NAME, name */ TOPSPEED_DESC, TOPSPEED_NAME, TOPSPEED_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 50, VALUE_OPT_ONEATATIME,
     /* equiv idx, value */ 50, VALUE_OPT_ONEATATIME,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ ONEATATIME_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --oneatatime */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aOneatatimeCantList,
     /* option proc      */ NULL,
     /* desc, NAME, name */ ONEATATIME_DESC, ONEATATIME_NAME, ONEATATIME_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 51, VALUE_OPT_PPS_MULTI,
     /* equiv idx, value */ 51, VALUE_OPT_PPS_MULTI,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PPS_MULTI_FLAGS, 0,
     /* last opt argumnt */ { PPS_MULTI_DFT_ARG },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ aPps_MultiMustList, NULL,
     /* option proc      */ doOptPps_Multi,
     /* desc, NAME, name */ PPS_MULTI_DESC, PPS_MULTI_NAME, PPS_MULTI_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 52, VALUE_OPT_PID,
     /* equiv idx, value */ 52, VALUE_OPT_PID,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PID_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --pid */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptPid,
     /* desc, NAME, name */ PID_DESC, PID_NAME, PID_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 53, VALUE_OPT_STATS,
     /* equiv idx, value */ 53, VALUE_OPT_STATS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ STATS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --stats */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptStats,
     /* desc, NAME, name */ STATS_DESC, STATS_NAME, STATS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 54, VALUE_OPT_VERSION,
     /* equiv idx, value */ 54, VALUE_OPT_VERSION,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ VERSION_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --version */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptVersion,
     /* desc, NAME, name */ VERSION_DESC, VERSION_NAME, VERSION_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 55, VALUE_OPT_LESS_HELP,
     /* equiv idx, value */ 55, VALUE_OPT_LESS_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LESS_HELP_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --less-help */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptLess_Help,
     /* desc, NAME, name */ LESS_HELP_DESC, LESS_HELP_NAME, LESS_HELP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_HELP, VALUE_OPT_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doUsageOpt,
     /* desc, NAME, name */ HELP_DESC, NULL, HELP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_MORE_HELP, VALUE_OPT_MORE_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_MORE_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MORE_HELP_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ optionPagedUsage,
     /* desc, NAME, name */ MORE_HELP_DESC, NULL, MORE_HELP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_SAVE_OPTS, VALUE_OPT_SAVE_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_SAVE_OPTS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_SET_ARGTYPE(OPARG_TYPE_STRING)
                          | OPTST_ARG_OPTIONAL | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SAVE_OPTS_DESC, NULL, SAVE_OPTS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_LOAD_OPTS, VALUE_OPT_LOAD_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_LOAD_OPTS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ OPTST_SET_ARGTYPE(OPARG_TYPE_STRING)
			  | OPTST_DISABLE_IMM, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionLoadOpt,
     /* desc, NAME, name */ LOAD_OPTS_DESC, LOAD_OPTS_NAME, LOAD_OPTS_name,
     /* disablement strs */ NO_LOAD_OPTS_name, LOAD_OPTS_pfx }
};

tOptDesc * const tcpedit_tcpedit_optDesc_p = optDesc + 0;

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the tcpreplay-edit Option Environment
 */
#define zPROGNAME       (tcpreplay_edit_opt_strs+4286)
#define zUsageTitle     (tcpreplay_edit_opt_strs+4301)
#define zRcName         (tcpreplay_edit_opt_strs+4455)
static char const * const apzHomeList[2] = {
    tcpreplay_edit_opt_strs+4451,
    NULL };
#define zBugsAddr       (tcpreplay_edit_opt_strs+4473)
#define zExplain        (tcpreplay_edit_opt_strs+4511)
#define zDetail         (tcpreplay_edit_opt_strs+4635)
#define zFullVersion    (NULL)
/* extracted from optcode.tlib near line 350 */

#if defined(ENABLE_NLS)
# define OPTPROC_BASE OPTPROC_TRANSLATE
  static tOptionXlateProc translate_option_strings;
#else
# define OPTPROC_BASE OPTPROC_NONE
# define translate_option_strings NULL
#endif /* ENABLE_NLS */


#define tcpreplay_edit_full_usage (NULL)

#define tcpreplay_edit_short_usage (NULL)

#endif /* not defined __doxygen__ */

/*
 *  Create the static procedure(s) declared above.
 */
/**
 * The callout function that invokes the optionUsage function.
 *
 * @param pOptions the AutoOpts option description structure
 * @param pOptDesc the descriptor for the "help" (usage) option.
 * @noreturn
 */
static void
doUsageOpt(tOptions * pOptions, tOptDesc * pOptDesc)
{
    optionUsage(&tcpreplay_editOptions, TCPREPLAY_EDIT_EXIT_SUCCESS);
    /* NOTREACHED */
    (void)pOptDesc;
    (void)pOptions;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the mtu option.
 *
 * @param pOptions the tcpreplay-edit options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptMtu(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 1, MAXPACKET } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the tos option.
 *
 * @param pOptions the tcpreplay-edit options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptTos(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0, 255 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the tclass option.
 *
 * @param pOptions the tcpreplay-edit options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptTclass(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0, 255 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the flowlabel option.
 *
 * @param pOptions the tcpreplay-edit options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptFlowlabel(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0, 1048575 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the enet-vlan-tag option.
 *
 * @param pOptions the tcpreplay-edit options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptEnet_Vlan_Tag(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0, 4095 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the enet-vlan-cfi option.
 *
 * @param pOptions the tcpreplay-edit options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptEnet_Vlan_Cfi(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0, 1 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the enet-vlan-pri option.
 *
 * @param pOptions the tcpreplay-edit options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptEnet_Vlan_Pri(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0, 7 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the dbug option, when DEBUG is #define-d.
 *
 * @param pOptions the tcpreplay-edit options data structure
 * @param pOptDesc the option descriptor for this option.
 */
#ifdef DEBUG
static void
doOptDbug(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0, 5 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}
#endif /* defined DEBUG */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the listnics option, when ENABLE_PCAP_FINDALLDEVS is #define-d.
 *
 * @param pOptions the tcpreplay-edit options data structure
 * @param pOptDesc the option descriptor for this option.
 */
#ifdef ENABLE_PCAP_FINDALLDEVS
static void
doOptListnics(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /* extracted from tcpreplay_opts.def, line 312 */

    interface_list_t *list = get_interface_list();
    list_interfaces(list);
    free(list);
    exit(0);

    (void)pOptDesc;
    (void)pOptions;
}
#endif /* defined ENABLE_PCAP_FINDALLDEVS */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the loop option.
 *
 * @param pOptions the tcpreplay-edit options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptLoop(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0, LONG_MAX } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the limit option.
 *
 * @param pOptions the tcpreplay-edit options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptLimit(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 1, LONG_MAX } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the pps-multi option.
 *
 * @param pOptions the tcpreplay-edit options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptPps_Multi(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 1, LONG_MAX } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the pid option.
 *
 * @param pOptions the tcpreplay-edit options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptPid(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /* extracted from tcpreplay_opts.def, line 462 */

    fprintf(stderr, "PID: %d\n", getpid());

    (void)pOptDesc;
    (void)pOptions;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the stats option.
 *
 * @param pOptions the tcpreplay-edit options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptStats(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 1, LONG_MAX } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:
    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the version option.
 *
 * @param pOptions the tcpreplay-edit options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptVersion(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /* extracted from tcpreplay_opts.def, line 485 */

    fprintf(stderr, "tcpreplay version: %s (build %s)", VERSION, git_version());
#ifdef DEBUG
    fprintf(stderr, " (debug)");
#endif
    fprintf(stderr, "\n");
    fprintf(stderr, "Copyright 2000-2010 by Aaron Turner <aturner at synfin dot net>\n");
    fprintf(stderr, "The entire Tcpreplay Suite is licensed under the GPLv3\n");
    fprintf(stderr, "Cache file supported: %s\n", CACHEVERSION);
#ifdef HAVE_LIBDNET
    fprintf(stderr, "Compiled against libdnet: %s\n", LIBDNET_VERSION);
#else
    fprintf(stderr, "Not compiled with libdnet.\n");
#endif
#ifdef HAVE_WINPCAP
    fprintf(stderr, "Compiled against winpcap: %s\n", get_pcap_version());
#else
    fprintf(stderr, "Compiled against libpcap: %s\n", get_pcap_version());
#endif
#ifdef ENABLE_64BITS
    fprintf(stderr, "64 bit packet counters: enabled\n");
#else
    fprintf(stderr, "64 bit packet counters: disabled\n");
#endif
#ifdef ENABLE_VERBOSE
    fprintf(stderr, "Verbose printing via tcpdump: enabled\n");
#else
    fprintf(stderr, "Verbose printing via tcpdump: disabled\n");
#endif
#ifdef TCPREPLAY_EDIT
    fprintf(stderr, "Packet editing: enabled\n");
#else
    fprintf(stderr, "Packet editing: disabled\n");
#endif
#ifdef ENABLE_FRAGROUTE
    fprintf(stderr, "Fragroute engine: enabled\n");
#else
    fprintf(stderr, "Fragroute engine: disabled\n");
#endif
    fprintf(stderr, "Injection method: %s\n", sendpacket_get_method());
    exit(0);

    (void)pOptDesc;
    (void)pOptions;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the less-help option.
 *
 * @param pOptions the tcpreplay-edit options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptLess_Help(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /* extracted from tcpreplay_opts.def, line 537 */

    USAGE(EXIT_FAILURE);

    (void)pOptDesc;
    (void)pOptions;
}
/* extracted from optmain.tlib near line 1146 */

/**
 * The directory containing the data associated with tcpreplay-edit.
 */
#ifndef  PKGDATADIR
# define PKGDATADIR ""
#endif

/**
 * Information about the person or institution that packaged tcpreplay-edit
 * for the current distribution.
 */
#ifndef  WITH_PACKAGER
# define tcpreplay_edit_packager_info NULL
#else
static char const tcpreplay_edit_packager_info[] =
    "Packaged by " WITH_PACKAGER

# ifdef WITH_PACKAGER_VERSION
        " ("WITH_PACKAGER_VERSION")"
# endif

# ifdef WITH_PACKAGER_BUG_REPORTS
    "\nReport tcpreplay_edit bugs to " WITH_PACKAGER_BUG_REPORTS
# endif
    "\n";
#endif
#ifndef __doxygen__

#endif /* __doxygen__ */
/**
 * The option definitions for tcpreplay-edit.  The one structure that
 * binds them all.
 */
tOptions tcpreplay_editOptions = {
    OPTIONS_STRUCT_VERSION,
    0, NULL,                    /* original argc + argv    */
    ( OPTPROC_BASE
    + OPTPROC_ERRSTOP
    + OPTPROC_SHORTOPT
    + OPTPROC_LONGOPT
    + OPTPROC_NO_REQ_OPT
    + OPTPROC_ARGS_REQ
    + OPTPROC_GNUUSAGE ),
    0, NULL,                    /* current option index, current option */
    NULL,         NULL,         zPROGNAME,
    zRcName,      zCopyright,   zLicenseDescrip,
    zFullVersion, apzHomeList,  zUsageTitle,
    zExplain,     zDetail,      optDesc,
    zBugsAddr,                  /* address to send bugs to */
    NULL, NULL,                 /* extensions/saved state  */
    optionUsage, /* usage procedure */
    translate_option_strings,   /* translation procedure */
    /*
     *  Indexes to special options
     */
    { INDEX_OPT_MORE_HELP, /* more-help option index */
      INDEX_OPT_SAVE_OPTS, /* save option index */
      NO_EQUIVALENT, /* '-#' option index */
      9 /* index of default opt */
    },
    60 /* full option count */, 56 /* user option count */,
    tcpreplay_edit_full_usage, tcpreplay_edit_short_usage,
    NULL, NULL,
    PKGDATADIR, tcpreplay_edit_packager_info
};

#if ENABLE_NLS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <autoopts/usage-txt.h>

static char* AO_gettext(char const* pz);
static void  coerce_it(void** s);

/**
 * AutoGen specific wrapper function for gettext.
 * It relies on the macro _() to convert from English to the target
 * language, then strdup-duplicates the result string.
 *
 * @param[in] pz the input text used as a lookup key.
 * @returns the translated text (if there is one),
 *   or the original text (if not).
 */
static char *
AO_gettext(char const* pz)
{
    char* pzRes;
    if (pz == NULL)
        return NULL;
    pzRes = _(pz);
    if (pzRes == pz)
        return pzRes;
    pzRes = strdup(pzRes);
    if (pzRes == NULL) {
        fputs(_("No memory for duping translated strings\n"), stderr);
        exit(TCPREPLAY_EDIT_EXIT_FAILURE);
    }
    return pzRes;
}

static void coerce_it(void** s) { *s = AO_gettext(*s);
}

/**
 * Translate all the translatable strings in the tcpreplay_editOptions
 * structure defined above.  This is done only once.
 */
static void
translate_option_strings(void)
{
    tOptions * const pOpt = &tcpreplay_editOptions;

    /*
     *  Guard against re-translation.  It won't work.  The strings will have
     *  been changed by the first pass through this code.  One shot only.
     */
    if (option_usage_text.field_ct != 0) {
        /*
         *  Do the translations.  The first pointer follows the field count
         *  field.  The field count field is the size of a pointer.
         */
        tOptDesc * pOD = pOpt->pOptDesc;
        char **    ppz = (char**)(void*)&(option_usage_text);
        int        ix  = option_usage_text.field_ct;

        do {
            ppz++;
            *ppz = AO_gettext(*ppz);
        } while (--ix > 0);

        coerce_it((void*)&(pOpt->pzCopyright));
        coerce_it((void*)&(pOpt->pzCopyNotice));
        coerce_it((void*)&(pOpt->pzFullVersion));
        coerce_it((void*)&(pOpt->pzUsageTitle));
        coerce_it((void*)&(pOpt->pzExplain));
        coerce_it((void*)&(pOpt->pzDetail));
        coerce_it((void*)&(pOpt->pzPackager));
        option_usage_text.field_ct = 0;

        for (ix = pOpt->optCt; ix > 0; ix--, pOD++)
            coerce_it((void*)&(pOD->pzText));
    }

    if ((pOpt->fOptSet & OPTPROC_NXLAT_OPT_CFG) == 0) {
        tOptDesc * pOD = pOpt->pOptDesc;
        int        ix;

        for (ix = pOpt->optCt; ix > 0; ix--, pOD++) {
            coerce_it((void*)&(pOD->pz_Name));
            coerce_it((void*)&(pOD->pz_DisableName));
            coerce_it((void*)&(pOD->pz_DisablePfx));
        }
        /* prevent re-translation */
        tcpreplay_editOptions.fOptSet |= OPTPROC_NXLAT_OPT_CFG | OPTPROC_NXLAT_OPT;
    }
}

#endif /* ENABLE_NLS */

#ifdef  __cplusplus
}
#endif
/* tcpreplay_edit_opts.c ends here */
