'\" t
.\"     Title: tcpreplay
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2026-07-19
.\"    Manual: Tcpreplay Suite
.\"    Source: Tcpreplay Suite
.\"  Language: English
.\"
.TH "TCPREPLAY" "1" "2026-07-19" "Tcpreplay Suite" "Tcpreplay Suite"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
tcpreplay \- Replay network traffic stored in pcap files
.SH "SYNOPSIS"
.sp
\fBtcpreplay\fP [\fIOPTION\fP]... <pcap_file(s)> | <pcap_dir(s)>
.SH "DESCRIPTION"
.sp
tcpreplay is a tool for replaying network traffic from files saved with tcpdump or other tools which write pcap(3) files.
.sp
The basic operation of tcpreplay is to resend  all  packets  from  the input file(s) at the speed at which they were recorded, or a specified data rate, up to as fast as the hardware is capable.
.sp
+
Optionally, the traffic can be split between two interfaces, written to files, filtered and edited in various ways, providing the means to test firewalls, NIDS and other network devices.
.sp
+
On Linux, raw IP (layer 3 only) interfaces such as WireGuard and tun are supported automatically: any layer 2 header in the input file (Ethernet including VLAN tags, Linux SLL, loopback, ...) is stripped and packets are sent as bare IPv4/IPv6. Non\-IP packets such as ARP cannot be sent on these interfaces and are reported as failed.
.sp
+
For more details, please see the Tcpreplay Manual at: \c
.URL "http://tcpreplay.appneta.com" "" ""
.SH "OPTIONS"
.sp
\fB\-d\fP, \fB\-\-dbug\fP=\fInumber\fP
.RS 4
Enable debugging output. Range: 0 to 5. Default: \f(CR0\fP.
.sp
If configured with \-\-enable\-debug, then you can specify a verbosity level for debugging output.  Higher numbers increase verbosity.
.RE
.sp
\fB\-q\fP, \fB\-\-quiet\fP
.RS 4
Quiet mode.
.sp
Print nothing except the statistics at the end of the run
.RE
.sp
\fB\-T\fP, \fB\-\-timer\fP=\fIstring\fP
.RS 4
Select packet timing mode: select, ioport, gtod, nano. Default: \f(CRgtod\fP.
.sp
Allows you to select the packet timing method to use:
.sp
\fBnano\fP
.RS 4
Use nanosleep() API
.RE
.sp
\fBselect\fP
.RS 4
Use select() API
.RE
.sp
\fBioport\fP
.RS 4
Write to the i386 IO Port 0x80
.RE
.sp
\fBgtod [default]\fP
.RS 4
Use a gettimeofday() loop
.RE
.RE
.sp
\fB\-\-maxsleep\fP=\fInumber\fP
.RS 4
Sleep for no more then X milliseconds between packets. Default: \f(CR0\fP.
.sp
Set a limit for the maximum number of milliseconds that tcpreplay will sleep between packets.  Effectively prevents long delays between packets without effecting the majority of packets.  Default is disabled.
.RE
.sp
\fB\-v\fP, \fB\-\-verbose\fP
.RS 4
Print decoded packets via tcpdump to STDOUT.
.RE
.sp
\fB\-A\fP, \fB\-\-decode\fP=\fIstring\fP
.RS 4
Arguments passed to tcpdump decoder. Requires: \fB\-\-verbose\fP.
.sp
When enabling verbose mode (\fI\-v\fP) you may also specify one or more additional  arguments to pass to \f(CRtcpdump\fP to modify the way packets are decoded.  By default, \-n and \-l are used.   Be  sure  to quote the arguments like: \-A "\-axxx" so that they are not interpreted by tcpreplay.   Please see the tcpdump(1) man page for a complete list of options.
.RE
.sp
\fB\-K\fP, \fB\-\-preload_pcap\fP
.RS 4
Preloads packets into RAM before sending.
.sp
This option loads the specified pcap(s) into RAM before starting to send in order to improve replay performance while introducing a startup performance hit. Preloading can be used with or without \fI\-\-loop\fP. This option also suppresses flow statistics collection for every iteration, which can significantly reduce memory usage. Flow statistics are predicted based on options supplied and statistics collected from the first loop iteration.
.RE
.sp
\fB\-c\fP, \fB\-\-cachefile\fP=\fIstring\fP
.RS 4
Split traffic via a tcpprep cache file. Requires: \fB\-\-intf2\fP. Cannot be combined with: \fB\-\-dualfile\fP.
.sp
If you have a pcap file you would like to use to send bi\-directional traffic through a device (firewall, router, IDS, etc) then using tcpprep you can create a cachefile which tcpreplay will use to split the traffic across two network interfaces.
.RE
.sp
\fB\-2\fP, \fB\-\-dualfile\fP
.RS 4
Replay two files at a time from a network tap. Requires: \fB\-\-intf2\fP. Cannot be combined with: \fB\-\-cachefile\fP.
.sp
If you captured network traffic using a network tap, then you can end up with two pcap files\- one for each direction.  This option will replay these two files at the same time, one on each interface and inter\-mix them using the timestamps in each.
.RE
.sp
\fB\-i\fP, \fB\-\-intf1\fP=\fIstring\fP
.RS 4
Client to server/RX/primary traffic output interface. This option is required.
.sp
Required network interface used to send either all traffic or traffic which is marked as \*(Aqprimary\*(Aq via tcpprep.  Primary traffic is usually client\-to\-server or inbound (RX) on khial virtual interfaces.
.RE
.sp
\fB\-I\fP, \fB\-\-intf2\fP=\fIstring\fP
.RS 4
Server to client/TX/secondary traffic output interface.
.sp
Optional network interface used to send traffic which is marked as \*(Aqsecondary\*(Aq via tcpprep.  Secondary traffic is usually server\-to\-client or outbound (TX) on khial virtual interfaces.  Generally, it only makes sense to use this option with \-\-cachefile.
.RE
.sp
\fB\-w\fP, \fB\-\-write\fP=\fIstring\fP
.RS 4
Pcap file to receive traffic outputs. Cannot be combined with: \fB\-\-intf2\fP.
.sp
Optional pcap file name used to receive traffic.
.RE
.sp
\fB\-\-include\fP=\fIstring\fP
.RS 4
Send only selected packet numbers. Cannot be combined with: \fB\-\-exclude\fP.
.sp
Override default of processing all packets stored in the capture file and only send packets that are part of a supplied list of packet numbers.
.sp
.if n .RS 4
.nf
.fam C
\-x P:1\-5,9,15,72\-
.fam
.fi
.if n .RE
.sp
would skip packets 1 through 5, the 9th and 15th packet, and packets 72 until the end of the file
.RE
.sp
\fB\-\-exclude\fP=\fIstring\fP
.RS 4
Send all but selected packet numbers. Cannot be combined with: \fB\-\-include\fP.
.sp
Override default of processing all packets stored in the capture file and only send packets that are NOT part of a supplied list of packet numbers.
.sp
.if n .RS 4
.nf
.fam C
\-x P:1\-5,9,15,72\-
.fam
.fi
.if n .RE
.sp
would skip packets 1 through 5, the 9th and 15th packet, and packets 72 until the end of the file
.RE
.sp
\fB\-\-listnics\fP
.RS 4
List available network interfaces and exit.
.RE
.sp
\fB\-l\fP, \fB\-\-loop\fP=\fInumber\fP
.RS 4
Loop through the capture file X times. Range: 0 to any. Default: \f(CR1\fP.
.RE
.sp
\fB\-\-loopdelay\-ms\fP=\fInumber\fP
.RS 4
Delay between loops in milliseconds. Range: 0 to any. Default: \f(CR0\fP. Requires: \fB\-\-loop\fP. Cannot be combined with: \fB\-\-loopdelay\-ns\fP.
.RE
.sp
\fB\-\-loopdelay\-ns\fP=\fInumber\fP
.RS 4
Delay between loops in nanoseconds. Range: 0 to any. Default: \f(CR0\fP. Requires: \fB\-\-loop\fP. Cannot be combined with: \fB\-\-loopdelay\-ms\fP.
.sp
By default, tcpreplay will use loop delay with microsecond accuracy (loopdelay\-ms). In order to use loop delay with nanosecond accuracy you need to use nano packet timing mode.
.RE
.sp
\fB\-\-pktlen\fP
.RS 4
Override the snaplen and use the actual packet len.
.sp
By default, tcpreplay will send packets based on the size of the "snaplen" stored in the pcap file which is usually the correct thing to do.  However, occasionally, tools will store more bytes then told to.  By specifying this option, tcpreplay will ignore the snaplen field and instead try to send packets based on the original packet length.  Bad things may happen if you specify this option.
.RE
.sp
\fB\-L\fP, \fB\-\-limit\fP=\fInumber\fP
.RS 4
Limit the number of packets to send. Range: 1 to any. Default: \f(CR\-1\fP.
.sp
By default, tcpreplay will send all the packets.  Alternatively, you can specify a maximum number of packets to send.
.RE
.sp
\fB\-\-duration\fP=\fInumber\fP
.RS 4
Limit the number of seconds to send. Range: 1 to any. Default: \f(CR\-1\fP.
.sp
By default, tcpreplay will send all the packets.  Alternatively, you can specify a maximum number of seconds to transmit.
.RE
.sp
\fB\-x\fP, \fB\-\-multiplier\fP=\fIstring\fP
.RS 4
Modify replay speed to a given multiple. Cannot be combined with: \fB\-\-pps\fP, \fB\-\-mbps\fP, \fB\-\-oneatatime\fP, \fB\-\-topspeed\fP.
.sp
Specify a value to modify the packet replay speed. Examples:
.sp
.if n .RS 4
.nf
.fam C
    2.0 will replay traffic at twice the speed captured
    0.7 will replay traffic at 70% the speed captured
.fam
.fi
.if n .RE
.RE
.sp
\fB\-p\fP, \fB\-\-pps\fP=\fIstring\fP
.RS 4
Replay packets at a given packets/sec. Cannot be combined with: \fB\-\-multiplier\fP, \fB\-\-mbps\fP, \fB\-\-oneatatime\fP, \fB\-\-topspeed\fP.
.sp
Specify a value to regulate the packet replay to a specific packet\-per\-second rate. Examples:
.sp
.if n .RS 4
.nf
.fam C
    200 will replay traffic at 200 packets per second
    0.25 will replay traffic at 15 packets per minute
.fam
.fi
.if n .RE
.RE
.sp
\fB\-M\fP, \fB\-\-mbps\fP=\fIstring\fP
.RS 4
Replay packets at a given Mbps. Cannot be combined with: \fB\-\-multiplier\fP, \fB\-\-pps\fP, \fB\-\-oneatatime\fP, \fB\-\-topspeed\fP.
.sp
Specify a floating point value for the Mbps rate that tcpreplay should send packets at.
.RE
.sp
\fB\-t\fP, \fB\-\-topspeed\fP
.RS 4
Replay packets as fast as possible. Cannot be combined with: \fB\-\-mbps\fP, \fB\-\-multiplier\fP, \fB\-\-pps\fP, \fB\-\-oneatatime\fP.
.RE
.sp
\fB\-o\fP, \fB\-\-oneatatime\fP
.RS 4
Replay one packet at a time for each user input. Cannot be combined with: \fB\-\-mbps\fP, \fB\-\-pps\fP, \fB\-\-multiplier\fP, \fB\-\-topspeed\fP.
.sp
Allows you to step through one or more packets at a time.
.RE
.sp
\fB\-\-pps\-multi\fP=\fInumber\fP
.RS 4
Number of packets to send for each time interval. Range: 1 to any. Default: \f(CR1\fP. Requires: \fB\-\-pps\fP.
.sp
When trying to send packets at very high rates, the time between each packet can be so short that it is impossible to accurately sleep for the required period of time.  This option allows you to send multiple packets at a time, thus allowing for longer sleep times which can be more accurately implemented.
.RE
.sp
\fB\-\-unique\-ip\fP
.RS 4
Modify IP addresses each loop iteration to generate unique flows. Requires: \fB\-\-loop\fP.
.sp
Ensure IPv4 and IPv6 packets will be unique for each \fI\-\-loop\fP iteration. This is done in a way that will not alter packet CRC, and therefore will generally not affect performance. This option will significantly increase the flows/sec over generated over multiple loop iterations.
.RE
.sp
\fB\-\-unique\-ip\-loops\fP=\fIstring\fP
.RS 4
Number of times to loop before assigning new unique ip. Requires: \fB\-\-unique\-ip\fP.
.sp
Number of \fI\-\-loop\fP iterations before a new unique IP is assigned. Default is 1. Assumes both \fI\-\-loop\fP and \fI\-\-unique\-ip\fP.
.RE
.sp
\fB\-\-netmap\fP
.RS 4
Write packets directly to netmap enabled network adapter.
.sp
This feature will detect netmap capable network drivers on Linux and BSD systems. If detected, the network driver is bypassed for the execution duration, and network buffers will be written to directly. This will allow you to achieve full line rates on commodity network adapters, similar to rates achieved by commercial network traffic generators. Note that bypassing the network driver will disrupt other applications connected through the test interface. See INSTALL for more information.
.sp
This feature can also be enabled by specifying an interface as \*(Aqnetmap:<intf>\*(Aq or \*(Aqvale:<intf>. For example \*(Aqnetmap:eth0\*(Aq specifies netmap over interface eth0.
.RE
.sp
\fB\-\-nm\-delay\fP=\fInumber\fP
.RS 4
Netmap startup delay. Default: \f(CR10\fP.
.sp
Number of seconds to delay after netmap is loaded. Required to ensure interfaces are fully up before netmap transmit. Requires netmap option. Default is 10 seconds.
.RE
.sp
\fB\-\-no\-flow\-stats\fP
.RS 4
Suppress printing and tracking flow count, rates and expirations.
.sp
Suppress the collection and printing of flow statistics. This option may improve performance when not using \fI\-\-preload\-pcap\fP option, otherwise its only function is to suppress printing.
.sp
The flow feature will track and print statistics of the flows being sent. A flow is loosely defined as a unique combination of a 5\-tuple, i.e. source IP, destination IP, source port, destination port and protocol.
.sp
If \fI\-\-loop\fP is specified, the flows from one iteration to the next will not be unique, unless the packets are altered. Use \fI\-\-unique\-ip\fP or \fItcpreplay\-edit\fP to alter packets between iterations.
.RE
.sp
\fB\-\-flow\-expiry\fP=\fInumber\fP
.RS 4
Number of inactive seconds before a flow is considered expired. Range: 0 to any. Default: \f(CR0\fP. Cannot be combined with: \fB\-\-no\-flow\-stats\fP.
.sp
This option will track and report flow expirations based on the flow idle times. The timestamps within the pcap file are used to determine the expiry, not the actual timestamp of the packets are replayed. For example, a value of 30 suggests that if no traffic is seen on a flow for 30 seconds, any subsequent traffic would be considered a new flow, and thereby will increment the flows and flows per second (fps) statistics.
.sp
This option can be used to optimize flow timeout settings for flow products. Setting the timeout low may lead to flows being dropped when in fact the flow is simply slow to respond. Configuring your flow timeouts too high may increase resources required by your flow product.
.sp
Note that using this option while replaying at higher than original speeds can lead to inflated flows and fps counts.
.sp
Default is 0 (no expiry) and a typical value is 30\-120 seconds.
.RE
.sp
\fB\-P\fP, \fB\-\-pid\fP
.RS 4
Print the PID of tcpreplay at startup.
.RE
.sp
\fB\-\-stats\fP=\fInumber\fP
.RS 4
Print statistics every X seconds, or every loop if \*(Aq0\*(Aq. Range: 0 to any.
.sp
Note that timed delays are a "best effort" and long delays between sending packets may cause equally long delays between printing statistics.
.RE
.sp
\fB\-W\fP, \fB\-\-suppress\-warnings\fP
.RS 4
suppress printing warning messages.
.RE
.sp
\fB\-\-xdp\fP
.RS 4
Write packets directly to AF_XDP enabled network adapter.
.sp
This feature will detect AF_XDP capable network drivers on Linux systems that have \*(Aqlibxdp\-dev\*(Aq and \*(Aqlibbpf\-dev\*(Aq installed. If detected, the network stack is bypassed and packets are sent directly to an eBPF enabled driver directly. This will allow you to achieve full line rates on commodity network adapters, similar to rates achieved by commercial network traffic generators.
.RE
.sp
\fB\-\-xdp\-batch\-size\fP=\fInumber\fP
.RS 4
The maximum number of packets that can be submitted to the AF_XDP TX ring at once. Range: 1 to 4096. Default: \f(CR1\fP. Requires: \fB\-\-xdp\fP, \fB\-\-topspeed\fP. Cannot be combined with: \fB\-\-oneatatime\fP, \fB\-\-pps\-multi\fP.
.sp
Only allowed if sending at top speed. Values higher than 1 may improve performance at the cost of accuracy.
.RE
.sp
\fB\-\-io\-uring\fP
.RS 4
Send packets asynchronously via Linux io_uring.
.sp
This feature is available on Linux systems with a kernel that supports io_uring and \*(Aqliburing\-dev\*(Aq installed. Packets are still sent through a PF_PACKET raw socket, but sends are submitted asynchronously through an io_uring submission queue, which reduces per\-packet syscall overhead and lets the kernel process transmissions while tcpreplay prepares the next packet.
.RE
.sp
\fB\-V\fP, \fB\-\-version\fP
.RS 4
Print version information.
.RE
.sp
\fB\-h\fP, \fB\-\-less\-help\fP
.RS 4
Display less usage information and exit.
.RE
.sp
\fB\-H\fP, \fB\-\-help\fP
.RS 4
Display usage information and exit.
.RE
.sp
\fB\-\-more\-help\fP
.RS 4
Pass the extended usage information through a pager.
.RE
.sp
\fB\-\-save\-opts\fP[=\fIstring\fP]
.RS 4
Save the current option state to a config file.
.RE
.sp
\fB\-\-load\-opts\fP=\fIstring\fP, \fB\-\-no\-load\-opts\fP
.RS 4
Load options from a config file; \fB\-\-no\-load\-opts\fP disables this.
.RE
.SH "OPTION PRESETS"
.sp
Any option that is not marked as \fInot presettable\fP may be preset by loading values from configuration ("RC" or ".INI") file(s).
The homerc file is \fI$$/\fP, unless that is a directory; in that case \fI.tcpreplayrc\fP is searched for within it.
.SH "FILES"
.sp
See \fBOPTION PRESETS\fP for configuration files.
.SH "EXIT STATUS"
.sp
One of the following exit values will be returned:
.sp
\fB0\fP (EXIT_SUCCESS)
.RS 4
Successful program execution.
.RE
.sp
\fB1\fP (EXIT_FAILURE)
.RS 4
The operation failed or the command syntax was not valid.
.RE
.sp
\fB66\fP (EX_NOINPUT)
.RS 4
A specified configuration file could not be loaded.
.RE
.sp
\fB70\fP (EX_SOFTWARE)
.RS 4
libopts had an internal operational error. Please report it to \c
.MTO "autogen\-users\(atlists.sourceforge.net" "" "."
Thank you.
.RE
.SH "AUTHORS"
.sp
Copyright 2013\-2026 Fred Klassen \- AppNeta
.sp
Copyright 2000\-2012 Aaron Turner
.sp
For support please use the \c
.MTO "tcpreplay\-users\(atlists.sourceforge.net" "" ""
mailing list.
.sp
The latest version of this software is always available from: \c
.URL "http://tcpreplay.appneta.com/" "" ""
.SH "COPYRIGHT"
.sp
Copyright \(co 2000\-2026 Aaron Turner and Fred Klassen, all rights reserved.
This program is released under the terms of the GNU General Public License, version 3 or later.
.SH "BUGS"
.sp
Please send bug reports to: \c
.MTO "tcpreplay\-users\(atlists.sourceforge.net" "" ""
.SH "NOTES"
.sp
This manual page was generated from the tcpreplay option definitions.