# FindPCAP.cmake — locate libpcap the same way configure.ac does (issue #688).
#
# Input cache variables:
#   WITH_LIBPCAP        - prefix of a libpcap install/build tree (like --with-libpcap=DIR)
#   ENABLE_PCAPCONFIG   - use pcap-config for discovery (like --enable-pcapconfig)
#   ENABLE_STATIC_LINK  - prefer static libraries (like --enable-static-link)
#
# Output:
#   PCAP_FOUND
#   PCAP_INCLUDE_DIR    - directory containing pcap.h
#   PCAP_INCLUDE_FILE   - full path of pcap.h (used for @LPCAPINC@ in defines.h)
#   PCAP_LIBRARIES      - libraries to link
#   PCAP_BPF_H_FILE     - full path of the libpcap bpf header, if usable

set(PCAP_FOUND FALSE)
set(PCAP_LIBRARIES "")
set(PCAP_INCLUDE_DIR "")
set(PCAP_INCLUDE_FILE "")

if(ENABLE_PCAPCONFIG AND NOT WITH_LIBPCAP)
    find_program(PCAP_CONFIG_EXECUTABLE pcap-config)
    if(PCAP_CONFIG_EXECUTABLE)
        if(ENABLE_STATIC_LINK)
            execute_process(COMMAND ${PCAP_CONFIG_EXECUTABLE} --libs --static
                            OUTPUT_VARIABLE _pcap_libs OUTPUT_STRIP_TRAILING_WHITESPACE)
        else()
            execute_process(COMMAND ${PCAP_CONFIG_EXECUTABLE} --libs
                            OUTPUT_VARIABLE _pcap_libs OUTPUT_STRIP_TRAILING_WHITESPACE)
        endif()
        execute_process(COMMAND ${PCAP_CONFIG_EXECUTABLE} --cflags
                        OUTPUT_VARIABLE _pcap_cflags OUTPUT_STRIP_TRAILING_WHITESPACE)
        if(_pcap_libs)
            separate_arguments(_pcap_libs)
            set(PCAP_LIBRARIES ${_pcap_libs})
            separate_arguments(_pcap_cflags)
            foreach(_flag ${_pcap_cflags})
                if(_flag MATCHES "^-I(.*)")
                    set(PCAP_INCLUDE_DIR "${CMAKE_MATCH_1}")
                endif()
            endforeach()
            if(NOT PCAP_INCLUDE_DIR)
                find_path(PCAP_INCLUDE_DIR pcap.h)
            endif()
            set(PCAP_FOUND TRUE)
            set(PCAP_VIA_PCAPCONFIG TRUE)
        else()
            message(WARNING "Unable to find libpcap using pcap-config")
        endif()
    endif()
endif()

if(NOT PCAP_FOUND)
    # Same search prefixes as configure.ac, plus Apple Silicon homebrew
    set(_pcap_prefixes /usr/local /opt/local /usr /wpdpack
        /usr/local/opt/libpcap /opt/homebrew/opt/libpcap)
    if(WITH_LIBPCAP)
        set(_pcap_prefixes ${WITH_LIBPCAP})
    endif()
    if(CMAKE_OSX_SYSROOT)
        list(APPEND _pcap_prefixes ${CMAKE_OSX_SYSROOT}/usr)
    elseif(APPLE)
        # mirror configure.ac's xcrun SDK discovery when no sysroot was given
        execute_process(COMMAND xcrun --show-sdk-path
                        OUTPUT_VARIABLE _macos_sdk_path OUTPUT_STRIP_TRAILING_WHITESPACE
                        ERROR_QUIET)
        if(_macos_sdk_path AND IS_DIRECTORY ${_macos_sdk_path})
            list(APPEND _pcap_prefixes ${_macos_sdk_path}/usr)
        endif()
    endif()

    foreach(_prefix ${_pcap_prefixes})
        foreach(_inc ${_prefix}/include/pcap.h ${_prefix}/pcap.h ${_prefix}/pcap/pcap.h)
            if(EXISTS ${_inc})
                get_filename_component(PCAP_INCLUDE_DIR ${_inc} DIRECTORY)
                set(PCAP_INCLUDE_FILE ${_inc})
                break()
            endif()
        endforeach()
        if(NOT PCAP_INCLUDE_FILE)
            continue()
        endif()

        if(ENABLE_STATIC_LINK)
            set(_pcap_names libpcap.a libpcap.A.tbd)
        else()
            set(_pcap_names libpcap${CMAKE_SHARED_LIBRARY_SUFFIX} libpcap.so libpcap.dylib libpcap.tbd)
        endif()
        foreach(_dir . lib lib64 lib32 lib/${CMAKE_LIBRARY_ARCHITECTURE} ${CMAKE_LIBRARY_ARCHITECTURE})
            foreach(_name ${_pcap_names})
                file(GLOB _cand "${_prefix}/${_dir}/${_name}*")
                if(_cand)
                    list(SORT _cand)
                    list(GET _cand 0 _pcap_lib)
                    if(ENABLE_STATIC_LINK)
                        set(PCAP_LIBRARIES ${_pcap_lib})
                    else()
                        get_filename_component(_pcap_libdir ${_pcap_lib} DIRECTORY)
                        set(PCAP_LIBRARIES -L${_pcap_libdir} -lpcap)
                        set(PCAP_LIBRARY_DIR ${_pcap_libdir})
                    endif()
                    set(PCAP_FOUND TRUE)
                    break()
                endif()
            endforeach()
            if(PCAP_FOUND)
                break()
            endif()
        endforeach()

        if(PCAP_FOUND)
            set(PCAP_PREFIX ${_prefix})
            break()
        elseif(WITH_LIBPCAP)
            message(FATAL_ERROR "Unable to find matching library for header file in ${WITH_LIBPCAP}")
        endif()
        set(PCAP_INCLUDE_FILE "")
    endforeach()
endif()

if(NOT PCAP_FOUND)
    message(FATAL_ERROR "libpcap not found")
endif()

if(NOT PCAP_INCLUDE_FILE)
    if(EXISTS ${PCAP_INCLUDE_DIR}/pcap/pcap.h)
        set(PCAP_INCLUDE_FILE ${PCAP_INCLUDE_DIR}/pcap/pcap.h)
    else()
        set(PCAP_INCLUDE_FILE ${PCAP_INCLUDE_DIR}/pcap.h)
    endif()
endif()

message(STATUS "Found libpcap: ${PCAP_INCLUDE_FILE} (${PCAP_LIBRARIES})")

# libpcap bpf header (INCLUDE_PCAP_BPF_HEADER / PCAP_BPF_H_FILE)
foreach(_bpf ${PCAP_INCLUDE_DIR}/pcap/bpf.h ${PCAP_INCLUDE_DIR}/pcap-bpf.h)
    if(EXISTS ${_bpf})
        set(PCAP_BPF_H_FILE ${_bpf})
        break()
    endif()
endforeach()

# netmap-aware libpcap? (checks for pcap-netmap.c next to the headers)
if(EXISTS ${PCAP_INCLUDE_DIR}/pcap-netmap.c)
    set(HAVE_LIBPCAP_NETMAP 1)
endif()
