name: cpp-linter

on: pull_request

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Build Application"
          sudo apt-get -y install libpcap-dev autogen
          ./autogen.sh
          ./configure --disable-local-libopts
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          version: 14
          lines-changed-only: true
          files-changed-only: false
          ignore: .github|docs|scripts

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        # for testing...
        # run: echo "Some files failed the linting checks!"
        # for development...
        run: exit 0 # exit the job with a success status
        # for actual deployment...
        # run: exit 1 # exit the job with a failure status

